// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Beacons.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid, segment } from "./core.js";
import type { AccessState } from "./shared.js";

export interface BeaconAccessRequest {
    feature: BeaconFeature;
}

export interface BeaconAccessResult {
    access: AccessState;
}

/** Advertising as an iBeacon. */
export interface BeaconBroadcast {
    uuid: string;
    major: number;
    minor: number;
    /** The power a receiver sees at one meter, dBm; -59 when null. It calibrates distance and does not change the radio. */
    txPower?: number | null;
}

export interface BeaconBroadcastStatus {
    broadcasting: boolean;
}

/** A part of the beacons bridge, each with its own permission and registration. */
export type BeaconFeature = "Ranging" | "Monitoring" | "Eddystone" | "Broadcasting";

/** A distance bucket derived from the estimated distance. */
export type BeaconProximity = "Unknown" | "Immediate" | "Near" | "Far";

/** One observation of an iBeacon while ranging. */
export interface BeaconReading {
    /** The identifier of the ranged region it belongs to. */
    region: string;
    uuid: string;
    major: number;
    minor: number;
    /** dBm. */
    rssi: number;
    proximity: BeaconProximity;
    /** Estimated meters. */
    distance: number;
    /** The beacon's calibrated power at one meter. Null on Apple platforms, where CoreLocation hides it. */
    txPower: number | null;
    timestamp: string;
}

/** A set of iBeacons, by UUID and optionally narrowed by major and then minor. */
export interface BeaconRegion {
    /** Names the region; ranging or monitoring one with an identifier already in use replaces it. */
    identifier: string;
    uuid: string;
    major: number | null;
    /** Needs `major`. */
    minor: number | null;
    /** Monitoring only. */
    notifyOnEntry: boolean;
    /** Monitoring only. */
    notifyOnExit: boolean;
}

export type BeaconRegionState = "Unknown" | "Entered" | "Exited";

export interface BeaconRegionStatus {
    identifier: string;
    state: BeaconRegionState;
}

/** The permission state of each feature, without prompting. A feature the app did not register is `NotSupported`. */
export interface BeaconsStatus {
    ranging: AccessState;
    monitoring: AccessState;
    eddystone: AccessState;
    /** Whether the app registered broadcasting and the platform has it. */
    broadcastingSupported: boolean;
    /** Whether the device is advertising as a beacon now. */
    broadcasting: boolean;
}

/** An Eddystone frame. Which fields are set depends on `frameType`: `Uid` has `namespace` and `instance`, `Url` has `url`, `Eid` has `ephemeralId`, and those three have `txPower`, `distance` and `proximity`. `Tlm` is the beacon's telemetry. */
export interface EddystoneFrame {
    frameType: EddystoneFrameType;
    /** The advertising device: a GUID on Apple platforms, a MAC address on Android. */
    peripheralId: string;
    rssi: number;
    timestamp: string;
    /** 10 bytes, hex. */
    namespace: string | null;
    /** 6 bytes, hex. */
    instance: string | null;
    url: string | null;
    /** Hex. */
    ephemeralId: string | null;
    txPower: number | null;
    distance: number | null;
    proximity: BeaconProximity | null;
    batteryVolts: number | null;
    temperatureCelsius: number | null;
    advertisementCount: number | null;
    /** Telemetry: time since the beacon powered up. */
    uptime: string | null;
    encrypted: boolean | null;
}

export type EddystoneFrameType = "Uid" | "Url" | "Tlm" | "Eid";

export interface EddystoneUidBroadcast {
    /** 10 bytes, hex. */
    namespace: string;
    /** 6 bytes, hex. */
    instance: string;
    /** The power at zero meters, dBm; -18 when null. */
    txPower?: number | null;
}

export interface EddystoneUrlBroadcast {
    /** Must compress to 17 bytes or fewer under Eddystone's URL encoding. */
    url: string;
    /** The power at zero meters, dBm; -18 when null. */
    txPower?: number | null;
}

/** Beacons: range iBeacons in the foreground, monitor iBeacon regions in the background, scan for Eddystone frames, and advertise the device as a beacon. Android, iOS, Mac Catalyst, macOS and Windows; a feature the app did not register, or a platform without it, fails with 501. */
export class BeaconsBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** The permission state of each feature, and whether the device is broadcasting. */
    getStatus(options?: { signal?: AbortSignal }): Promise<BeaconsStatus> {
        return call<BeaconsStatus>(this.transport, "GET", `beacons/status`, { signal: options?.signal });
    }

    /** Requests the permission a feature needs — background location for monitoring on Apple platforms. */
    requestAccess(request: BeaconAccessRequest, options?: { signal?: AbortSignal }): Promise<BeaconAccessResult> {
        return call<BeaconAccessResult>(this.transport, "POST", `beacons/access`, { json: request, signal: options?.signal });
    }

    /** The regions being ranged. */
    getRangedRegions(options?: { signal?: AbortSignal }): Promise<BeaconRegion[]> {
        return call<BeaconRegion[]>(this.transport, "GET", `beacons/ranging`, { signal: options?.signal });
    }

    /** Starts ranging a region; readings arrive through `onBeacon`, so listen first: without a listener it fails with 409. Several regions can be ranged at once. Ranging is a foreground activity, and it stops once nothing listens to it. */
    startRanging(region: BeaconRegion, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `beacons/ranging`, { json: region, signal: options?.signal });
    }

    /** Stops ranging every region. */
    stopAllRanging(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `beacons/ranging`, { signal: options?.signal });
    }

    /** Stops ranging one region. */
    stopRanging(identifier: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `beacons/ranging/${segment(identifier)}`, { signal: options?.signal });
    }

    /** The regions being monitored. Monitoring survives the app restarting. */
    getMonitoredRegions(options?: { signal?: AbortSignal }): Promise<BeaconRegion[]> {
        return call<BeaconRegion[]>(this.transport, "GET", `beacons/regions`, { signal: options?.signal });
    }

    /** Starts monitoring a region; transitions arrive through `onRegion` while a page is open, and to the web app's `beacon` handler otherwise. Fails with 409 without permission. */
    startMonitoring(region: BeaconRegion, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `beacons/regions`, { json: region, signal: options?.signal });
    }

    /** Stops monitoring every region. */
    stopAllMonitoring(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `beacons/regions`, { signal: options?.signal });
    }

    /** Stops monitoring one region. */
    stopMonitoring(identifier: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `beacons/regions/${segment(identifier)}`, { signal: options?.signal });
    }

    /** Whether the device is inside a monitored region now. Fails with 404 for a region not monitored. */
    getRegionState(identifier: string, options?: { signal?: AbortSignal }): Promise<BeaconRegionStatus> {
        return call<BeaconRegionStatus>(this.transport, "GET", `beacons/regions/${segment(identifier)}/state`, { signal: options?.signal });
    }

    /** Starts scanning for Eddystone frames; they arrive through `onEddystone`, so listen first: without a listener it fails with 409. The scan stops once nothing listens to it. */
    startEddystoneScan(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `beacons/eddystone`, { signal: options?.signal });
    }

    /** Stops scanning for Eddystone frames. */
    stopEddystoneScan(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `beacons/eddystone`, { signal: options?.signal });
    }

    /** Whether the device is advertising as a beacon. */
    getBroadcast(options?: { signal?: AbortSignal }): Promise<BeaconBroadcastStatus> {
        return call<BeaconBroadcastStatus>(this.transport, "GET", `beacons/broadcast`, { signal: options?.signal });
    }

    /** Advertises as an iBeacon, replacing any running advertisement. Apple platforms stop it in the background. */
    broadcastIBeacon(broadcast: BeaconBroadcast, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `beacons/broadcast/ibeacon`, { json: broadcast, signal: options?.signal });
    }

    /** Advertises an Eddystone-UID frame, replacing any running advertisement. */
    broadcastEddystoneUid(broadcast: EddystoneUidBroadcast, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `beacons/broadcast/eddystone-uid`, { json: broadcast, signal: options?.signal });
    }

    /** Advertises an Eddystone-URL frame, replacing any running advertisement. Fails with 400 for a URL too long to encode. */
    broadcastEddystoneUrl(broadcast: EddystoneUrlBroadcast, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `beacons/broadcast/eddystone-url`, { json: broadcast, signal: options?.signal });
    }

    /** Stops advertising. */
    stopBroadcast(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `beacons/broadcast`, { signal: options?.signal });
    }

    /** An iBeacon seen while ranging. */
    onBeacon(handler: (payload: BeaconReading) => void): Promise<() => void> {
        return this.transport.subscribe("beacons.ranged", json => handler(JSON.parse(json) as BeaconReading));
    }

    /** The device entered or left a monitored region, while the page is open. */
    onRegion(handler: (payload: BeaconRegionStatus) => void): Promise<() => void> {
        return this.transport.subscribe("beacons.region", json => handler(JSON.parse(json) as BeaconRegionStatus));
    }

    /** An Eddystone frame seen while scanning. */
    onEddystone(handler: (payload: EddystoneFrame) => void): Promise<() => void> {
        return this.transport.subscribe("beacons.eddystone", json => handler(JSON.parse(json) as EddystoneFrame));
    }
}
