// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.BluetoothLE.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid, segment } from "./core";
import type { AccessState } from "./shared";

export interface BleCharacteristic {
    serviceUuid: string;
    uuid: string;
    isNotifying: boolean;
    properties: BleCharacteristicProperty[];
}

/** What a characteristic supports. */
export type BleCharacteristicProperty = "Broadcast" | "Read" | "WriteWithoutResponse" | "Write" | "Notify" | "Indicate" | "AuthenticatedSignedWrites" | "ExtendedProperties" | "NotifyEncryptionRequired" | "IndicateEncryptionRequired";

export interface BleCharacteristicValue {
    serviceUuid: string;
    characteristicUuid: string;
    /** Base64 in JSON. */
    data: string | null;
}

export interface BleConnectRequest {
    /** Reconnect when the peripheral comes back in range. */
    autoConnect?: boolean;
    /** How long to wait for the connection; 30 seconds when null. */
    timeoutMs?: number | null;
}

export type BleConnectionState = "Disconnected" | "Disconnecting" | "Connected" | "Connecting";

export interface BleError {
    /** `scan` or `notify`. */
    operation: string;
    peripheralUuid: string | null;
    message: string;
}

export interface BleNotification {
    peripheralUuid: string;
    serviceUuid: string;
    characteristicUuid: string;
    /** Base64 in JSON. */
    data: string | null;
}

export interface BlePeripheral {
    uuid: string;
    name: string | null;
    status: BleConnectionState;
    mtu: number;
}

export interface BlePeripheralStatus {
    uuid: string;
    status: BleConnectionState;
}

export interface BleRssi {
    rssi: number;
}

export interface BleScanRequest {
    /** Only report peripherals advertising one of these services; every peripheral when empty. */
    serviceUuids?: string[] | null;
}

/** An advertisement. */
export interface BleScanResult {
    uuid: string;
    name: string | null;
    rssi: number;
    localName: string | null;
    isConnectable: boolean | null;
    serviceUuids: string[] | null;
    txPower: number | null;
    manufacturerId: number | null;
    /** Base64 in JSON. */
    manufacturerData: string | null;
}

export interface BleService {
    uuid: string;
}

export interface BleStatus {
    access: AccessState;
    isScanning: boolean;
}

export interface BleWriteRequest {
    /** Base64 in JSON. */
    data: Blob | ArrayBuffer | Uint8Array;
    /** Wait for the peripheral to acknowledge the write. */
    withResponse?: boolean;
}

/** Bluetooth LE central: scan, connect, discover services and characteristics, read, write and subscribe to notifications. Peripheral ids are GUIDs on Apple platforms and MAC addresses on Android. On Linux every call fails with 501. A peripheral must have been seen in a scan first; otherwise calls on it fail with 404. */
export class BluetoothLEBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** Whether Bluetooth is available to the app, and whether a scan is running. */
    getStatus(options?: { signal?: AbortSignal }): Promise<BleStatus> {
        return call<BleStatus>(this.transport, "GET", `ble/status`, { signal: options?.signal });
    }

    /** Requests Bluetooth access. */
    requestAccess(options?: { signal?: AbortSignal }): Promise<BleStatus> {
        return call<BleStatus>(this.transport, "POST", `ble/access`, { signal: options?.signal });
    }

    /** Starts scanning; results arrive through `onScanResult`. Starting again replaces the running scan. */
    startScan(request: BleScanRequest, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `ble/scan`, { json: request, signal: options?.signal });
    }

    /** Stops scanning. */
    stopScan(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `ble/scan`, { signal: options?.signal });
    }

    /** The peripherals connected now. */
    getConnectedPeripherals(options?: { signal?: AbortSignal }): Promise<BlePeripheral[]> {
        return call<BlePeripheral[]>(this.transport, "GET", `ble/peripherals`, { signal: options?.signal });
    }

    /** A peripheral seen in a scan. */
    getPeripheral(uuid: string, options?: { signal?: AbortSignal }): Promise<BlePeripheral> {
        return call<BlePeripheral>(this.transport, "GET", `ble/peripherals/${segment(uuid)}`, { signal: options?.signal });
    }

    /** Connects. Fails with 504 on timeout, 409 when the connection fails. */
    connect(uuid: string, request: BleConnectRequest, options?: { signal?: AbortSignal }): Promise<BlePeripheral> {
        return call<BlePeripheral>(this.transport, "POST", `ble/peripherals/${segment(uuid)}/connection`, { json: request, signal: options?.signal });
    }

    /** Disconnects, ending its notifications. */
    disconnect(uuid: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `ble/peripherals/${segment(uuid)}/connection`, { signal: options?.signal });
    }

    /** The connected peripheral's signal strength. */
    readRssi(uuid: string, options?: { signal?: AbortSignal }): Promise<BleRssi> {
        return call<BleRssi>(this.transport, "GET", `ble/peripherals/${segment(uuid)}/rssi`, { signal: options?.signal });
    }

    /** The connected peripheral's services. */
    getServices(uuid: string, options?: { signal?: AbortSignal }): Promise<BleService[]> {
        return call<BleService[]>(this.transport, "GET", `ble/peripherals/${segment(uuid)}/services`, { signal: options?.signal });
    }

    /** A service's characteristics. */
    getCharacteristics(uuid: string, service: string, options?: { signal?: AbortSignal }): Promise<BleCharacteristic[]> {
        return call<BleCharacteristic[]>(this.transport, "GET", `ble/peripherals/${segment(uuid)}/services/${segment(service)}/characteristics`, { signal: options?.signal });
    }

    /** Reads a characteristic. */
    read(uuid: string, service: string, characteristic: string, options?: { signal?: AbortSignal }): Promise<BleCharacteristicValue> {
        return call<BleCharacteristicValue>(this.transport, "GET", `ble/peripherals/${segment(uuid)}/services/${segment(service)}/characteristics/${segment(characteristic)}`, { signal: options?.signal });
    }

    /** Writes a characteristic. */
    write(uuid: string, service: string, characteristic: string, request: BleWriteRequest, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "PUT", `ble/peripherals/${segment(uuid)}/services/${segment(service)}/characteristics/${segment(characteristic)}`, { json: request, signal: options?.signal });
    }

    /** Subscribes to a characteristic; values arrive through `onNotification`. */
    startNotifications(uuid: string, service: string, characteristic: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `ble/peripherals/${segment(uuid)}/services/${segment(service)}/characteristics/${segment(characteristic)}/notifications`, { signal: options?.signal });
    }

    /** Unsubscribes from a characteristic. */
    stopNotifications(uuid: string, service: string, characteristic: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `ble/peripherals/${segment(uuid)}/services/${segment(service)}/characteristics/${segment(characteristic)}/notifications`, { signal: options?.signal });
    }

    /** A peripheral seen by the running scan. Raised for every advertisement. */
    onScanResult(handler: (payload: BleScanResult) => void): () => void {
        return this.transport.subscribe("ble.scan", json => handler(JSON.parse(json) as BleScanResult));
    }

    /** A peripheral this page connected to changed connection state. */
    onStatus(handler: (payload: BlePeripheralStatus) => void): () => void {
        return this.transport.subscribe("ble.status", json => handler(JSON.parse(json) as BlePeripheralStatus));
    }

    /** A subscribed characteristic changed. */
    onNotification(handler: (payload: BleNotification) => void): () => void {
        return this.transport.subscribe("ble.notification", json => handler(JSON.parse(json) as BleNotification));
    }

    /** A scan or a notification subscription failed and has ended. */
    onError(handler: (payload: BleError) => void): () => void {
        return this.transport.subscribe("ble.error", json => handler(JSON.parse(json) as BleError));
    }
}
