// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Calendar.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid, dateText, query, segment } from "./core.js";
import type { AccessState } from "./shared.js";

export type AttendeeRole = "Required" | "Optional" | "Resource" | "Unknown";

export type AttendeeStatus = "Unknown" | "Pending" | "Accepted" | "Declined" | "Tentative";

export interface CalendarAccessRequest {
    access?: CalendarAccessType;
}

export interface CalendarAccessResult {
    access: AccessState;
}

/** The access to ask for. Write-only is iOS 17 and later; elsewhere it is treated as read-write. */
export type CalendarAccessType = "ReadOnly" | "WriteOnly" | "ReadWrite";

export interface CalendarAttendee {
    name: string | null;
    email: string | null;
    role: AttendeeRole;
    status: AttendeeStatus;
    isOrganizer: boolean;
}

/** An event as the device holds it. Attendees, the organizer and recurrence can be read but not written. */
export interface CalendarEvent {
    id: string | null;
    calendarId: string | null;
    title: string;
    description: string | null;
    location: string | null;
    start: string;
    end: string;
    isAllDay: boolean;
    availability: EventAvailability;
    url: string | null;
    isRecurring: boolean;
    recurrenceRule: string | null;
    reminderMinutes: number[];
    attendees: CalendarAttendee[];
    organizer: CalendarAttendee | null;
}

/** Changes to an event. Anything left null stays as it is; an empty `reminderMinutes` clears them, and an empty `url` removes it. */
export interface CalendarEventChanges {
    title?: string | null;
    start?: Date | string | null;
    end?: Date | string | null;
    description?: string | null;
    location?: string | null;
    isAllDay?: boolean | null;
    availability?: EventAvailability | null;
    url?: string | null;
    reminderMinutes?: number[] | null;
}

export interface CalendarEventPage {
    items: CalendarEvent[];
    offset: number;
    limit: number;
    hasMore: boolean;
}

export interface CalendarInfo {
    id: string | null;
    name: string;
    color: string | null;
    isReadOnly: boolean;
    account: string | null;
}

export interface CalendarList {
    calendars: CalendarInfo[];
}

export type EventAvailability = "Busy" | "Free" | "Tentative" | "Unavailable";

/** An event to create. `title`, `start` and `end` are required. */
export interface NewCalendarEvent {
    /** At most 1,000 characters. */
    title: string;
    start: Date | string;
    /** Not before `start`. */
    end: Date | string;
    /** The calendar to create it in; the device's default calendar when null. */
    calendarId?: string | null;
    /** At most 10,000 characters. */
    description?: string | null;
    location?: string | null;
    isAllDay?: boolean;
    availability?: EventAvailability;
    /** An absolute http or https URL. */
    url?: string | null;
    /** Whole minutes before the start; at most 10, each up to four weeks. */
    reminderMinutes?: number[] | null;
}

/** The device's calendars, from the page. Android, iOS, Mac Catalyst, macOS and Windows; Linux answers `isNotSupported`. Every call but `getAccess` and `requestAccess` fails with `access_denied` until access has been granted. */
export class CalendarBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** Where calendar access stands, without asking. */
    getAccess(options?: { signal?: AbortSignal }): Promise<CalendarAccessResult> {
        return call<CalendarAccessResult>(this.transport, "GET", `calendar`, { signal: options?.signal });
    }

    /** Asks for access, prompting if the OS has not asked before. */
    requestAccess(request: CalendarAccessRequest, options?: { signal?: AbortSignal }): Promise<CalendarAccessResult> {
        return call<CalendarAccessResult>(this.transport, "POST", `calendar/access`, { json: request, signal: options?.signal });
    }

    getCalendars(options?: { signal?: AbortSignal }): Promise<CalendarList> {
        return call<CalendarList>(this.transport, "GET", `calendar/calendars`, { signal: options?.signal });
    }

    /** Events overlapping a range of at most 366 days, a page at a time, in start order. */
    getEvents(start: Date | string, end: Date | string, options?: { calendarId?: string | null; search?: string | null; offset?: number; limit?: number; signal?: AbortSignal }): Promise<CalendarEventPage> {
        return call<CalendarEventPage>(this.transport, "GET", `calendar/events` + query({ start: dateText(start), end: dateText(end), calendarId: options?.calendarId, search: options?.search, offset: options?.offset, limit: options?.limit }), { signal: options?.signal });
    }

    /** Creates an event. A read-only calendar fails with `read_only`. */
    createEvent(calendarEvent: NewCalendarEvent, options?: { signal?: AbortSignal }): Promise<CalendarEvent> {
        return call<CalendarEvent>(this.transport, "POST", `calendar/events`, { json: calendarEvent, signal: options?.signal });
    }

    getEvent(id: string, options?: { signal?: AbortSignal }): Promise<CalendarEvent> {
        return call<CalendarEvent>(this.transport, "GET", `calendar/events/${segment(id)}`, { signal: options?.signal });
    }

    /** Changes only what `changes` sets. An event cannot move between calendars. */
    updateEvent(id: string, changes: CalendarEventChanges, options?: { signal?: AbortSignal }): Promise<CalendarEvent> {
        return call<CalendarEvent>(this.transport, "PUT", `calendar/events/${segment(id)}`, { json: changes, signal: options?.signal });
    }

    /** Deletes an event — or, with `series`, the rest of the recurring series it belongs to. */
    deleteEvent(id: string, options?: { series?: boolean; signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `calendar/events/${segment(id)}` + query({ series: options?.series }), { signal: options?.signal });
    }
}
