// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Camera.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid } from "./core.js";
import type { AccessState, BridgeFile } from "./shared.js";

export interface CameraAccessResult {
    /** Where the camera permission stands after asking. */
    access: AccessState;
}

/** A capture, filed into a file root and read through the files bridge. */
export interface CameraCapture {
    /** Where it was filed. */
    file: BridgeFile;
    /** A photo or a video. */
    kind: CameraCaptureKind;
    /** Bytes. */
    size: number;
    /** A photo's width in pixels. */
    width: number | null;
    /** A photo's height in pixels. */
    height: number | null;
    /** A video's length, where the platform reports one. */
    durationSeconds: number | null;
}

export type CameraCaptureKind = "Photo" | "Video";

/** One camera the device can open. */
export interface CameraDevice {
    /** What `cameraId` takes. */
    id: string;
    /** The name the platform gives it — "FaceTime HD Camera", "Back Camera". */
    name: string;
    /** Which way it points. */
    facing: CameraFacing;
    /** Whether the platform would choose it when nothing is pinned. */
    isDefault: boolean;
}

/** Which way a camera points. Most desktop cameras are `External`, which is neither front nor back. */
export type CameraFacing = "Back" | "Front" | "External";

/** The camera's built-in effects, applied to the preview, the viewfinder stream and the captures alike. */
export type CameraFilter = "None" | "Mono" | "Noir" | "Sepia" | "Invert" | "Vivid" | "Cool" | "Warm" | "Fade" | "Chrome" | "Instant" | "Tonal";

/** A change to the live camera. Every member is optional and null leaves it alone — a patch, so two viewers of the same camera do not undo each other's changes. */
export interface CameraSettingsInput {
    /** Switch between photos and video. Refused while recording. */
    videoMode?: boolean | null;
    /** Choose a camera by which way it points. Refused while recording. */
    facing?: CameraFacing | null;
    /** Pin a camera by id, which wins over `facing`; empty unpins it. Refused while recording. */
    cameraId?: string | null;
    /** Turn the camera on or off without closing its screen. Refused while recording. */
    active?: boolean | null;
    /** The effect to apply. */
    filter?: CameraFilter | null;
    /** Light the torch, where there is one. */
    torchOn?: boolean | null;
    /** The zoom factor, clamped to the camera's range. */
    zoom?: number | null;
}

/** The camera as it is right now. Everything about the camera itself is meaningless while `live` is false: no camera screen is open on the device, and every command answers 409. */
export interface CameraStatus {
    /** Whether this platform has a camera to bridge. False on Linux. */
    supported: boolean;
    /** The camera permission, without prompting. */
    access: AccessState;
    /** Whether a camera screen is open on the device, so there is something to drive. */
    live: boolean;
    /** Whether that screen has the camera turned on. A live camera can be put down without closing it. */
    active: boolean;
    /** Video rather than photos. The two are modes, never both at once. */
    videoMode: boolean;
    /** Whether a video is being recorded. */
    recording: boolean;
    /** Whether a capture is in progress. */
    busy: boolean;
    /** Which way the camera in use points. */
    facing: CameraFacing;
    /** The camera pinned by id, or null when the device chose by `facing`. */
    cameraId: string | null;
    /** The cameras this device offers. */
    cameras: CameraDevice[] | null;
    /** Whether this device picks a camera from `cameras` rather than flipping between front and back — true on desktops, whose cameras are neither. */
    choosesCamera: boolean;
    /** Whether the torch is lit. */
    torchOn: boolean;
    /** Whether there is a torch to light. False on front cameras and desktops. */
    torchAvailable: boolean;
    /** The zoom factor, between `minZoom` and `maxZoom`. */
    zoom: number;
    /** The least the camera in use zooms. */
    minZoom: number;
    /** The most the camera in use zooms. */
    maxZoom: number;
    /** The effect in use. */
    filter: CameraFilter;
    /** The most recent capture this camera filed. */
    lastCapture: CameraCapture | null;
    /** A sentence for people: what the camera is doing, or why it is not. */
    message: string | null;
}

/**
 * The device's own camera, driven from wherever the page is — a laptop across the room from a phone on a mount. Not the camera of the machine showing the page: that is `getUserMedia`.
 *
 * The camera runs on a camera screen on the device, and only while one is open: iOS will not run a camera in the background at all. `open` asks the device to show one; until it does, `live` is false and commands fail with 409 (`camera_not_open`), which a page should show as an instruction rather than an error. A command the camera cannot take in its current state — stop a recording that is not running, change lens while recording — fails with 422 (`camera_state`). Linux has no camera: 501.
 *
 * The viewfinder is `GET {bridge}/camera/preview` — a `multipart/x-mixed-replace` MJPEG stream an `<img>` plays directly. The device only encodes frames while someone is watching. Add a changing query parameter each time it is shown, or a browser may reuse the previous, never-ending response.
 */
export class CameraBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** The camera's state, and whether this platform has one and the app may use it — without prompting. */
    getStatus(options?: { signal?: AbortSignal }): Promise<CameraStatus> {
        return call<CameraStatus>(this.transport, "GET", `camera`, { signal: options?.signal });
    }

    /** Prompts for camera access where the platform still will, and says where it stands. */
    requestAccess(options?: { signal?: AbortSignal }): Promise<CameraAccessResult> {
        return call<CameraAccessResult>(this.transport, "POST", `camera/access`, { signal: options?.signal });
    }

    /** Asks the device to show its camera screen. Answers straight away; the camera arrives on `onStatus` when it is up. Does nothing when one is already open. */
    open(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `camera/open`, { signal: options?.signal });
    }

    /** Closes the camera screen the bridge opened. A camera screen the app opened itself is the app's to close. */
    close(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `camera/close`, { signal: options?.signal });
    }

    /** Takes a photo at full resolution and files it. */
    takePhoto(options?: { signal?: AbortSignal }): Promise<CameraCapture> {
        return call<CameraCapture>(this.transport, "POST", `camera/photo`, { signal: options?.signal });
    }

    /** Starts recording video. The camera has to be in video mode. */
    startRecording(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `camera/recording`, { signal: options?.signal });
    }

    /** Stops recording and files the video. */
    stopRecording(options?: { signal?: AbortSignal }): Promise<CameraCapture> {
        return call<CameraCapture>(this.transport, "DELETE", `camera/recording`, { signal: options?.signal });
    }

    /** Changes the live camera, and answers with the state it is in afterwards. */
    updateSettings(settings: CameraSettingsInput, options?: { signal?: AbortSignal }): Promise<CameraStatus> {
        return call<CameraStatus>(this.transport, "PUT", `camera/settings`, { json: settings, signal: options?.signal });
    }

    /** The camera changed — opened, closed, switched mode, filed a capture. Raised with the whole state. */
    onStatus(handler: (payload: CameraStatus) => void): () => void {
        return this.transport.subscribe("camera.status", json => handler(JSON.parse(json) as CameraStatus));
    }
}
