// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Contacts.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callBlob, callVoid, query, segment } from "./core.js";
import type { AccessState } from "./shared.js";

export type AddressType = "Home" | "Work" | "Other" | "Custom";

/** A contact. Photos are not included; `getPhoto` fetches them. */
export interface Contact {
    id: string | null;
    displayName: string;
    namePrefix: string | null;
    givenName: string | null;
    middleName: string | null;
    familyName: string | null;
    nameSuffix: string | null;
    nickname: string | null;
    note: string | null;
    organization: ContactOrganization | null;
    phones: ContactPhone[];
    emails: ContactEmail[];
    addresses: ContactAddress[];
    dates: ContactDate[];
    relationships: ContactRelationship[];
    websites: ContactWebsite[];
    /** Whether `getPhoto` has anything to return. */
    hasPhoto: boolean;
}

export interface ContactAddress {
    street: string | null;
    city: string | null;
    state: string | null;
    postalCode: string | null;
    country: string | null;
    type: AddressType;
    /** The label shown on the device, for a `Custom` type. */
    label: string | null;
}

export interface ContactCreated {
    id: string;
}

export interface ContactDate {
    date: string;
    type: ContactDateType;
    /** The label shown on the device, for a `Custom` type. */
    label: string | null;
}

export type ContactDateType = "Birthday" | "Anniversary" | "Other" | "Custom";

export interface ContactEmail {
    address: string;
    type: EmailType;
    /** The label shown on the device, for a `Custom` type. */
    label: string | null;
}

/** A contact to create, or the changes to one. A property left null is left as it is; an empty list clears. Names and organization fields are at most 1,000 characters, the note 10,000, and each list 50 entries. */
export interface ContactInput {
    namePrefix?: string | null;
    givenName?: string | null;
    middleName?: string | null;
    familyName?: string | null;
    nameSuffix?: string | null;
    nickname?: string | null;
    note?: string | null;
    organization?: ContactOrganization | null;
    phones?: ContactPhone[] | null;
    emails?: ContactEmail[] | null;
    addresses?: ContactAddress[] | null;
    dates?: ContactDate[] | null;
    relationships?: ContactRelationship[] | null;
    websites?: ContactWebsite[] | null;
}

export interface ContactOrganization {
    company: string | null;
    title: string | null;
    department: string | null;
}

/** A page of contacts. */
export interface ContactPage {
    items: Contact[];
    offset: number;
    limit: number;
    /** Whether another page follows. */
    hasMore: boolean;
}

export interface ContactPhone {
    number: string;
    type: PhoneType;
    /** The label shown on the device, for a `Custom` type. */
    label: string | null;
}

/** Which photo to fetch. Each falls back to the other when the contact only has one. */
export type ContactPhotoSize = "Full" | "Thumbnail";

export interface ContactRelationship {
    /** The related person's name. */
    name: string;
    type: RelationshipType;
    /** The label shown on the device, for a `Custom` type. */
    label: string | null;
}

export interface ContactWebsite {
    url: string;
    label: string | null;
}

export interface ContactsAccessResult {
    access: AccessState;
}

export type EmailType = "Home" | "Work" | "Other" | "Custom";

export type PhoneType = "Home" | "Mobile" | "Work" | "FaxWork" | "FaxHome" | "Pager" | "Other" | "Custom";

export type RelationshipType = "Father" | "Mother" | "Parent" | "Brother" | "Sister" | "Child" | "Friend" | "Spouse" | "Partner" | "Assistant" | "Manager" | "Other" | "Custom";

/** The device's address book: search and page through contacts, read one, create, update and delete, and fetch photos. Android and iOS; elsewhere every call fails with 501. Without access, calls fail with 403. */
export class ContactsBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** Whether the app has contacts access, without prompting. */
    getAccess(options?: { signal?: AbortSignal }): Promise<ContactsAccessResult> {
        return call<ContactsAccessResult>(this.transport, "GET", `contacts`, { signal: options?.signal });
    }

    /** Prompts for contacts access if it has not been decided. */
    requestAccess(options?: { signal?: AbortSignal }): Promise<ContactsAccessResult> {
        return call<ContactsAccessResult>(this.transport, "POST", `contacts/access`, { signal: options?.signal });
    }

    /** A page of contacts ordered by family then given name, optionally matching a name, phone or email. */
    getContacts(options?: { search?: string | null; offset?: number; limit?: number; signal?: AbortSignal }): Promise<ContactPage> {
        return call<ContactPage>(this.transport, "GET", `contacts/items` + query({ search: options?.search, offset: options?.offset, limit: options?.limit }), { signal: options?.signal });
    }

    /** Creates a contact. It needs a given name, family name or company. */
    createContact(contact: ContactInput, options?: { signal?: AbortSignal }): Promise<ContactCreated> {
        return call<ContactCreated>(this.transport, "POST", `contacts/items`, { json: contact, signal: options?.signal });
    }

    /** One contact. Fails with 404 when there is no such contact. */
    getContact(id: string, options?: { signal?: AbortSignal }): Promise<Contact> {
        return call<Contact>(this.transport, "GET", `contacts/items/${segment(id)}`, { signal: options?.signal });
    }

    /** Changes the properties set in `changes` and leaves the rest as they are. */
    updateContact(id: string, changes: ContactInput, options?: { signal?: AbortSignal }): Promise<Contact> {
        return call<Contact>(this.transport, "PUT", `contacts/items/${segment(id)}`, { json: changes, signal: options?.signal });
    }

    /** Deletes a contact. */
    deleteContact(id: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `contacts/items/${segment(id)}`, { signal: options?.signal });
    }

    /** The contact's photo as encoded image bytes. Fails with 404 when it has none. */
    getPhoto(id: string, options?: { size?: ContactPhotoSize; signal?: AbortSignal }): Promise<Blob> {
        return callBlob(this.transport, "GET", `contacts/items/${segment(id)}/photo` + query({ size: options?.size }), { signal: options?.signal });
    }
}
