// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Database.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid, query, segment } from "./core.js";

/** Stops a query started with that run id, if it is still running. */
export interface CancelDatabaseQuery {
    runId: string;
}

/** Drops or renames a table, view, index or trigger — or, with `preview`, only says what it would run. */
export interface ChangeDatabaseObject {
    action: DatabaseObjectAction;
    /** `table`, `view`, `index` or `trigger`. */
    kind: string;
    name: string;
    newName?: string | null;
    /** The table an index or trigger belongs to, where the engine's rename needs it. */
    table?: string | null;
    preview?: boolean;
    schema?: string | null;
    root?: string | null;
    path?: string | null;
    connection?: string | null;
    database?: string | null;
}

export interface ClearDatabaseHistory {
    root?: string | null;
    path?: string | null;
    connection?: string | null;
    database?: string | null;
}

/** How many rows a table has under the same filters and search as a page — exact, and asked separately so the first page never waits on it. */
export interface CountDatabaseTableRows {
    table: string;
    filters?: DatabaseRowFilter[] | null;
    search?: string | null;
    schema?: string | null;
    root?: string | null;
    path?: string | null;
    connection?: string | null;
    database?: string | null;
}

/** Writes a new, empty SQLite database — with the header a file needs before other tools will admit it is a database — at a path in a file root. Refused when something is already there. */
export interface CreateDatabase {
    root: string;
    path: string;
}

export type DatabaseAggregate = "Count" | "Sum" | "Average" | "Min" | "Max";

export interface DatabaseCellEdit {
    column: string;
    /** Null is SQL NULL. */
    value: string | null;
}

export interface DatabaseCheck {
    name: string | null;
    expression: string;
}

export interface DatabaseCheckDesign {
    name: string | null;
    expression: string;
    original?: string | null;
}

export interface DatabaseColumn {
    name: string;
    type: string;
    notNull: boolean;
    primaryKey: boolean;
    /** The column's default as the engine wrote it down — an expression, not a value. */
    default: string | null;
    /** Whether the engine numbers it; a column like this is left out of a new record. */
    autoIncrement: boolean;
    kind: DatabaseValueKind;
}

export interface DatabaseColumnDesign {
    name: string;
    type: string;
    notNull: boolean;
    primaryKey: boolean;
    default?: string | null;
    autoIncrement?: boolean;
    /** A single-column UNIQUE constraint. */
    unique?: boolean;
    /** What the column is called in the table as it stands, or null for one being added. */
    original?: string | null;
}

/** A database server connection a driver serves, by the id requests name it with. */
export interface DatabaseConnection {
    id: string;
    name: string;
    engine: DatabaseEngineKind;
    /** The database it opens on when a request names none. */
    database: string | null;
}

export interface DatabaseDesignScript {
    /** The script, or empty when there is nothing to do. */
    sql: string;
    /** What a reader must know before running it — a rebuild, what cannot be kept. */
    notes: string[];
    /** Why no script could be written. */
    error: string | null;
}

/** What is on the other end of a request. SQLite ships with the bridge; the servers come from drivers an app registers. */
export type DatabaseEngineKind = "Sqlite" | "SqlServer" | "PostgreSql";

export interface DatabaseExportResult {
    /** Where it was written, in `targetRoot`. */
    path: string | null;
    rows: number;
    elapsedMs: number;
    error: string | null;
}

/** How a filter compares a column with its value. The comparisons read the value back through the column's own type; the text ones compare the column's text, case-insensitively. */
export type DatabaseFilterOperator = "Equal" | "NotEqual" | "Contains" | "NotContains" | "StartsWith" | "EndsWith" | "Greater" | "GreaterOrEqual" | "Less" | "LessOrEqual" | "IsNull" | "IsNotNull";

export interface DatabaseForeignKey {
    /** Null on SQLite, whose foreign keys have no names. */
    name: string | null;
    columns: string[];
    referencedSchema: string | null;
    referencedTable: string;
    /** Parallel to `columns`; empty for a SQLite key that means the other table's primary key. */
    referencedColumns: string[];
    onUpdate: string;
    onDelete: string;
}

export interface DatabaseForeignKeyDesign {
    name: string | null;
    columns: string[];
    referencedSchema: string | null;
    referencedTable: string;
    referencedColumns: string[];
    onDelete?: string;
    onUpdate?: string;
    /** The constraint's name as it stands — or, where keys have no names, any value for "was there". */
    original?: string | null;
}

export interface DatabaseHistoryEntry {
    id: string;
    sql: string;
    ranOn: string;
    elapsedMs: number;
    rowsAffected: number;
    resultSets: number;
    error: string | null;
}

export interface DatabaseImportColumn {
    /** The CSV column, from zero. */
    source: number;
    /** The table's column it goes into. */
    target: string;
    /** For a new table, the column's type. */
    type?: string | null;
}

export interface DatabaseImportPreview {
    delimiter: string;
    hasHeader: boolean;
    /** A name for each column — the header's, or `column1`… without one. */
    columns: string[];
    /** What every sampled value in each column could be read as. */
    kinds: DatabaseValueKind[];
    /** The engine's type for each, for a new table. */
    suggestedTypes: string[];
    sample: string[][];
    /** How many data rows the whole file has. */
    rows: number;
    error: string | null;
}

export interface DatabaseImportResult {
    rows: number;
    elapsedMs: number;
    error: string | null;
    /** The file's line the import stopped at, when it did. */
    failedAtLine: number | null;
}

export interface DatabaseIndex {
    name: string;
    /** In index order. An expression index says `(expression)` for that position. */
    columns: string[];
    unique: boolean;
    /** Made by the engine for a constraint rather than by CREATE INDEX; it cannot be dropped on its own. */
    automatic: boolean;
    /** It has a WHERE clause, so it covers only some of the rows. */
    partial: boolean;
}

export interface DatabaseIndexDesign {
    name: string;
    columns: string[];
    unique: boolean;
    /** The index's name as it stands, or null for one being added. */
    original?: string | null;
}

/** What a statement did, what the server printed, what failed. */
export interface DatabaseMessage {
    kind: DatabaseMessageKind;
    text: string;
    /** 1-based, in the text that was sent, where the engine said. */
    line: number | null;
    column: number | null;
    elapsedMs: number;
}

export type DatabaseMessageKind = "Info" | "Rows" | "Error" | "Notice";

export interface DatabaseNames {
    names: string[];
    /** Why the server could not be asked — it is off, the password is wrong. */
    error: string | null;
}

export type DatabaseObjectAction = "Drop" | "Rename";

export interface DatabaseObjectResult {
    sql: string;
    error: string | null;
}

/** A step of a query plan, as a tree. */
export interface DatabasePlanNode {
    /** What the step is: `SCAN orders`, `Hash Join`. */
    label: string;
    /** The numbers — estimated rows and cost — where the engine gave any. */
    detail: string | null;
    children: DatabasePlanNode[];
}

/** What one write did. Every value is the engine's text; null stays null. */
export interface DatabaseQueryResult {
    columns: string[];
    rows: string[][];
    rowsAffected: number;
    truncated: boolean;
    elapsedMs: number;
    error: string | null;
    /** The record's key after the write — the only way to name a record the engine numbered. Null when it could not be read back. */
    key: string[] | null;
}

export interface DatabaseResultSet {
    columns: string[];
    /** Parallel to `columns`: how each is shown. */
    kinds: DatabaseValueKind[];
    rows: string[][];
    truncated: boolean;
    /** Which statement of the script produced it, from zero. */
    statement: number;
    /** The engine's name for each column's type, where it gave one. */
    types: string[] | null;
}

export interface DatabaseRowCount {
    /** Null when it could not be counted. */
    count: number | null;
    elapsedMs: number;
    error: string | null;
}

export interface DatabaseRowFilter {
    column: string;
    operator: DatabaseFilterOperator;
    /** Ignored by `IsNull` and `IsNotNull`. */
    value?: string | null;
}

export interface DatabaseSchema {
    /** Tables first, then views, each alphabetically. The engine's internal ones are left out. */
    tables: DatabaseTable[];
    /** The file's size, for a SQLite file; null for a server. */
    fileSize: number | null;
    engine: DatabaseEngineKind;
    /** The engine's own version string. */
    serverVersion: string;
    /** Why the database could not be opened at all — a file that is not a database, a server that is off. */
    error: string | null;
    /** Where a table made without saying lands — `dbo`, `public`. Null on SQLite. */
    defaultSchema: string | null;
}

/** Everything a script produced: each result set, each statement's outcome, and how it ended. */
export interface DatabaseScriptResult {
    results: DatabaseResultSet[];
    messages: DatabaseMessage[];
    /** What every write in it changed, added up; -1 when nothing was a write. */
    rowsAffected: number;
    elapsedMs: number;
    error: string | null;
    /** Where the error was, counted in the text that was sent. */
    errorLine: number | null;
    errorColumn: number | null;
    /** For an Explain: the plan as a tree, or null where it could not be read as one. */
    plan: DatabasePlanNode[] | null;
    /** Stopped — by a cancel, or by the device's statement timeout. */
    cancelled: boolean;
    /** Whether the script made, dropped or altered something, so the page reads the schema again. */
    schemaChanged: boolean;
}

export interface DatabaseSort {
    column: string;
    descending?: boolean;
}

/** A table or a view. */
export interface DatabaseTable {
    name: string;
    /** `table` or `view`. */
    kind: string;
    columns: DatabaseColumn[];
    indexes: DatabaseIndex[];
    /** The columns whose values name one row, and so whether a row can be edited at all: empty means it cannot. SQLite's is `rowid`, which a view and a WITHOUT ROWID table do not have; a server's is the primary key. */
    keyColumns: string[];
    /** A server's namespace — `dbo`, `public`. Null on SQLite. */
    schema: string | null;
    foreignKeys: DatabaseForeignKey[] | null;
    checks: DatabaseCheck[] | null;
    /** The names of the triggers on it. */
    triggers: string[] | null;
}

/** A table as a designer wants it, compared by the device with the table as it is. */
export interface DatabaseTableDesign {
    name: string;
    schema: string | null;
    columns: DatabaseColumnDesign[];
    indexes: DatabaseIndexDesign[];
    foreignKeys: DatabaseForeignKeyDesign[];
    checks: DatabaseCheckDesign[];
    /** The table being changed, or null for a new one. */
    originalName?: string | null;
    originalSchema?: string | null;
}

export interface DatabaseTableRows {
    columns: string[];
    /** Parallel to `rows`: each row's key, carried back untouched to edit or delete it. Empty when rows cannot be named. */
    rowKeys: string[][];
    rows: string[][];
    /** True when there are rows after this page. */
    truncated: boolean;
    elapsedMs: number;
    error: string | null;
    /** The request's, said back so a late answer can be placed. */
    offset: number;
}

export interface DatabaseTotal {
    column: string;
    aggregate: DatabaseAggregate;
}

export interface DatabaseTotals {
    /** Parallel to the request's totals, each the engine's own text for it. */
    values: string[];
    elapsedMs: number;
    error: string | null;
}

export interface DatabaseValue {
    /** The bytes of a binary value. */
    base64: string | null;
    /** Any other value, as the engine's own text. */
    text: string | null;
    length: number;
    isNull: boolean;
    error: string | null;
}

/** What sort of value a column holds, decided on the device from the engine's own type names, so the page can pick an editor and an alignment without knowing that `bit`, `boolean` and SQLite's `BOOLEAN` are one idea. The value itself still travels as the engine's own text. */
export type DatabaseValueKind = "Text" | "LongText" | "Integer" | "Decimal" | "Boolean" | "Date" | "DateTime" | "DateTimeOffset" | "Time" | "Binary" | "Guid" | "Other";

/** Deletes records, each named by its key — all of them or, when one is refused, none. */
export interface DeleteDatabaseRows {
    table: string;
    keys: string[][];
    schema?: string | null;
    root?: string | null;
    path?: string | null;
    connection?: string | null;
    database?: string | null;
}

/** Writes a table — filtered and sorted as a datasheet shows it — or one statement's answer to a CSV file in a file root, streamed from the engine on the device. Exactly one of `table` and `sql`. The file is UTF-8 with a byte-order mark, so spreadsheets read it as UTF-8, and replaces anything already at the target. */
export interface ExportDatabaseCsv {
    targetRoot: string;
    targetPath: string;
    table?: string | null;
    sql?: string | null;
    filters?: DatabaseRowFilter[] | null;
    search?: string | null;
    sort?: DatabaseSort[] | null;
    schema?: string | null;
    root?: string | null;
    path?: string | null;
    connection?: string | null;
    database?: string | null;
}

/** The queries run against one database, newest first, as the device recorded them. */
export interface GetDatabaseHistory {
    take?: number;
    root?: string | null;
    path?: string | null;
    connection?: string | null;
    database?: string | null;
}

/** The databases on a connection's server that its login may open, for a picker. */
export interface GetDatabaseNames {
    connection: string;
}

/** The tables and views in a database, and the columns, indexes, keys, checks and triggers of each. No row counts: a count is a full scan on a table without a narrow index, so it is asked separately (`CountDatabaseTableRows`). */
export interface GetDatabaseSchema {
    root?: string | null;
    path?: string | null;
    connection?: string | null;
    database?: string | null;
}

/** One page of one table's rows, each with the key that names it. Paged, sorted and filtered on the device: every column a filter or sort names is checked against the table, and every value is a parameter. */
export interface GetDatabaseTableRows {
    table: string;
    /** The page size, 1–5,000. */
    maxRows?: number;
    /** Where the page starts, in the order the sort gives. The key always ends the order, so pages are stable. */
    offset?: number;
    sort?: DatabaseSort[] | null;
    /** Every one must hold. */
    filters?: DatabaseRowFilter[] | null;
    /** Text to look for anywhere in a row, case-insensitively. */
    search?: string | null;
    schema?: string | null;
    root?: string | null;
    path?: string | null;
    connection?: string | null;
    database?: string | null;
}

/** A totals row — one aggregate per column, over every row the filters let through, worked out by the engine. */
export interface GetDatabaseTotals {
    table: string;
    totals: DatabaseTotal[];
    filters?: DatabaseRowFilter[] | null;
    search?: string | null;
    schema?: string | null;
    root?: string | null;
    path?: string | null;
    connection?: string | null;
    database?: string | null;
}

/** One value in full — a BLOB the datasheet only describes as its length and first bytes. */
export interface GetDatabaseValue {
    table: string;
    key: string[];
    column: string;
    schema?: string | null;
    root?: string | null;
    path?: string | null;
    connection?: string | null;
    database?: string | null;
}

/** The named queries saved against one database. */
export interface GetSavedDatabaseQueries {
    root?: string | null;
    path?: string | null;
    connection?: string | null;
    database?: string | null;
}

/** Reads a CSV into a table — a new one made to the mapping, or one that exists — in one transaction: an import that stops part way leaves the table as it was, with the line that stopped it in the answer. */
export interface ImportDatabaseCsv {
    table: string;
    createTable: boolean;
    columns: DatabaseImportColumn[];
    delimiter: string;
    hasHeader: boolean;
    csvRoot?: string | null;
    csvPath?: string | null;
    csvText?: string | null;
    /** Whether an empty field is NULL rather than an empty string. */
    emptyIsNull?: boolean;
    schema?: string | null;
    root?: string | null;
    path?: string | null;
    connection?: string | null;
    database?: string | null;
}

/** Adds one record and answers with it as it stands afterwards — defaults, the number the engine gave it, whatever a trigger made of it. A column left out takes the table's default. The table and column names are checked against the schema and every value is a parameter. */
export interface InsertDatabaseRow {
    table: string;
    values: DatabaseCellEdit[];
    schema?: string | null;
    root?: string | null;
    path?: string | null;
    connection?: string | null;
    database?: string | null;
}

/** The DDL that would make a table what a design says, to be read before it is run. Applying it is running that text with `RunDatabaseQuery`, so what somebody approved is what runs. */
export interface PreviewDatabaseDesign {
    design: DatabaseTableDesign;
    root?: string | null;
    path?: string | null;
    connection?: string | null;
    database?: string | null;
}

/** A first look at a CSV: its delimiter, whether it has a header, what each column seems to be, and the engine's type for each. From a file in a file root (`csvRoot` and `csvPath`) or from text the page already has (`csvText`) — exactly one. */
export interface PreviewDatabaseImport {
    csvRoot?: string | null;
    csvPath?: string | null;
    csvText?: string | null;
    /** Null to detect it. `\t` for a tab. */
    delimiter?: string | null;
    /** Null to detect it. */
    hasHeader?: boolean | null;
    sampleRows?: number;
    root?: string | null;
    path?: string | null;
    connection?: string | null;
    database?: string | null;
}

/** Runs SQL — one statement or a script — and answers with every result set it produced and what each statement said. This can write: it is a database client. What it cannot do on SQLite is leave the file it was opened on — `ATTACH` and `load_extension` are refused by SQLite's authorizer before a statement can run. */
export interface RunDatabaseQuery {
    sql: string;
    /** The cap on each result set, 1–100,000. Each result says whether it bit. */
    maxRows?: number;
    /** Ask how each statement would be answered rather than answering it, as a plan tree. */
    explain?: boolean;
    /** The page's name for this run, so `CancelDatabaseQuery` can stop it. */
    runId?: string | null;
    /** Whether this run goes into the database's query history. */
    record?: boolean;
    root?: string | null;
    path?: string | null;
    connection?: string | null;
    database?: string | null;
}

/** Saves a query under a name. Saving under a name the database already has overwrites that one. */
export interface SaveDatabaseQuery {
    name: string;
    sql: string;
    /** Null for a new one; a saved one's id to overwrite or rename it. */
    id?: string | null;
    root?: string | null;
    path?: string | null;
    connection?: string | null;
    database?: string | null;
}

export interface SavedDatabaseQuery {
    id: string;
    name: string;
    sql: string;
    savedOn: string;
}

export interface SavedDatabaseQueryResult {
    query: SavedDatabaseQuery | null;
    /** Why it was not saved, in a sentence for the form. */
    refusal: string | null;
}

/** Changes some cells of one record, named by its key, and answers with the record as it now stands. */
export interface UpdateDatabaseRow {
    table: string;
    /** The row's key exactly as `rowKeys` gave it. */
    key: string[];
    changes: DatabaseCellEdit[];
    schema?: string | null;
    root?: string | null;
    path?: string | null;
    connection?: string | null;
    database?: string | null;
}

/**
 * A database client on the device: SQLite files in the app's file roots, opened where they lie so a 4GB file costs a page of rows rather than 4GB; and database servers a driver the app registered can reach, which a page cannot open a socket to. Every request names its database by `root` and `path`, or by `connection` and `database`.
 *
 * What the database decided — a syntax error, a constraint, a server that is off — is in the answer's `error`. A request that names no database, or one that is not there, fails with 400 or 404.
 */
export class DatabaseBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** The database server connections the app's drivers serve. Empty when it registered none. */
    getConnections(options?: { signal?: AbortSignal }): Promise<DatabaseConnection[]> {
        return call<DatabaseConnection[]>(this.transport, "GET", `database/connections`, { signal: options?.signal });
    }

    /** The databases on a connection's server that its login may open, or why the server could not be asked. */
    getDatabaseNames(request: GetDatabaseNames, options?: { signal?: AbortSignal }): Promise<DatabaseNames> {
        return call<DatabaseNames>(this.transport, "POST", `database/databases`, { json: request, signal: options?.signal });
    }

    /** Makes a new, empty SQLite database. 409 when something is already at the path. */
    create(request: CreateDatabase, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `database/create`, { json: request, signal: options?.signal });
    }

    /** The tables and views in a database, or why it could not be opened. */
    getSchema(request: GetDatabaseSchema, options?: { signal?: AbortSignal }): Promise<DatabaseSchema> {
        return call<DatabaseSchema>(this.transport, "POST", `database/schema`, { json: request, signal: options?.signal });
    }

    /** Runs SQL — every result set and every statement's outcome — or the error it failed with. */
    query(request: RunDatabaseQuery, options?: { signal?: AbortSignal }): Promise<DatabaseScriptResult> {
        return call<DatabaseScriptResult>(this.transport, "POST", `database/query`, { json: request, signal: options?.signal });
    }

    /** Stops a query started with that run id. Harmless when it has already finished. */
    cancel(request: CancelDatabaseQuery, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `database/query/cancel`, { json: request, signal: options?.signal });
    }

    /** One page of one table's rows, with the key that names each. */
    getRows(request: GetDatabaseTableRows, options?: { signal?: AbortSignal }): Promise<DatabaseTableRows> {
        return call<DatabaseTableRows>(this.transport, "POST", `database/rows`, { json: request, signal: options?.signal });
    }

    /** How many rows pass the filters and search. */
    count(request: CountDatabaseTableRows, options?: { signal?: AbortSignal }): Promise<DatabaseRowCount> {
        return call<DatabaseRowCount>(this.transport, "POST", `database/rows/count`, { json: request, signal: options?.signal });
    }

    /** An aggregate per column over every row that passes the filters and search. */
    getTotals(request: GetDatabaseTotals, options?: { signal?: AbortSignal }): Promise<DatabaseTotals> {
        return call<DatabaseTotals>(this.transport, "POST", `database/rows/totals`, { json: request, signal: options?.signal });
    }

    /** Adds one record, and answers with it as it now stands. */
    insertRow(request: InsertDatabaseRow, options?: { signal?: AbortSignal }): Promise<DatabaseQueryResult> {
        return call<DatabaseQueryResult>(this.transport, "POST", `database/rows/insert`, { json: request, signal: options?.signal });
    }

    /** Changes cells of one record, and answers with it as it now stands. */
    updateRow(request: UpdateDatabaseRow, options?: { signal?: AbortSignal }): Promise<DatabaseQueryResult> {
        return call<DatabaseQueryResult>(this.transport, "POST", `database/rows/update`, { json: request, signal: options?.signal });
    }

    /** Deletes records by key, all or none. */
    deleteRows(request: DeleteDatabaseRows, options?: { signal?: AbortSignal }): Promise<DatabaseQueryResult> {
        return call<DatabaseQueryResult>(this.transport, "POST", `database/rows/delete`, { json: request, signal: options?.signal });
    }

    /** One value in full — a BLOB as base64, up to 64MB. */
    getValue(request: GetDatabaseValue, options?: { signal?: AbortSignal }): Promise<DatabaseValue> {
        return call<DatabaseValue>(this.transport, "POST", `database/value`, { json: request, signal: options?.signal });
    }

    /** The DDL that would make a table what a design says. Nothing is run. */
    previewDesign(request: PreviewDatabaseDesign, options?: { signal?: AbortSignal }): Promise<DatabaseDesignScript> {
        return call<DatabaseDesignScript>(this.transport, "POST", `database/design/preview`, { json: request, signal: options?.signal });
    }

    /** Drops or renames one object — or with `preview`, says what that would run. */
    changeObject(request: ChangeDatabaseObject, options?: { signal?: AbortSignal }): Promise<DatabaseObjectResult> {
        return call<DatabaseObjectResult>(this.transport, "POST", `database/object`, { json: request, signal: options?.signal });
    }

    /** A first look at a CSV before importing it. */
    previewImport(request: PreviewDatabaseImport, options?: { signal?: AbortSignal }): Promise<DatabaseImportPreview> {
        return call<DatabaseImportPreview>(this.transport, "POST", `database/import/preview`, { json: request, signal: options?.signal });
    }

    /** Reads a CSV into a table in one transaction. */
    import(request: ImportDatabaseCsv, options?: { signal?: AbortSignal }): Promise<DatabaseImportResult> {
        return call<DatabaseImportResult>(this.transport, "POST", `database/import`, { json: request, signal: options?.signal });
    }

    /** Writes a table or a statement's answer to a CSV file in a file root. */
    export(request: ExportDatabaseCsv, options?: { signal?: AbortSignal }): Promise<DatabaseExportResult> {
        return call<DatabaseExportResult>(this.transport, "POST", `database/export`, { json: request, signal: options?.signal });
    }

    /** The queries run against a database, newest first. */
    getHistory(request: GetDatabaseHistory, options?: { signal?: AbortSignal }): Promise<DatabaseHistoryEntry[]> {
        return call<DatabaseHistoryEntry[]>(this.transport, "POST", `database/history`, { json: request, signal: options?.signal });
    }

    /** Forgets a database's query history. */
    clearHistory(request: ClearDatabaseHistory, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `database/history/clear`, { json: request, signal: options?.signal });
    }

    /** The queries saved against a database, by name. */
    getSavedQueries(request: GetSavedDatabaseQueries, options?: { signal?: AbortSignal }): Promise<SavedDatabaseQuery[]> {
        return call<SavedDatabaseQuery[]>(this.transport, "POST", `database/saved`, { json: request, signal: options?.signal });
    }

    /** Saves a query under a name, or overwrites one. */
    saveQuery(request: SaveDatabaseQuery, options?: { signal?: AbortSignal }): Promise<SavedDatabaseQueryResult> {
        return call<SavedDatabaseQueryResult>(this.transport, "POST", `database/saved/save`, { json: request, signal: options?.signal });
    }

    /** Forgets a saved query. */
    removeSavedQuery(id: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `database/saved/${segment(id)}`, { signal: options?.signal });
    }
}
