// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Desktop.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid, segment } from "./core.js";

export type QuickEntryGlowTrigger = "None" | "WhileOpen" | "WhileBusy";

/** Changes to how the window opens. Properties left null are left as they are. */
export interface QuickEntryOptionsInput {
    presentation?: QuickEntryPresentation | null;
    /** A global shortcut such as `Cmd+Opt+Space` or `Ctrl+Alt+Space`; an empty string removes it. */
    hotKey?: string | null;
    /** Device-independent pixels, 200 to 4000. */
    width?: number | null;
    /** The height with nothing below the entry row. */
    collapsedHeight?: number | null;
    /** The window grows to fit suggestions and a response, up to this. */
    maxHeight?: number | null;
    placement?: QuickEntryPlacement | null;
    /** For `TopCenter`: the top edge as a fraction of the screen, 0 to 1. */
    topMarginRatio?: number | null;
    /** For `BottomCenter`: the gap below as a fraction of the screen, 0 to 1. */
    bottomMarginRatio?: number | null;
    /** For `Manual`: screen coordinates from the top left. */
    x?: number | null;
    y?: number | null;
    /** Close when another application takes focus. */
    dismissOnFocusLost?: boolean | null;
    dismissOnEscape?: boolean | null;
    /** Take keyboard focus when opening. Off for a window that should not steal typing. */
    activateOnShow?: boolean | null;
    /** What lights the glow around the screen's edge. */
    glow?: QuickEntryGlowTrigger | null;
}

export type QuickEntryPlacement = "TopCenter" | "BottomCenter" | "Center" | "NearCursor" | "Manual";

export type QuickEntryPresentation = "Auto" | "InApp" | "Desktop";

/** The prompt in the window. */
export interface QuickEntryPrompt {
    /** What is typed in the entry right now. */
    text: string;
    placeholder: string;
    /** Shows `busyText` and an animated orb in place of the entry, while the page works. */
    isBusy: boolean;
    busyText: string;
    /** Text shown under the entry — the answer to what was submitted. */
    response: string | null;
    suggestions: QuickEntrySuggestion[];
    /** Shows a microphone button, which raises `quickentry.microphone`. */
    showMicrophone: boolean;
    showSubmitButton: boolean;
    /** Empty the entry once a prompt is submitted. */
    clearOnSubmit: boolean;
}

/** The entry's text when the user cancelled or pressed the microphone. */
export interface QuickEntryPromptEvent {
    text: string;
}

/** Changes to the prompt. Properties left null are left as they are; an empty `response` removes the response and an empty `suggestions` list removes the suggestions. Everything but `text` is kept across a window that rebuilds its content on every open. */
export interface QuickEntryPromptInput {
    text?: string | null;
    placeholder?: string | null;
    isBusy?: boolean | null;
    busyText?: string | null;
    response?: string | null;
    suggestions?: QuickEntrySuggestion[] | null;
    showMicrophone?: boolean | null;
    showSubmitButton?: boolean | null;
    clearOnSubmit?: boolean | null;
}

export interface QuickEntryPulse {
    /** How long the glow stays lit: 100 ms to 30 s. */
    durationMs: number;
}

/** What quick entry can do here and what it is doing. */
export interface QuickEntryStatus {
    /** False on Android and iOS, where every other call fails with 501. */
    supported: boolean;
    /** How the window will actually open, with `Auto` resolved. */
    presentation: QuickEntryPresentation;
    isOpen: boolean;
    glowSupported: boolean;
    glowVisible: boolean;
    /** The global shortcut that toggles the window, when one is set. */
    hotKey: string | null;
    /** False when the shortcut is set but another application already owns it. */
    hotKeyRegistered: boolean;
    /** False when the app replaced the prompt with content of its own, which the prompt calls cannot drive. */
    hasPrompt: boolean;
}

/** A prompt the user submitted. */
export interface QuickEntrySubmission {
    text: string;
    /** The suggestion chosen to submit it; null when it was typed. */
    suggestion: QuickEntrySuggestion | null;
}

/** A row under the entry. */
export interface QuickEntrySuggestion {
    /** What is written into the entry when it is chosen. */
    text: string;
    /** A second line. */
    description: string | null;
    /** A leading emoji or icon-font character. */
    glyph: string | null;
    /** Anything the page wants back when the suggestion is chosen. */
    value: string | null;
}

export interface TrayAnimation {
    /** 2–24 images. */
    frames?: TrayImage[] | null;
    /** Time per frame; at least 50 ms. */
    intervalMs?: number;
}

export interface TrayClick {
    /** The icon clicked. */
    id: string;
    button: TrayClickButton;
    /** Screen coordinates, where the platform reports them. */
    x: number;
    y: number;
}

export type TrayClickButton = "Primary" | "Secondary" | "Double";

export interface TrayIconInfo {
    id: string;
    tooltip: string | null;
    title: string | null;
    visible: boolean;
    templateImage: boolean;
    badge: string | null;
    hasIcon: boolean;
    animating: boolean;
    menu: TrayMenuItemInfo[];
}

/** An icon to create, or the changes to one. Properties left null are left as they are. */
export interface TrayIconInput {
    id?: string | null;
    tooltip?: string | null;
    title?: string | null;
    visible?: boolean | null;
    /** On macOS, let the menu bar tint the icon; use black with alpha. */
    templateImage?: boolean | null;
    /** A short count or label drawn over the icon. */
    badge?: string | null;
    icon?: TrayImage | null;
    menu?: TrayMenuInput | null;
}

/** An image: a file the page could already read through the files bridge (`root` and `path`), or base64 bytes it built itself (`data`, with or without a `data:` URI prefix). */
export interface TrayImage {
    root?: string | null;
    path?: string | null;
    data?: string | null;
}

/** A menu: at most 64 entries in all, nested at most 4 deep. */
export interface TrayMenuInput {
    items?: TrayMenuItemInput[] | null;
}

export interface TrayMenuItemInfo {
    id: string;
    type: TrayMenuItemType;
    label: string | null;
    enabled: boolean;
    visible: boolean;
    /** Null for anything but a check item. */
    checked: boolean | null;
    items: TrayMenuItemInfo[] | null;
}

/** One menu entry. */
export interface TrayMenuItemInput {
    /** What comes back on `tray.menu`; assigned when null. */
    id?: string | null;
    type?: TrayMenuItemType;
    label?: string | null;
    /** A shortcut such as `Ctrl+S`. */
    accelerator?: string | null;
    enabled?: boolean;
    visible?: boolean;
    checked?: boolean;
    icon?: TrayImage | null;
    /** A submenu's entries. */
    items?: TrayMenuItemInput[] | null;
}

export type TrayMenuItemType = "Item" | "Check" | "Separator" | "Submenu";

export interface TrayMenuSelection {
    /** The icon whose menu it was. */
    id: string;
    itemId: string;
    label: string | null;
    /** The new state of a check item; null for anything else. */
    checked: boolean | null;
}

export interface TrayNotification {
    title?: string | null;
    message?: string | null;
}

export interface TrayStatus {
    supported: boolean;
    maxIcons: number;
    icons: TrayIconInfo[];
}

/** Quick entry: a prompt window that opens over other applications — from a global hotkey, a tray click or the page — in the style of Spotlight or a desktop assistant. The page configures the prompt, hears what is submitted, and writes the response back, and it keeps working with the app's own window closed: submissions also go to background.js. Windows, macOS and Linux; Android and iOS fail with 501. */
export class QuickEntryBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** Whether quick entry works here, and what it is doing. */
    getStatus(options?: { signal?: AbortSignal }): Promise<QuickEntryStatus> {
        return call<QuickEntryStatus>(this.transport, "GET", `quickentry`, { signal: options?.signal });
    }

    /** Changes how the window opens. A hotkey another application owns is reported, not an error. */
    configure(options: QuickEntryOptionsInput, requestOptions?: { signal?: AbortSignal }): Promise<QuickEntryStatus> {
        return call<QuickEntryStatus>(this.transport, "PUT", `quickentry/options`, { json: options, signal: requestOptions?.signal });
    }

    /** Opens the window. */
    show(options?: { signal?: AbortSignal }): Promise<QuickEntryStatus> {
        return call<QuickEntryStatus>(this.transport, "POST", `quickentry/show`, { signal: options?.signal });
    }

    /** Closes the window. */
    hide(options?: { signal?: AbortSignal }): Promise<QuickEntryStatus> {
        return call<QuickEntryStatus>(this.transport, "POST", `quickentry/hide`, { signal: options?.signal });
    }

    /** Opens the window if it is closed, and closes it if it is open. */
    toggle(options?: { signal?: AbortSignal }): Promise<QuickEntryStatus> {
        return call<QuickEntryStatus>(this.transport, "POST", `quickentry/toggle`, { signal: options?.signal });
    }

    /** The prompt. Fails with 409 when the app replaced the prompt with content of its own. */
    getPrompt(options?: { signal?: AbortSignal }): Promise<QuickEntryPrompt> {
        return call<QuickEntryPrompt>(this.transport, "GET", `quickentry/prompt`, { signal: options?.signal });
    }

    /** Changes the prompt: its placeholder, suggestions, busy state and response. */
    setPrompt(prompt: QuickEntryPromptInput, options?: { signal?: AbortSignal }): Promise<QuickEntryPrompt> {
        return call<QuickEntryPrompt>(this.transport, "PUT", `quickentry/prompt`, { json: prompt, signal: options?.signal });
    }

    /** Clears the entry, the response and the busy state. */
    resetPrompt(options?: { signal?: AbortSignal }): Promise<QuickEntryPrompt> {
        return call<QuickEntryPrompt>(this.transport, "POST", `quickentry/prompt/reset`, { signal: options?.signal });
    }

    /** Lights the glow around the screen's edge until `hideGlow`. */
    showGlow(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `quickentry/glow/show`, { signal: options?.signal });
    }

    hideGlow(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `quickentry/glow/hide`, { signal: options?.signal });
    }

    /** Lights the glow for a while, answering once it has gone out. */
    pulseGlow(pulse: QuickEntryPulse, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `quickentry/glow/pulse`, { json: pulse, signal: options?.signal });
    }

    /** The user submitted a prompt. Also delivered to background.js when no page is listening. */
    onSubmitted(handler: (payload: QuickEntrySubmission) => void): Promise<() => void> {
        return this.transport.subscribe("quickentry.submitted", json => handler(JSON.parse(json) as QuickEntrySubmission));
    }

    /** The user chose a suggestion, just before it is submitted. */
    onSuggestion(handler: (payload: QuickEntrySubmission) => void): Promise<() => void> {
        return this.transport.subscribe("quickentry.suggestion", json => handler(JSON.parse(json) as QuickEntrySubmission));
    }

    /** The user pressed Escape in the prompt. */
    onCancelled(handler: (payload: QuickEntryPromptEvent) => void): Promise<() => void> {
        return this.transport.subscribe("quickentry.cancelled", json => handler(JSON.parse(json) as QuickEntryPromptEvent));
    }

    /** The user pressed the microphone button. */
    onMicrophone(handler: (payload: QuickEntryPromptEvent) => void): Promise<() => void> {
        return this.transport.subscribe("quickentry.microphone", json => handler(JSON.parse(json) as QuickEntryPromptEvent));
    }

    /** The window opened, however it was opened. */
    onOpened(handler: (payload: QuickEntryStatus) => void): Promise<() => void> {
        return this.transport.subscribe("quickentry.opened", json => handler(JSON.parse(json) as QuickEntryStatus));
    }

    /** The window closed, however it was dismissed. */
    onClosed(handler: (payload: QuickEntryStatus) => void): Promise<() => void> {
        return this.transport.subscribe("quickentry.closed", json => handler(JSON.parse(json) as QuickEntryStatus));
    }
}

/** System tray and menu bar icons on Windows, macOS and Linux: create and update them, give them menus, show notifications, animate them, and hear clicks and menu choices. Android and iOS fail with 501. Ids are 1–64 letters, digits, `.`, `_` or `-`. */
export class TrayBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** Whether tray icons are supported here, the limit, and the icons this page created. */
    getStatus(options?: { signal?: AbortSignal }): Promise<TrayStatus> {
        return call<TrayStatus>(this.transport, "GET", `tray`, { signal: options?.signal });
    }

    /** Creates an icon, assigning an id when `id` is null. Fails with 429 past the limit. */
    create(icon: TrayIconInput, options?: { signal?: AbortSignal }): Promise<TrayIconInfo> {
        return call<TrayIconInfo>(this.transport, "POST", `tray`, { json: icon, signal: options?.signal });
    }

    /** Removes every icon. */
    removeAll(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `tray`, { signal: options?.signal });
    }

    /** One icon. Fails with 404 when there is no such icon. */
    get(id: string, options?: { signal?: AbortSignal }): Promise<TrayIconInfo> {
        return call<TrayIconInfo>(this.transport, "GET", `tray/${segment(id)}`, { signal: options?.signal });
    }

    /** Creates the icon, or updates it: only properties that are set change, and an empty string clears `tooltip`, `title` or `badge`. PUT by a fixed id lets a reloaded page adopt its icon rather than add another. */
    put(id: string, icon: TrayIconInput, options?: { signal?: AbortSignal }): Promise<TrayIconInfo> {
        return call<TrayIconInfo>(this.transport, "PUT", `tray/${segment(id)}`, { json: icon, signal: options?.signal });
    }

    /** Removes an icon. */
    remove(id: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `tray/${segment(id)}`, { signal: options?.signal });
    }

    /** Replaces an icon's menu. */
    setMenu(id: string, menu: TrayMenuInput, options?: { signal?: AbortSignal }): Promise<TrayIconInfo> {
        return call<TrayIconInfo>(this.transport, "PUT", `tray/${segment(id)}/menu`, { json: menu, signal: options?.signal });
    }

    /** Removes an icon's menu. */
    clearMenu(id: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `tray/${segment(id)}/menu`, { signal: options?.signal });
    }

    /** Opens an icon's menu, as though it had been clicked. */
    showMenu(id: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `tray/${segment(id)}/menu/show`, { signal: options?.signal });
    }

    /** Shows a notification from the icon. */
    notify(id: string, notification: TrayNotification, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `tray/${segment(id)}/notification`, { json: notification, signal: options?.signal });
    }

    /** Cycles the icon through two or more frames. */
    startAnimation(id: string, animation: TrayAnimation, options?: { signal?: AbortSignal }): Promise<TrayIconInfo> {
        return call<TrayIconInfo>(this.transport, "PUT", `tray/${segment(id)}/animation`, { json: animation, signal: options?.signal });
    }

    /** Stops animating and restores the icon. */
    stopAnimation(id: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `tray/${segment(id)}/animation`, { signal: options?.signal });
    }

    /** An icon was clicked. Also delivered to background.js when no page is listening. */
    onClick(handler: (payload: TrayClick) => void): Promise<() => void> {
        return this.transport.subscribe("tray.click", json => handler(JSON.parse(json) as TrayClick));
    }

    /** A menu item was chosen. Also delivered to background.js when no page is listening. */
    onMenu(handler: (payload: TrayMenuSelection) => void): Promise<() => void> {
        return this.transport.subscribe("tray.menu", json => handler(JSON.parse(json) as TrayMenuSelection));
    }
}
