// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Discovery.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid, query, segment } from "./core.js";

export interface DiscoveryBrowse {
    id: string;
    protocol: DiscoveryProtocol;
    /** What is being browsed for: a service type, search target or type list. */
    target: string;
}

export interface DiscoveryError {
    browseId: string;
    protocol: DiscoveryProtocol;
    message: string;
}

export type DiscoveryProtocol = "Mdns" | "Ssdp" | "Wsd";

export interface DiscoveryPublication {
    id: string;
    protocol: DiscoveryProtocol;
    /** The name in use, which mDNS may have changed to settle a conflict on the network. */
    name: string;
}

/** Whether a browse result is new or went away. */
export type DiscoveryStatus = "Found" | "Lost";

export interface MdnsBrowseResult {
    browseId: string;
    status: DiscoveryStatus;
    service: MdnsService;
}

export interface MdnsPublishRequest {
    instanceName: string;
    serviceType: string;
    /** 1–65535. */
    port: number;
    domain?: string | null;
    txtRecords?: Record<string, string> | null;
}

export interface MdnsSearchRequest {
    /** Such as `_http._tcp`. */
    serviceType: string;
    /** `local.` when null. */
    domain?: string | null;
    /** Resolve host, port, addresses and TXT records for each service found. */
    resolveServices?: boolean;
    /** A search's window, 250–30,000 ms; 5 seconds when null. Ignored by a browse. */
    scanMs?: number | null;
}

export interface MdnsService {
    instanceName: string;
    serviceType: string;
    domain: string;
    fullName: string;
    hostName: string | null;
    port: number;
    addresses: string[];
    txtRecords: Record<string, string>;
    isResolved: boolean;
}

export interface SsdpBrowseResult {
    browseId: string;
    status: DiscoveryStatus;
    device: SsdpDevice;
}

export interface SsdpDevice {
    udn: string;
    location: string | null;
    server: string | null;
    notificationTypes: string[];
    sourceAddress: string | null;
    isRootDevice: boolean;
    deviceType: string | null;
    serviceTypes: string[];
    headers: Record<string, string>;
}

export interface SsdpPublishRequest {
    udn: string;
    /** The absolute URL of the device description XML. */
    location: string;
    deviceType?: string | null;
    serviceTypes?: string[] | null;
    isRootDevice?: boolean;
    maxAgeSeconds?: number | null;
    server?: string | null;
}

export interface SsdpSearchRequest {
    /** `ssdp:all` when null. */
    searchTarget?: string | null;
    /** A search's window, 250–30,000 ms; 5 seconds when null. Ignored by a browse. */
    scanMs?: number | null;
    /** How long devices may wait before answering, 1,000–5,000 ms. */
    maxWaitMs?: number | null;
}

/** A device's UPnP description, with its embedded devices. */
export interface UpnpDeviceDescription {
    udn: string | null;
    deviceType: string | null;
    friendlyName: string | null;
    manufacturer: string | null;
    manufacturerUrl: string | null;
    modelName: string | null;
    modelNumber: string | null;
    modelDescription: string | null;
    modelUrl: string | null;
    serialNumber: string | null;
    upc: string | null;
    presentationUrl: string | null;
    icons: UpnpIcon[];
    services: UpnpService[];
    devices: UpnpDeviceDescription[];
}

export interface UpnpIcon {
    mimeType: string | null;
    width: number;
    height: number;
    depth: number;
    url: string | null;
}

export interface UpnpService {
    serviceType: string | null;
    serviceId: string | null;
    scpdUrl: string | null;
    controlUrl: string | null;
    eventSubscriptionUrl: string | null;
}

export type WsDiscoveryProfile = "None" | "Ws2005" | "Ws2009" | "All";

export interface WsdBrowseResult {
    browseId: string;
    status: DiscoveryStatus;
    target: WsdTarget;
}

export interface WsdPublishRequest {
    endpointReference: string;
    types?: WsdQualifiedName[] | null;
    scopes?: string[] | null;
    /** Absolute URLs the target answers at. */
    addresses?: string[] | null;
    metadataVersion?: number;
    profiles?: WsDiscoveryProfile;
}

/** An XML qualified name, since WS-Discovery types are namespaced XML names. */
export interface WsdQualifiedName {
    name: string;
    namespace: string;
}

export interface WsdSearchRequest {
    types?: WsdQualifiedName[] | null;
    scopes?: string[] | null;
    scopeMatchBy?: string | null;
    profiles?: WsDiscoveryProfile;
    /** A search's window, 250–30,000 ms; 5 seconds when null. Ignored by a browse. */
    scanMs?: number | null;
}

export interface WsdTarget {
    endpointReference: string;
    types: WsdQualifiedName[];
    scopes: string[];
    addresses: string[];
    preferredAddress: string | null;
    metadataVersion: number;
    sourceAddress: string | null;
    profile: WsDiscoveryProfile;
    isOnvifCamera: boolean;
}

/** Local network discovery over mDNS/Bonjour, SSDP/UPnP and WS-Discovery: search for a window, browse with results as events, resolve one, and advertise this app. A protocol the app did not register fails with 501. A browse needs a listener for its protocol's results first — it fails with 409 without one — and stops once that has none left; publications keep advertising until removed or the app exits. */
export class DiscoveryBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** The mDNS services seen during the scan window, less any that went away. */
    searchMdns(request: MdnsSearchRequest, options?: { signal?: AbortSignal }): Promise<MdnsService[]> {
        return call<MdnsService[]>(this.transport, "POST", `discovery/mdns/search`, { json: request, signal: options?.signal });
    }

    /** Browses for mDNS services; results arrive through `onMdns`. */
    browseMdns(request: MdnsSearchRequest, options?: { signal?: AbortSignal }): Promise<DiscoveryBrowse> {
        return call<DiscoveryBrowse>(this.transport, "POST", `discovery/mdns/browse`, { json: request, signal: options?.signal });
    }

    /** Resolves one mDNS service. Fails with 404 when it does not answer. */
    resolveMdns(instanceName: string, serviceType: string, options?: { timeoutMs?: number | null; signal?: AbortSignal }): Promise<MdnsService> {
        return call<MdnsService>(this.transport, "GET", `discovery/mdns/resolve` + query({ instanceName: instanceName, serviceType: serviceType, timeoutMs: options?.timeoutMs }), { signal: options?.signal });
    }

    /** Advertises a service over mDNS. On iOS the type must be listed in `NSBonjourServices`. */
    publishMdns(request: MdnsPublishRequest, options?: { signal?: AbortSignal }): Promise<DiscoveryPublication> {
        return call<DiscoveryPublication>(this.transport, "POST", `discovery/mdns/publications`, { json: request, signal: options?.signal });
    }

    /** The UPnP devices seen during the scan window, less any that went away. */
    searchSsdp(request: SsdpSearchRequest, options?: { signal?: AbortSignal }): Promise<SsdpDevice[]> {
        return call<SsdpDevice[]>(this.transport, "POST", `discovery/ssdp/search`, { json: request, signal: options?.signal });
    }

    /** Browses for UPnP devices; results arrive through `onSsdp`. */
    browseSsdp(request: SsdpSearchRequest, options?: { signal?: AbortSignal }): Promise<DiscoveryBrowse> {
        return call<DiscoveryBrowse>(this.transport, "POST", `discovery/ssdp/browse`, { json: request, signal: options?.signal });
    }

    /** A device's UPnP description. The device must have been seen by a search or browse first; otherwise 404. */
    getSsdpDescription(udn: string, options?: { signal?: AbortSignal }): Promise<UpnpDeviceDescription> {
        return call<UpnpDeviceDescription>(this.transport, "GET", `discovery/ssdp/description` + query({ udn: udn }), { signal: options?.signal });
    }

    /** Advertises a device over SSDP. */
    publishSsdp(request: SsdpPublishRequest, options?: { signal?: AbortSignal }): Promise<DiscoveryPublication> {
        return call<DiscoveryPublication>(this.transport, "POST", `discovery/ssdp/publications`, { json: request, signal: options?.signal });
    }

    /** The WS-Discovery targets seen during the scan window, less any that went away. */
    searchWsd(request: WsdSearchRequest, options?: { signal?: AbortSignal }): Promise<WsdTarget[]> {
        return call<WsdTarget[]>(this.transport, "POST", `discovery/wsd/search`, { json: request, signal: options?.signal });
    }

    /** Browses for WS-Discovery targets; results arrive through `onWsd`. */
    browseWsd(request: WsdSearchRequest, options?: { signal?: AbortSignal }): Promise<DiscoveryBrowse> {
        return call<DiscoveryBrowse>(this.transport, "POST", `discovery/wsd/browse`, { json: request, signal: options?.signal });
    }

    /** Resolves one WS-Discovery target. Fails with 404 when it does not answer. */
    resolveWsd(endpointReference: string, options?: { timeoutMs?: number | null; signal?: AbortSignal }): Promise<WsdTarget> {
        return call<WsdTarget>(this.transport, "GET", `discovery/wsd/resolve` + query({ endpointReference: endpointReference, timeoutMs: options?.timeoutMs }), { signal: options?.signal });
    }

    /** Advertises a target over WS-Discovery. */
    publishWsd(request: WsdPublishRequest, options?: { signal?: AbortSignal }): Promise<DiscoveryPublication> {
        return call<DiscoveryPublication>(this.transport, "POST", `discovery/wsd/publications`, { json: request, signal: options?.signal });
    }

    /** The running browses. */
    getBrowses(options?: { signal?: AbortSignal }): Promise<DiscoveryBrowse[]> {
        return call<DiscoveryBrowse[]>(this.transport, "GET", `discovery/browses`, { signal: options?.signal });
    }

    /** Stops a browse. */
    stopBrowse(id: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `discovery/browses/${segment(id)}`, { signal: options?.signal });
    }

    /** The active publications. */
    getPublications(options?: { signal?: AbortSignal }): Promise<DiscoveryPublication[]> {
        return call<DiscoveryPublication[]>(this.transport, "GET", `discovery/publications`, { signal: options?.signal });
    }

    /** Stops advertising, sending a goodbye so it vanishes from other devices straight away. */
    unpublish(id: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `discovery/publications/${segment(id)}`, { signal: options?.signal });
    }

    /** An mDNS service was found or lost by a browse. */
    onMdns(handler: (payload: MdnsBrowseResult) => void): Promise<() => void> {
        return this.transport.subscribe("discovery.mdns", json => handler(JSON.parse(json) as MdnsBrowseResult));
    }

    /** A UPnP device was found or lost by a browse. */
    onSsdp(handler: (payload: SsdpBrowseResult) => void): Promise<() => void> {
        return this.transport.subscribe("discovery.ssdp", json => handler(JSON.parse(json) as SsdpBrowseResult));
    }

    /** A WS-Discovery target was found or lost by a browse. */
    onWsd(handler: (payload: WsdBrowseResult) => void): Promise<() => void> {
        return this.transport.subscribe("discovery.wsd", json => handler(JSON.parse(json) as WsdBrowseResult));
    }

    /** A browse failed; `onStopped` follows. */
    onError(handler: (payload: DiscoveryError) => void): Promise<() => void> {
        return this.transport.subscribe("discovery.error", json => handler(JSON.parse(json) as DiscoveryError));
    }

    /** A browse ended. */
    onStopped(handler: (payload: DiscoveryBrowse) => void): Promise<() => void> {
        return this.transport.subscribe("discovery.stopped", json => handler(JSON.parse(json) as DiscoveryBrowse));
    }
}
