// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.DocumentGeofencing.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid } from "./core.js";
import type { AccessState } from "./shared.js";

/** Where the device is now in one set. */
export interface DocumentCurrentRegion {
    /** The set that was queried. */
    regionSet: string;
    /** The region the device is in, or null when it is outside every region of the set. */
    regionId: string | null;
    /** Its display name, when the set was registered with one. */
    regionName: string | null;
    /** Distance to the region — 0 in a containment set. */
    distanceMeters: number;
    /** The region document as the store serializes it, as on `region`. */
    region: unknown | null;
}

export interface DocumentGeofenceAccessResult {
    access: AccessState;
}

export interface DocumentGeofenceStatus {
    /** Whether monitoring is running. It survives an app restart. */
    isStarted: boolean;
    /** The region sets the app registered, in registration order. */
    regionSets: DocumentRegionSetInfo[];
}

/** The device entered or left one region of one set. */
export interface DocumentRegionChange {
    /** The set the region belongs to. */
    regionSet: string;
    /** The region document's id. */
    regionId: string;
    /** Its display name, when the set was registered with one. */
    regionName: string | null;
    /** True for an entry, false for an exit. */
    entered: boolean;
    /** The GPS position that produced the change. */
    latitude: number;
    /** The GPS position that produced the change. */
    longitude: number;
    /** The region document as the store serializes it. Null when its type has no JSON metadata in the store's serializer options, or for an exit from a region since deleted. */
    region: unknown | null;
}

/** A layer of regions the app registered in C# — states, cities, delivery zones. */
export interface DocumentRegionSetInfo {
    /** The name every change in the set carries. */
    name: string;
    /** Set for a proximity set — inside means within this distance; null for containment. */
    withinMeters: number | null;
}

/** Document geofencing: GPS-driven monitoring of polygon and proximity regions stored in Shiny.DocumentDb, with no platform limit on how many. The app registers the region sets in C#; the page starts and stops monitoring, reads where the device is, and hears changes. Android, iOS and Mac Catalyst; elsewhere every call fails with 501. */
export class DocumentGeofencesBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** Whether monitoring is running, and the region sets the app registered. */
    getStatus(options?: { signal?: AbortSignal }): Promise<DocumentGeofenceStatus> {
        return call<DocumentGeofenceStatus>(this.transport, "GET", `documentgeofences/status`, { signal: options?.signal });
    }

    /** Requests the background location permission monitoring needs. */
    requestAccess(options?: { signal?: AbortSignal }): Promise<DocumentGeofenceAccessResult> {
        return call<DocumentGeofenceAccessResult>(this.transport, "POST", `documentgeofences/access`, { signal: options?.signal });
    }

    /** Starts monitoring; a no-op while it runs. Fails with 409 without permission and with 501 when the store's provider cannot run spatial queries. */
    start(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `documentgeofences/start`, { signal: options?.signal });
    }

    /** Stops monitoring and forgets which regions the device was in. */
    stop(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `documentgeofences/stop`, { signal: options?.signal });
    }

    /** The region the device is in for each set, from the last GPS reading, without raising changes. Empty when there is no reading. */
    getCurrent(options?: { signal?: AbortSignal }): Promise<DocumentCurrentRegion[]> {
        return call<DocumentCurrentRegion[]>(this.transport, "GET", `documentgeofences/current`, { signal: options?.signal });
    }

    /** The device entered or left a region, while the page is open. */
    onChange(handler: (payload: DocumentRegionChange) => void): Promise<() => void> {
        return this.transport.subscribe("documentgeofence.change", json => handler(JSON.parse(json) as DocumentRegionChange));
    }
}
