// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Folders.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid, segment } from "./core.js";

export interface FolderList {
    /** Whether this platform has a folder picker. */
    supported: boolean;
    folders: PickedFolder[];
}

export interface FolderPickRequest {
    /** The file root name to give the folder: 1–64 letters, digits, `-` or `_`. One is chosen when null. */
    root?: string | null;
    /** The picker's title, where the platform shows one. */
    title?: string | null;
}

export interface PickedFolder {
    /** The file root name the files bridge knows the folder by. */
    root: string;
    /** The folder's name as the user saw it in the picker. */
    displayName: string;
    /** False when the folder was moved, deleted or its access revoked since it was picked. */
    available: boolean;
}

/** Folders the user picks with the platform's own picker. A picked folder becomes a file root: the page reads and writes it through `IFilesBridge` under the root name it chose, and it is still there the next time the app runs, until the page forgets it. Where the platform has no folder picker, calls fail with 501. */
export class FoldersBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** Whether folders can be picked here, and the folders picked so far. */
    getFolders(options?: { signal?: AbortSignal }): Promise<FolderList> {
        return call<FolderList>(this.transport, "GET", `folders`, { signal: options?.signal });
    }

    /** Shows the folder picker. Null when the user cancels. Picking again under a root name already in use replaces that folder; the app's own roots (`data`, `cache`) cannot be replaced. */
    pick(request: FolderPickRequest, options?: { signal?: AbortSignal }): Promise<PickedFolder | null> {
        return call<PickedFolder | null>(this.transport, "POST", `folders/pick`, { json: request, signal: options?.signal });
    }

    /** Forgets a picked folder: its root goes away and the app gives up its access to it. */
    forget(root: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `folders/${segment(root)}`, { signal: options?.signal });
    }
}
