// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Geofencing.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid, segment } from "./core.js";
import type { AccessState } from "./shared.js";

export interface GeofenceAccessResult {
    access: AccessState;
}

/** A circular region. */
export interface GeofenceRegion {
    /** Names the region; monitoring one with an identifier already in use replaces it. */
    identifier: string;
    latitude: number;
    longitude: number;
    /** Must be positive. */
    radiusMeters: number;
    /** Stop monitoring after the first transition. */
    singleUse: boolean;
    notifyOnEntry: boolean;
    notifyOnExit: boolean;
}

export type GeofenceState = "Unknown" | "Entered" | "Exited";

export interface GeofenceStatus {
    identifier: string;
    state: GeofenceState;
}

/** Geofences: monitor circular regions and hear when the device enters or leaves one. Android, iOS, Mac Catalyst and Windows; elsewhere every call fails with 501. */
export class GeofencesBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** The permission state, without prompting. */
    getStatus(options?: { signal?: AbortSignal }): Promise<GeofenceAccessResult> {
        return call<GeofenceAccessResult>(this.transport, "GET", `geofences/status`, { signal: options?.signal });
    }

    /** Requests the background location permission geofencing needs. */
    requestAccess(options?: { signal?: AbortSignal }): Promise<GeofenceAccessResult> {
        return call<GeofenceAccessResult>(this.transport, "POST", `geofences/access`, { signal: options?.signal });
    }

    /** The regions being monitored. */
    getRegions(options?: { signal?: AbortSignal }): Promise<GeofenceRegion[]> {
        return call<GeofenceRegion[]>(this.transport, "GET", `geofences/regions`, { signal: options?.signal });
    }

    /** Starts monitoring a region. Fails with 409 without permission. */
    startMonitoring(region: GeofenceRegion, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `geofences/regions`, { json: region, signal: options?.signal });
    }

    /** Stops monitoring every region. */
    stopAllMonitoring(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `geofences/regions`, { signal: options?.signal });
    }

    /** Stops monitoring one region. */
    stopMonitoring(identifier: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `geofences/regions/${segment(identifier)}`, { signal: options?.signal });
    }

    /** Whether the device is inside a monitored region now. Fails with 404 for a region not monitored. */
    getState(identifier: string, options?: { signal?: AbortSignal }): Promise<GeofenceStatus> {
        return call<GeofenceStatus>(this.transport, "GET", `geofences/regions/${segment(identifier)}/state`, { signal: options?.signal });
    }

    /** The device entered or left a region, while the page is open. */
    onStatus(handler: (payload: GeofenceStatus) => void): Promise<() => void> {
        return this.transport.subscribe("geofence.status", json => handler(JSON.parse(json) as GeofenceStatus));
    }
}
