// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Health.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid, dateText, query, segment } from "./core.js";

export type CervicalMucusAppearance = "Unspecified" | "Dry" | "Sticky" | "Creamy" | "Watery" | "EggWhite";

export interface HealthAccessRequest {
    permissions: HealthPermission[];
}

export interface HealthAccessResult {
    type: HealthDataType;
    /** Whether the platform reported success. iOS never says whether read access was granted. */
    granted: boolean;
}

export interface HealthAccessResults {
    results: HealthAccessResult[];
}

export type HealthAccessType = "Read" | "Write" | "ReadWrite";

/** How a type is read: bucketed numbers, bucketed blood pressure pairs, or individual records. */
export type HealthDataKind = "Numeric" | "BloodPressure" | "Record";

export type HealthDataType = "StepCount" | "HeartRate" | "Calories" | "Distance" | "Weight" | "Height" | "BodyFatPercentage" | "RestingHeartRate" | "BloodPressure" | "OxygenSaturation" | "SleepDuration" | "Hydration" | "MenstruationFlow" | "BloodGlucose" | "BodyTemperature" | "BasalBodyTemperature" | "RespiratoryRate" | "Vo2Max" | "HeartRateVariability" | "LeanBodyMass" | "BasalEnergyBurned" | "ActiveEnergyBurned" | "FloorsClimbed" | "WheelchairPushes" | "Speed" | "Power" | "SexualActivity" | "OvulationTest" | "CervicalMucus" | "IntermenstrualBleeding" | "Workout" | "Nutrition";

/** The bucket size for numeric and blood pressure reads. */
export type HealthInterval = "Minutes" | "Hours" | "Days";

export interface HealthListener {
    type: HealthDataType;
}

export interface HealthListenerRequest {
    /** How often Android polls, 5–300 seconds. iOS is pushed and ignores it. */
    pollingIntervalSeconds?: number | null;
}

export interface HealthListenerStopped {
    type: HealthDataType;
    /** Why it ended, when it failed rather than being stopped. */
    error: string | null;
}

export interface HealthPermission {
    type: HealthDataType;
    access?: HealthAccessType;
}

export interface HealthReading {
    type: HealthDataType;
    sample: HealthSample;
}

/** One sample. Which fields are set depends on the type: `value` for numeric types, `systolic` and `diastolic` for blood pressure, and the fields named after each record type for the rest. */
export interface HealthSample {
    start: string;
    end: string;
    value: number | null;
    systolic: number | null;
    diastolic: number | null;
    flow: MenstrualFlow | null;
    isCycleStart: boolean | null;
    protection: SexualActivityProtection | null;
    outcome: OvulationTestOutcome | null;
    appearance: CervicalMucusAppearance | null;
    workout: WorkoutType | null;
    totalEnergyKilocalories: number | null;
    totalDistanceMeters: number | null;
    title: string | null;
    meal: MealType | null;
    name: string | null;
    energyKilocalories: number | null;
    proteinGrams: number | null;
    carbohydratesGrams: number | null;
    totalFatGrams: number | null;
    fiberGrams: number | null;
    sugarGrams: number | null;
    sodiumGrams: number | null;
    cholesterolGrams: number | null;
}

/** A sample to write. `end` defaults to `start`. Set the fields the type needs: `value` for numeric types, `systolic` and `diastolic` for blood pressure, `flow` for menstruation flow, `outcome` for an ovulation test, `workout` for a workout. Numbers must be finite and not negative; title and name at most 256 characters. */
export interface HealthSampleInput {
    start: Date | string;
    end?: Date | string | null;
    value?: number | null;
    systolic?: number | null;
    diastolic?: number | null;
    flow?: MenstrualFlow | null;
    isCycleStart?: boolean | null;
    protection?: SexualActivityProtection | null;
    outcome?: OvulationTestOutcome | null;
    appearance?: CervicalMucusAppearance | null;
    workout?: WorkoutType | null;
    totalEnergyKilocalories?: number | null;
    totalDistanceMeters?: number | null;
    title?: string | null;
    meal?: MealType | null;
    name?: string | null;
    energyKilocalories?: number | null;
    proteinGrams?: number | null;
    carbohydratesGrams?: number | null;
    totalFatGrams?: number | null;
    fiberGrams?: number | null;
    sugarGrams?: number | null;
    sodiumGrams?: number | null;
    cholesterolGrams?: number | null;
}

export interface HealthSamples {
    type: HealthDataType;
    /** What values are measured in; null for record types. */
    unit: string | null;
    samples: HealthSample[];
}

export interface HealthStatus {
    /** False where the store is missing — Health Connect not installed. */
    available: boolean;
    types: HealthTypeInfo[];
    /** The types being watched. */
    listeners: HealthListener[];
}

export interface HealthTypeInfo {
    type: HealthDataType;
    kind: HealthDataKind;
    /** What values are measured in — `count`, `bpm`, `kg`; null for record types. */
    unit: string | null;
    /** Whether reads are bucketed by interval. */
    bucketed: boolean;
}

export type MealType = "Unknown" | "Breakfast" | "Lunch" | "Dinner" | "Snack";

export type MenstrualFlow = "Unspecified" | "None" | "Light" | "Medium" | "Heavy";

export type OvulationTestOutcome = "Inconclusive" | "Positive" | "High" | "Negative";

export type SexualActivityProtection = "Unspecified" | "Protected" | "Unprotected";

export type WorkoutType = "Other" | "Running" | "Walking" | "Hiking" | "Cycling" | "Swimming" | "Rowing" | "Elliptical" | "StairClimbing" | "StrengthTraining" | "HighIntensityIntervalTraining" | "Yoga" | "Pilates" | "Tennis" | "Basketball" | "Soccer" | "Baseball" | "Golf" | "Boxing" | "MartialArts" | "Dancing";

/** HealthKit on iOS and Health Connect on Android: request access per type, read samples, write them, and watch a type for new readings. Elsewhere every call fails with 501; where the store is missing (Health Connect not installed), with 503; without access to a type, with 403. */
export class HealthBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** Whether the store is available, every type with its unit, and the types being watched. */
    getStatus(options?: { signal?: AbortSignal }): Promise<HealthStatus> {
        return call<HealthStatus>(this.transport, "GET", `health`, { signal: options?.signal });
    }

    /** Requests access to up to 64 types. The platform decides which prompts to show. */
    requestAccess(request: HealthAccessRequest, options?: { signal?: AbortSignal }): Promise<HealthAccessResults> {
        return call<HealthAccessResults>(this.transport, "POST", `health/access`, { json: request, signal: options?.signal });
    }

    /** Samples in a range of at most 366 days. Numeric types and blood pressure are bucketed by `interval`, at most 2,000 buckets; record types — cycle tracking, workouts, nutrition — are individual records and ignore it. */
    getSamples(type: HealthDataType, start: Date | string, end: Date | string, options?: { interval?: HealthInterval; signal?: AbortSignal }): Promise<HealthSamples> {
        return call<HealthSamples>(this.transport, "GET", `health/samples/${segment(type)}` + query({ start: dateText(start), end: dateText(end), interval: options?.interval }), { signal: options?.signal });
    }

    /** Writes one sample. Which fields it needs depends on the type; a missing one fails with 400. */
    writeSample(type: HealthDataType, sample: HealthSampleInput, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `health/samples/${segment(type)}`, { json: sample, signal: options?.signal });
    }

    /** Watches a type; readings arrive through `onReading`. At most 8 types at once. It stops when the page stops listening to events. */
    startListening(type: HealthDataType, request: HealthListenerRequest, options?: { signal?: AbortSignal }): Promise<HealthListener> {
        return call<HealthListener>(this.transport, "POST", `health/listeners/${segment(type)}`, { json: request, signal: options?.signal });
    }

    /** Stops watching a type. Fails with 404 when it is not being watched. */
    stopListening(type: HealthDataType, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `health/listeners/${segment(type)}`, { signal: options?.signal });
    }

    /** A new reading for a watched type. */
    onReading(handler: (payload: HealthReading) => void): () => void {
        return this.transport.subscribe("health.reading", json => handler(JSON.parse(json) as HealthReading));
    }

    /** Watching a type ended, because it was stopped or it failed. */
    onStopped(handler: (payload: HealthListenerStopped) => void): () => void {
        return this.transport.subscribe("health.stopped", json => handler(JSON.parse(json) as HealthListenerStopped));
    }
}
