// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.HttpTransfers.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid, segment } from "./core";

/** An extra form part sent with a multipart upload. */
export interface TransferBody {
    /** At most 1 MB. */
    content: string;
    /** `text/plain` when null. */
    contentType?: string | null;
    formDataName?: string | null;
}

/** A transfer. */
export interface TransferInfo {
    id: string;
    type: TransferType;
    url: string;
    /** The file root, while the file is inside one. */
    root: string | null;
    path: string | null;
    status: TransferState;
    bytesTransferred: number;
    bytesToTransfer: number | null;
    bytesPerSecond: number | null;
    /** 0–1, when the size is known. */
    percentComplete: number | null;
    createdAt: string | null;
    /** The server's status, for a failure that had one. */
    statusCode: number | null;
    /** Why it failed. */
    error: string | null;
}

export interface TransferList {
    transfers: TransferInfo[];
}

/** A transfer to queue. */
export interface TransferRequest {
    type: TransferType;
    /** An absolute http or https URL. Loopback is refused unless the app allows it. */
    url: string;
    /** The file root a download goes into or an upload comes from. */
    root: string;
    /** The file inside the root. */
    path: string;
    /** GET, POST, PUT or PATCH; the transfer type's default when null. */
    method?: string | null;
    /** At most 32. Hop-by-hop, content and proxy headers are refused. */
    headers?: Record<string, string> | null;
    /** Whether the transfer may run on a metered network. */
    useMeteredConnection?: boolean;
    /** The file's form field name for a multipart upload; `file` when null. */
    formDataName?: string | null;
    /** An extra form part, for a multipart upload only. */
    body?: TransferBody | null;
    /** Whether a download may replace an existing file. */
    overwrite?: boolean;
}

export type TransferState = "Unknown" | "Pending" | "Paused" | "PausedByNoNetwork" | "PausedByCostedNetwork" | "InProgress" | "Error" | "Canceled" | "Completed";

export type TransferType = "UploadMultipart" | "UploadRaw" | "Download";

/** Background HTTP transfers that keep going while the app is suspended: downloads into a file root and uploads from one. Only the web app's own transfers are listed or cancelled. A download lands at its path only once it completes. */
export class TransfersBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** The web app's transfers. */
    getTransfers(options?: { signal?: AbortSignal }): Promise<TransferList> {
        return call<TransferList>(this.transport, "GET", `transfers`, { signal: options?.signal });
    }

    /** Queues a transfer. Fails with 403 for a URL the app does not allow, 404 for an unknown root or a missing upload file, 409 when a download's destination exists and overwrite is off, 429 when too many are queued. */
    queue(request: TransferRequest, options?: { signal?: AbortSignal }): Promise<TransferInfo> {
        return call<TransferInfo>(this.transport, "POST", `transfers`, { json: request, signal: options?.signal });
    }

    /** Cancels every web app transfer, and none of the native app's. */
    cancelAll(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `transfers`, { signal: options?.signal });
    }

    /** One transfer. Fails with 404 when there is no such transfer. */
    getTransfer(id: string, options?: { signal?: AbortSignal }): Promise<TransferInfo> {
        return call<TransferInfo>(this.transport, "GET", `transfers/${segment(id)}`, { signal: options?.signal });
    }

    /** Cancels a transfer. */
    cancel(id: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `transfers/${segment(id)}`, { signal: options?.signal });
    }

    /** Pauses a transfer. */
    pause(id: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `transfers/${segment(id)}/pause`, { signal: options?.signal });
    }

    /** Resumes a paused transfer. */
    resume(id: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `transfers/${segment(id)}/resume`, { signal: options?.signal });
    }

    /** A transfer moved on or changed state. Throttled per transfer; a state change always comes through. */
    onProgress(handler: (payload: TransferInfo) => void): () => void {
        return this.transport.subscribe("transfer.progress", json => handler(JSON.parse(json) as TransferInfo));
    }

    /** A transfer completed; a download is in place at its path. */
    onCompleted(handler: (payload: TransferInfo) => void): () => void {
        return this.transport.subscribe("transfer.completed", json => handler(JSON.parse(json) as TransferInfo));
    }

    /** A transfer failed. */
    onFailed(handler: (payload: TransferInfo) => void): () => void {
        return this.transport.subscribe("transfer.failed", json => handler(JSON.parse(json) as TransferInfo));
    }

    /** A transfer was cancelled. */
    onCancelled(handler: (payload: TransferInfo) => void): () => void {
        return this.transport.subscribe("transfer.cancelled", json => handler(JSON.parse(json) as TransferInfo));
    }
}
