// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.InAppPurchases.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid, segment } from "./core.js";

/** How to finish a purchase. */
export interface FinishPurchaseRequest {
    /** True for a consumable, so it can be bought again; false acknowledges a non-consumable or subscription. Apple has no separate consume step, so this only matters on Google Play — but always say what the product is. */
    consume: boolean;
}

/** Which subscription management screen to open. */
export interface ManageSubscriptionsRequest {
    /** Android: focus on this subscription. Apple always opens the full list. */
    productId?: string | null;
}

/** One phase of a subscription's price schedule. */
export interface PricingPhase {
    /** The localized, formatted price of one billing period. */
    displayPrice: string;
    /** The price of one billing period, as a number. */
    price: number;
    /** ISO 4217 currency code. */
    currencyCode: string;
    /** An ISO 8601 duration: `P1W`, `P1M`, `P1Y`. */
    billingPeriod: string;
    /** How many periods the phase lasts; 0 recurs until cancelled. */
    billingCycleCount: number;
    /** How the phase is charged. */
    paymentMode: SubscriptionPaymentMode;
}

/** What kind of product it is. */
export type ProductType = "OneTime" | "Subscription";

/** The products to load. */
export interface ProductsRequest {
    /** Store product ids, as configured in App Store Connect or the Play Console. */
    productIds: string[];
}

/** A purchase as the device's store reports it. */
export interface Purchase {
    /** The store it was made through. */
    platform: StorePlatform;
    /** The store product id. */
    productId: string;
    /** Unique per charge — finish it by this. Apple: the transaction id, new on each renewal. Google: the order id, or the purchase token while the purchase is pending. */
    transactionId: string;
    /** Stable across renewals. Apple: the original transaction id. Google: the purchase token. */
    originalTransactionId: string;
    /** Purchased, pending or revoked. */
    state: PurchaseState;
    /** When it — or this renewal — was bought. */
    purchaseDate: string;
    /** Apple subscriptions only; Google does not report expiry on the device, so ask your server. */
    expirationDate: string | null;
    /** Apple: finished. Google: acknowledged or consumed. */
    isFinished: boolean;
    /** A subscription set to renew. */
    isAutoRenewing: boolean;
    /** Units bought. */
    quantity: number;
    /** The `accountToken` it was bought with. */
    accountToken: string | null;
    /** Send this to your server to verify the purchase. Apple: the signed JWS transaction. Google: the purchase token. Shiny.Mobile.InAppPurchases.Server's `IPurchaseVerifier` takes it as it is. */
    verificationData: string;
    /** The bundle id (Apple) or package name (Google). */
    appId: string;
    /** The store environment; always Unknown on Google Play. */
    environment: StoreEnvironment;
    /** The store's raw JSON for the transaction. */
    originalJson: string | null;
    /** Google Play: the RSA signature of `originalJson`. Null on Apple. */
    signature: string | null;
    /** Apple: when it was refunded or revoked. */
    revocationDate: string | null;
}

/** A product to buy. */
export interface PurchaseRequest {
    /** The store product id. */
    productId: string;
    /** Your user's id. It comes back on every transaction and in the stores' server notifications (Apple `appAccountToken`, Google `obfuscatedAccountId`), so your server can tell whose purchase it is. Always set it. */
    accountToken?: string | null;
    /** Google Play: the `offerToken` to buy; the first base plan when omitted. Ignored on Apple. */
    offerToken?: string | null;
    /** Apple: how many units of a consumable, 1 to 10. Google lets the user choose in the sheet when the product allows it. */
    quantity?: number;
    /** Google Play: the subscription this one replaces. Ignored on Apple. */
    replacement?: SubscriptionReplacement | null;
}

/** How a purchase sheet ended. */
export interface PurchaseResult {
    /** What happened. */
    status: PurchaseResultStatus;
    /** Set on `Success`, and on `Pending` when the store reports one. */
    purchase: Purchase | null;
}

/** How a purchase sheet ended. */
export type PurchaseResultStatus = "Success" | "Pending" | "Cancelled" | "AlreadyOwned";

/** Where a purchase stands. */
export type PurchaseState = "Purchased" | "Pending" | "Revoked";

/** The store this device buys through, and whether it can buy now. */
export interface PurchasesStatus {
    /** App Store or Google Play. */
    platform: StorePlatform;
    /** False when the store is unreachable or payments are blocked — parental controls, MDM, an unsupported country, no Play Store. */
    canMakePayments: boolean;
}

/** Which store environment a purchase was made in. */
export type StoreEnvironment = "Unknown" | "Production" | "Sandbox" | "Xcode";

/** The store a device buys through. */
export type StorePlatform = "AppStore" | "GooglePlay";

/** A localized product from the store. */
export interface StoreProduct {
    /** The store product id. */
    id: string;
    /** One-time purchase or subscription. */
    type: ProductType;
    /** The localized name. */
    title: string;
    /** The localized description. */
    description: string;
    /** The localized, formatted price — for a subscription, the recurring price of its default plan. */
    displayPrice: string;
    /** The price as a number, in `currencyCode`. */
    price: number;
    /** ISO 4217 currency code. */
    currencyCode: string;
    /** Google Play: one per base plan and per offer the user is eligible for; buy one with its `offerToken`. Apple: the introductory offer when the user is eligible, then promotional offers. */
    subscriptionOffers: SubscriptionOffer[];
    /** Apple's subscription group; null on Google Play and for one-time products. */
    subscriptionGroupId: string | null;
}

/** A subscription base plan or offer. */
export interface SubscriptionOffer {
    /** Apple's offer id or Google's; null for an Apple introductory offer and a Google base plan. */
    offerId: string | null;
    /** Google's base plan id; null on Apple. */
    basePlanId: string | null;
    /** Google Play: pass it as `offerToken` to buy this offer. Null on Apple. */
    offerToken: string | null;
    /** An Apple introductory offer, or a Google free trial or introductory price. */
    isIntroductory: boolean;
    /** The price schedule in order — a free trial, then the recurring price. */
    pricingPhases: PricingPhase[];
    /** Google offer tags; empty on Apple. */
    tags: string[];
}

/** How a subscription pricing phase is charged. */
export type SubscriptionPaymentMode = "Recurring" | "FreeTrial" | "PayAsYouGo" | "PayUpFront";

/** Replaces a Google Play subscription with another — an upgrade or downgrade. Apple changes plans within a subscription group itself. */
export interface SubscriptionReplacement {
    /** The subscription being replaced. */
    oldProductId: string;
    /** Its purchase token: the old purchase's `originalTransactionId`. */
    oldPurchaseToken: string;
    /** How the change is prorated and charged. */
    mode?: SubscriptionReplacementMode;
}

/** How a Google Play subscription change is prorated and charged. */
export type SubscriptionReplacementMode = "Default" | "WithTimeProration" | "ChargeProratedPrice" | "ChargeFullPrice" | "WithoutProration" | "Deferred";

/**
 * In-app purchases — consumables, non-consumables and auto-renewable subscriptions — through the App Store (StoreKit 2) on iOS and Google Play Billing on Android. The store's own sheet takes the payment; the page never sees card details.
 *
 * Verify, grant, then finish: send `verificationData` to your server, store the entitlement, and only then call `finish`. Never grant a `Pending` purchase. Google Play refunds a purchase that is not finished within three days.
 *
 * Store failures answer with the error code the page switches on: 503 `store_unavailable` or `network`, 403 `not_allowed`, 404 `product_not_found`, 409 `product_unavailable`, `no_user_interface` or `invalid_state`, 400 `developer_error`, and 502 `verification_failed` or `purchase_failed`.
 */
export class InAppPurchasesBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** Which store this device buys through, and whether this user may make payments right now. */
    getStatus(options?: { signal?: AbortSignal }): Promise<PurchasesStatus> {
        return call<PurchasesStatus>(this.transport, "GET", `purchases`, { signal: options?.signal });
    }

    /** Localized products and prices. Ids the store does not know are left out rather than failing. */
    getProducts(request: ProductsRequest, options?: { signal?: AbortSignal }): Promise<StoreProduct[]> {
        return call<StoreProduct[]>(this.transport, "POST", `purchases/products`, { json: request, signal: options?.signal });
    }

    /** Opens the store's purchase sheet. A cancelled sheet, a pending payment (Ask to Buy, a slow payment method) and a product already owned are results, not errors. A `Success` is not finished: verify and grant it, then call `finish`. */
    purchase(request: PurchaseRequest, options?: { signal?: AbortSignal }): Promise<PurchaseResult> {
        return call<PurchaseResult>(this.transport, "POST", `purchases/purchase`, { json: request, signal: options?.signal });
    }

    /** What the user owns now: non-consumables, active subscriptions, and consumables not yet finished. */
    getEntitlements(options?: { signal?: AbortSignal }): Promise<Purchase[]> {
        return call<Purchase[]>(this.transport, "GET", `purchases/entitlements`, { signal: options?.signal });
    }

    /** Purchases that were paid for but never finished — check at startup, and run each through the same verify, grant, finish path, so a crash between payment and finishing never loses a purchase. */
    getUnfinished(options?: { signal?: AbortSignal }): Promise<Purchase[]> {
        return call<Purchase[]>(this.transport, "GET", `purchases/unfinished`, { signal: options?.signal });
    }

    /** Finishes a purchase once its entitlement is stored. `consume` makes a consumable buyable again. The bridge finds the purchase in the store by its transaction id, and fails with 404 (`purchase_not_found`) when the store has no unfinished purchase or entitlement by it — typically because it was finished already. */
    finish(transactionId: string, request: FinishPurchaseRequest, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `purchases/transactions/${segment(transactionId)}/finish`, { json: request, signal: options?.signal });
    }

    /** Restores purchases and returns the entitlements. On iOS this syncs with the App Store and may ask the user to sign in, so call it only from a "Restore Purchases" button. */
    restore(options?: { signal?: AbortSignal }): Promise<Purchase[]> {
        return call<Purchase[]>(this.transport, "POST", `purchases/restore`, { signal: options?.signal });
    }

    /** Opens the store's subscription management screen — on Android, focused on one product when it is named. */
    showManageSubscriptions(request: ManageSubscriptionsRequest, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `purchases/manage`, { json: request, signal: options?.signal });
    }

    /** A purchase changed outside a `purchase` call: an Ask to Buy approval, a pending payment that completed, a renewal, a refund, a purchase on another device, an offer code. The same purchase can arrive more than once, so handle it idempotently by `transactionId`. Also handed to a `purchases.updated` handler, so background.js can verify, grant and finish it when no page is open. */
    onUpdated(handler: (payload: Purchase) => void): Promise<() => void> {
        return this.transport.subscribe("purchases.updated", json => handler(JSON.parse(json) as Purchase));
    }
}
