// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.LiveActivities.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid, segment } from "./core.js";
import type { AccessState } from "./shared.js";

/** Whether this app can show live activities. */
export interface LiveActivitiesStatus {
    /** The iOS Live Activities switch for this app, or notification permission on Android. */
    access: AccessState;
    /** The device's push-to-start token (iOS 17.2+); null on Android, older iOS, and until the system issues one. */
    pushToStartToken: string | null;
}

/** A running, or recently ended, live activity. */
export interface LiveActivity {
    /** The system's id, which updates and ends it. */
    id: string;
    /** Where it is in its life. */
    state: LiveActivityState;
    /** The token that addresses it from a server, once the system issued one (iOS). */
    pushToken: string | null;
}

/** Turns an update into a banner, and a tap on a paired watch, instead of a silent refresh. */
export interface LiveActivityAlert {
    title: string;
    body?: string | null;
}

/** What an activity says — everything that can change while it runs. */
export interface LiveActivityContent {
    /** The headline: "Arriving in 5 min", the team names. */
    title?: string | null;
    /** Detail under the title. */
    body?: string | null;
    /** A few characters for the tightest places — the compact Dynamic Island and the Android 16 status bar chip: "5 min", "2-1". */
    shortStatus?: string | null;
    /** An optional progress bar. */
    progress?: LiveActivityProgress | null;
    /** When this content goes out of date; the activity turns `Stale` then. */
    staleDate?: Date | string | null;
    /** Ranks this activity against the app's others when several run (iOS). */
    relevanceScore?: number | null;
    /** Strings for the app's own widget to read. */
    data?: Record<string, string> | null;
}

/** How an activity ends. */
export interface LiveActivityEndRequest {
    /** Final content to show until it is dismissed; the last content when omitted. */
    content?: LiveActivityContent | null;
    /** When to take it off screen; the system decides when omitted, and a past time removes it now. */
    dismissAt?: Date | string | null;
}

/** A progress bar. Set `value`, or `start` and `end` for a timer the system advances itself, or `indeterminate`. */
export interface LiveActivityProgress {
    /** The completed fraction, 0 to 1. */
    value?: number | null;
    /** The start of a time range the system animates between. */
    start?: Date | string | null;
    /** The end of that range. */
    end?: Date | string | null;
    /** Progress of unknown length. */
    indeterminate?: boolean;
}

/** The device's push-to-start token. */
export interface LiveActivityPushToStartToken {
    token: string;
}

/** An activity's push token. */
export interface LiveActivityPushToken {
    /** The activity it addresses. */
    activityId: string;
    /** The APNs token, hex. */
    token: string;
}

/** An activity to start. */
export interface LiveActivityStartRequest {
    /** What it says first. */
    content: LiveActivityContent;
    /** What never changes for its lifetime — an order number, the teams. A push-to-start payload names the same attributes. */
    attributes?: Record<string, string> | null;
    /** Which layout renders it, for an app whose widget has more than one. */
    kind?: string | null;
    /** Ask for a push token so a server can update it; it arrives as `liveactivities.token`. On iOS the app needs the `aps-environment` entitlement for this, or the start fails. */
    requestPushToken?: boolean;
}

/** Where a live activity is in its life. */
export type LiveActivityState = "Active" | "Stale" | "Ended" | "Dismissed";

/** New content for a running activity. */
export interface LiveActivityUpdateRequest {
    /** Replaces what it says. */
    content: LiveActivityContent;
    /** Alert the user about the change; silent when omitted. */
    alert?: LiveActivityAlert | null;
}

/** Live activities: iOS/iPadOS Live Activities on the Lock Screen and in the Dynamic Island, and Android 16 Live Updates (an ordinary ongoing notification on older Android). The page decides what an activity says; the app's widget decides how it looks. */
export class LiveActivitiesBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** Whether the user allows live activities, and the device's push-to-start token when it has one. */
    getStatus(options?: { signal?: AbortSignal }): Promise<LiveActivitiesStatus> {
        return call<LiveActivitiesStatus>(this.transport, "GET", `liveactivities`, { signal: options?.signal });
    }

    /** Asks for the permission live activities need — notification permission on Android. iOS has no prompt, so it reports the Live Activities switch in Settings. */
    requestAccess(options?: { signal?: AbortSignal }): Promise<LiveActivitiesStatus> {
        return call<LiveActivitiesStatus>(this.transport, "POST", `liveactivities/access`, { signal: options?.signal });
    }

    /** The activities this app has running, newest first. */
    getActivities(options?: { signal?: AbortSignal }): Promise<LiveActivity[]> {
        return call<LiveActivity[]>(this.transport, "GET", `liveactivities/activities`, { signal: options?.signal });
    }

    /** Starts an activity. Fails with 502 (`live_activity_failed`) when the system refuses it — the user switched live activities off, or the app has too many running. */
    start(request: LiveActivityStartRequest, options?: { signal?: AbortSignal }): Promise<LiveActivity> {
        return call<LiveActivity>(this.transport, "POST", `liveactivities/activities`, { json: request, signal: options?.signal });
    }

    /** Replaces a running activity's content. Fails with 404 when no running activity has the id. */
    update(id: string, request: LiveActivityUpdateRequest, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "PUT", `liveactivities/activities/${segment(id)}`, { json: request, signal: options?.signal });
    }

    /** Ends an activity, optionally showing final content until it is dismissed. Fails with 404 when no running activity has the id. */
    end(id: string, request: LiveActivityEndRequest, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `liveactivities/activities/${segment(id)}/end`, { json: request, signal: options?.signal });
    }

    /** Ends every activity this app has running. */
    endAll(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `liveactivities/activities`, { signal: options?.signal });
    }

    /** An activity started — from this app, or from a push-to-start notification. Also handed to a `liveactivities.started` handler. */
    onStarted(handler: (payload: LiveActivity) => void): Promise<() => void> {
        return this.transport.subscribe("liveactivities.started", json => handler(JSON.parse(json) as LiveActivity));
    }

    /** An activity became stale, ended or was dismissed. Also handed to a `liveactivities.state` handler. */
    onStateChanged(handler: (payload: LiveActivity) => void): Promise<() => void> {
        return this.transport.subscribe("liveactivities.state", json => handler(JSON.parse(json) as LiveActivity));
    }

    /** The system issued or rotated the push token for one activity (iOS). Send it to your server: it is the only way to update that activity remotely. Also handed to a `liveactivities.token` handler, so background.js can send it when no page is open. */
    onPushToken(handler: (payload: LiveActivityPushToken) => void): Promise<() => void> {
        return this.transport.subscribe("liveactivities.token", json => handler(JSON.parse(json) as LiveActivityPushToken));
    }

    /** The device's push-to-start token appeared or rotated (iOS 17.2+). A server uses it to start an activity while the app is not running. Also handed to a `liveactivities.starttoken` handler. */
    onPushToStartToken(handler: (payload: LiveActivityPushToStartToken) => void): Promise<() => void> {
        return this.transport.subscribe("liveactivities.starttoken", json => handler(JSON.parse(json) as LiveActivityPushToStartToken));
    }
}
