// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Locations.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid, query, segment } from "./core.js";
import type { AccessState } from "./shared.js";

/** A circular region. */
export interface GeofenceRegion {
    /** Names the region; monitoring one with an identifier already in use replaces it. */
    identifier: string;
    latitude: number;
    longitude: number;
    /** Must be positive. */
    radiusMeters: number;
    /** Stop monitoring after the first transition. */
    singleUse: boolean;
    notifyOnEntry: boolean;
    notifyOnExit: boolean;
}

export type GeofenceState = "Unknown" | "Entered" | "Exited";

export interface GeofenceStatus {
    identifier: string;
    state: GeofenceState;
}

/** Which kind of GPS use a permission check is for. */
export type GpsAccessMode = "Foreground" | "Background" | "Realtime";

/** How a listener keeps running with the app in the background. */
export type GpsBackgroundMode = "None" | "Standard" | "Realtime";

export interface GpsListenerSettings {
    backgroundMode: GpsBackgroundMode;
    /** Ask for precise rather than approximate location where the platform distinguishes. */
    requestPreciseAccuracy: boolean;
    /** Restart the listener after the app is relaunched. */
    autoRestart: boolean;
}

/** A position. */
export interface GpsReading {
    latitude: number;
    longitude: number;
    /** Meters. */
    positionAccuracy: number;
    timestamp: string;
    /** Degrees from north. */
    heading: number;
    headingAccuracy: number;
    /** Meters. */
    altitude: number;
    /** Meters per second. */
    speed: number;
    speedAccuracy: number;
    floor: number;
    isStationary: boolean;
}

export interface LocationAccessResult {
    access: AccessState;
}

export interface MotionActivity {
    activity: MotionActivityType;
    confidence: MotionActivityConfidence;
    timestamp: string;
}

export type MotionActivityConfidence = "Low" | "Medium" | "High";

export type MotionActivityType = "Unknown" | "Stationary" | "Walking" | "Running" | "Cycling" | "Automotive";

export interface MotionListener {
    isListening: boolean;
}

/** Geofences: monitor circular regions and hear when the device enters or leaves one. Android, iOS, Mac Catalyst and Windows; elsewhere every call fails with 501. */
export class GeofencesBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** The permission state, without prompting. */
    getStatus(options?: { signal?: AbortSignal }): Promise<LocationAccessResult> {
        return call<LocationAccessResult>(this.transport, "GET", `geofences/status`, { signal: options?.signal });
    }

    /** Requests the background location permission geofencing needs. */
    requestAccess(options?: { signal?: AbortSignal }): Promise<LocationAccessResult> {
        return call<LocationAccessResult>(this.transport, "POST", `geofences/access`, { signal: options?.signal });
    }

    /** The regions being monitored. */
    getRegions(options?: { signal?: AbortSignal }): Promise<GeofenceRegion[]> {
        return call<GeofenceRegion[]>(this.transport, "GET", `geofences/regions`, { signal: options?.signal });
    }

    /** Starts monitoring a region. Fails with 409 without permission. */
    startMonitoring(region: GeofenceRegion, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `geofences/regions`, { json: region, signal: options?.signal });
    }

    /** Stops monitoring every region. */
    stopAllMonitoring(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `geofences/regions`, { signal: options?.signal });
    }

    /** Stops monitoring one region. */
    stopMonitoring(identifier: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `geofences/regions/${segment(identifier)}`, { signal: options?.signal });
    }

    /** Whether the device is inside a monitored region now. Fails with 404 for a region not monitored. */
    getState(identifier: string, options?: { signal?: AbortSignal }): Promise<GeofenceStatus> {
        return call<GeofenceStatus>(this.transport, "GET", `geofences/regions/${segment(identifier)}/state`, { signal: options?.signal });
    }

    /** The device entered or left a region, while the page is open. */
    onStatus(handler: (payload: GeofenceStatus) => void): () => void {
        return this.transport.subscribe("geofence.status", json => handler(JSON.parse(json) as GeofenceStatus));
    }
}

/** GPS: permission, the last and current position, and a listener whose readings arrive as events. Android, iOS, Mac Catalyst and Windows; elsewhere every call fails with 501. */
export class GpsBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** The permission state for a kind of GPS use, without prompting. */
    getStatus(options?: { mode?: GpsAccessMode; signal?: AbortSignal }): Promise<LocationAccessResult> {
        return call<LocationAccessResult>(this.transport, "GET", `gps/status` + query({ mode: options?.mode }), { signal: options?.signal });
    }

    /** Requests the permission the listener settings need — background access for a background mode. */
    requestAccess(settings: GpsListenerSettings, options?: { signal?: AbortSignal }): Promise<LocationAccessResult> {
        return call<LocationAccessResult>(this.transport, "POST", `gps/access`, { json: settings, signal: options?.signal });
    }

    /** The last known position, or null when there is none. */
    getLastReading(options?: { signal?: AbortSignal }): Promise<GpsReading | null> {
        return call<GpsReading | null>(this.transport, "GET", `gps/last`, { signal: options?.signal });
    }

    /** A fresh position, or null when none could be had. */
    getCurrentPosition(options?: { signal?: AbortSignal }): Promise<GpsReading | null> {
        return call<GpsReading | null>(this.transport, "GET", `gps/current`, { signal: options?.signal });
    }

    /** The running listener's settings, or null when not listening. */
    getListener(options?: { signal?: AbortSignal }): Promise<GpsListenerSettings | null> {
        return call<GpsListenerSettings | null>(this.transport, "GET", `gps/listener`, { signal: options?.signal });
    }

    /** Starts listening; readings arrive through `onReading`, and in the background to the web app's `gps` handler. Fails with 409 without permission or while another listener runs. */
    startListener(settings: GpsListenerSettings, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `gps/listener`, { json: settings, signal: options?.signal });
    }

    /** Stops listening. */
    stopListener(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `gps/listener`, { signal: options?.signal });
    }

    /** A reading from the listener, while the page is open. */
    onReading(handler: (payload: GpsReading) => void): () => void {
        return this.transport.subscribe("gps.reading", json => handler(JSON.parse(json) as GpsReading));
    }
}

/** Motion activity: walking, running, cycling, driving or stationary, as the OS's activity recognition reports it. Android, iOS and Mac Catalyst; elsewhere every call fails with 501. There is no history, only the latest reading and live ones. */
export class MotionBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** The permission state, without prompting. */
    getStatus(options?: { signal?: AbortSignal }): Promise<LocationAccessResult> {
        return call<LocationAccessResult>(this.transport, "GET", `motion/status`, { signal: options?.signal });
    }

    /** Requests motion activity permission. */
    requestAccess(options?: { signal?: AbortSignal }): Promise<LocationAccessResult> {
        return call<LocationAccessResult>(this.transport, "POST", `motion/access`, { signal: options?.signal });
    }

    /** The latest reading, or null when there is none. */
    getCurrent(options?: { signal?: AbortSignal }): Promise<MotionActivity | null> {
        return call<MotionActivity | null>(this.transport, "GET", `motion/current`, { signal: options?.signal });
    }

    /** Whether the listener is running. */
    getListener(options?: { signal?: AbortSignal }): Promise<MotionListener> {
        return call<MotionListener>(this.transport, "GET", `motion/listener`, { signal: options?.signal });
    }

    /** Starts listening; readings arrive through `onActivity`, and in the background to the web app's `motion` handler. Fails with 409 without permission. */
    startListener(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `motion/listener`, { signal: options?.signal });
    }

    /** Stops listening. */
    stopListener(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `motion/listener`, { signal: options?.signal });
    }

    /** A reading from the listener, while the page is open. */
    onActivity(handler: (payload: MotionActivity) => void): () => void {
        return this.transport.subscribe("motion.activity", json => handler(JSON.parse(json) as MotionActivity));
    }
}
