// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Maps.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callBlob, callVoid, query, segment } from "./core.js";

export interface DirectionsInfo {
    /** Whether the app configured an online router. */
    online: boolean;
    /** Whether this platform can compute routes on the device. It still needs a downloaded road network to do so. */
    onDevice: boolean;
    /** The regions whose road network is on the device. */
    offlineRegions: string[];
    /** Whether the app configured a geocoder, so `geocode` can turn an address into a stop. */
    geocoding: boolean;
}

export interface DirectionsRequest {
    /** Two or more, in order: where the route starts, any stops along the way, where it ends. */
    stops: RouteStop[];
    mode?: TravelMode;
    units?: DistanceUnits;
    /** An IETF language tag for the instructions, such as `en-US` or `fr`. English when null or unsupported. */
    language?: string | null;
    source?: DirectionsSource;
    avoid?: RouteAvoid | null;
}

export interface DirectionsRoute {
    /** Where the route was computed: `Device` or `Online`. */
    source: DirectionsSource;
    /** Metres. */
    distance: number;
    /** Seconds. */
    duration: number;
    /** The line to draw, as `[longitude, latitude]` pairs — GeoJSON's order, so it drops into a LineString as it is. */
    shape: number[][];
    /** `[west, south, east, north]` around `shape`, for fitting the map to the route. */
    bounds: number[];
    legs: RouteLeg[];
}

/** Where a route is computed. */
export type DirectionsSource = "Auto" | "Device" | "Online";

/** The units spoken and written instructions use. Distances in the response are always metres. */
export type DistanceUnits = "Kilometers" | "Miles";

export interface GeocodeResult {
    /** Best match first. Empty when nothing matched. */
    places: GeocodedPlace[];
    /** The credit the geocoder's terms require, as HTML. */
    attribution: string;
}

/** A place a geocoder found for an address or a name. */
export interface GeocodedPlace {
    /** What the place is called: "Union Station", "1701 Wynkoop Street". */
    name: string;
    /** The full address or description, which tells apart places with the same name. */
    address: string;
    latitude: number;
    longitude: number;
    /** `[west, south, east, north]` around a place with an extent — a city, a park — for fitting the map to it. Null for a point. */
    bounds: number[] | null;
}

/** What a maneuver asks the traveller to do. Enough to pick an arrow icon. */
export type ManeuverKind = "Depart" | "Arrive" | "Continue" | "SlightRight" | "Right" | "SharpRight" | "UTurn" | "SharpLeft" | "Left" | "SlightLeft" | "RampStraight" | "RampRight" | "RampLeft" | "ExitRight" | "ExitLeft" | "KeepStraight" | "KeepRight" | "KeepLeft" | "Merge" | "EnterRoundabout" | "ExitRoundabout" | "Ferry" | "Other";

export interface MapCatalog {
    /** The catalog's regions, and any installed region the catalog no longer lists. */
    regions: MapRegion[];
    /** False when the catalog could not be fetched — offline, say. The regions are then the ones last seen and the ones installed. */
    catalogReachable: boolean;
    /** Disk space the installed regions take. */
    installedBytes: number;
}

/** A region's download. Raised as `maps.download` while it runs and once more when it ends. */
export interface MapPackDownload {
    regionId: string;
    /** Whether the download includes the road network. */
    directions: boolean;
    state: MapPackDownloadState;
    bytesDownloaded: number;
    totalBytes: number;
    /** Why it failed. */
    error: string | null;
}

export type MapPackDownloadState = "Queued" | "Downloading" | "Verifying" | "Installed" | "Failed" | "Cancelled";

export interface MapPackInstallRequest {
    /** Also download the road network, so directions inside the region work offline. Ignored when the region does not offer it. */
    directions?: boolean;
}

/** A region the page can download, merged with what is on the device. */
export interface MapRegion {
    id: string;
    name: string;
    /** `[west, south, east, north]` in degrees. */
    bounds: number[];
    /** Bytes to download for the map tiles. */
    mapSize: number;
    /** Bytes to download for on-device directions, when the region offers them. */
    directionsSize: number | null;
    /** Whether the region's map is on the device, so it draws offline. */
    mapInstalled: boolean;
    /** Whether the region's road network is on the device, so directions inside it work offline. */
    directionsInstalled: boolean;
    /** Whether the catalog has a newer build of an installed part. */
    updateAvailable: boolean;
    /** The download in progress for this region, if any. */
    download: MapPackDownload | null;
}

/** Everything a map renderer needs to draw from the bridge. The URLs are templates MapLibre (or any vector-tile renderer) fills in itself, relative to the page's origin and already under the bridge's prefix. */
export interface MapsInfo {
    /** The vector tiles: `…/maps/tiles/{z}/{x}/{y}`. Served from a downloaded region when one covers the tile, from the online source otherwise. */
    tilesUrl: string;
    /** The label fonts: `…/maps/glyphs/{fontstack}/{range}.pbf`. */
    glyphsUrl: string;
    /** The icon sheets. Append a flavor — `light`, `dark`, `white`, `grayscale`, `black` — for MapLibre's `sprite`. */
    spritesUrl: string;
    /** The highest zoom the tiles carry. The renderer draws closer zooms by scaling these, which vector tiles do cleanly. */
    maxZoom: number;
    /** Whether the app configured an online tile source. Without one, only downloaded regions draw. */
    online: boolean;
    /** Whether the app configured a region catalog to download from. */
    catalog: boolean;
    /** The credit the map data's licence requires, as HTML. */
    attribution: string;
    /** The live traffic layer, when the app configured a traffic provider. Null otherwise. */
    traffic: TrafficInfo | null;
    /** Live traffic incidents — accidents, roadworks, closures — when the app configured an incident provider. Null otherwise. */
    incidents: TrafficIncidentInfo | null;
}

export interface RouteAvoid {
    tolls?: boolean;
    highways?: boolean;
    ferries?: boolean;
}

/** The part of a route between two consecutive stops. */
export interface RouteLeg {
    distance: number;
    duration: number;
    maneuvers: RouteManeuver[];
}

export interface RouteManeuver {
    kind: ManeuverKind;
    /** Written for reading: "Turn right onto North Broadway." */
    instruction: string;
    /** Written for speaking before the maneuver, when the router provides it. */
    verbalInstruction: string | null;
    /** Metres from this maneuver to the next. */
    distance: number;
    /** Seconds from this maneuver to the next. */
    duration: number;
    streetNames: string[];
    /** Where the maneuver is: an index into `shape`. */
    shapeIndex: number;
    /** Which exit to take, for `EnterRoundabout`. */
    roundaboutExit: number | null;
}

export interface RouteStop {
    latitude: number;
    longitude: number;
    name?: string | null;
}

/** A live layer of traffic incidents, whatever provider is behind it: vector tiles holding the stretch of road an incident affects as lines, where it is as points, or both. Tiles come through the bridge, which holds the provider's key, and only while online. */
export interface TrafficIncidentInfo {
    /** The incident tiles: `…/maps/incidents/{z}/{x}/{y}`. */
    tilesUrl: string;
    /** Below this the layer draws nothing, and no tiles are asked for. */
    minZoom: number;
    /** The highest zoom the provider has. The renderer scales past it. */
    maxZoom: number;
    /** How often the page should fetch the tiles again. */
    refreshSeconds: number;
    /** The layer inside each tile holding the affected stretches of road. Null when the provider has none. */
    lineSourceLayer: string | null;
    /** The layer inside each tile holding incident locations. Null when the provider has none. */
    pointSourceLayer: string | null;
    /** The property holding the provider's incident type. */
    kindProperty: string;
    /** The provider's values of `kindProperty`, as text, and what each is. Anything not listed is `Other`. */
    kinds: Record<string, TrafficIncidentKind>;
    /** The property holding a description to show for an incident. Null when there is none. */
    descriptionProperty: string | null;
    /** The property holding the delay the incident causes, in seconds. Null when there is none. */
    delayProperty: string | null;
    /** The property holding how many incidents a point stands for, where the provider groups them. Null when it does not. */
    clusterSizeProperty: string | null;
    /** The credit the provider's terms require, as HTML. */
    attribution: string;
}

/** What a traffic incident is, whatever each provider calls it. The map colours incidents by it. */
export type TrafficIncidentKind = "Other" | "Accident" | "Congestion" | "RoadWorks" | "RoadClosed" | "LaneClosed" | "Weather" | "Hazard" | "BrokenDownVehicle";

/** A live traffic layer, whatever provider is behind it. Tiles come through the bridge, which holds the provider's key, and only while online: offline the layer is simply empty. */
export interface TrafficInfo {
    /** The traffic tiles: `…/maps/traffic/{z}/{x}/{y}`. */
    tilesUrl: string;
    format: TrafficTileFormat;
    /** Below this the layer draws nothing, and no tiles are asked for. */
    minZoom: number;
    /** The highest zoom the provider has. The renderer scales past it. */
    maxZoom: number;
    /** How often the provider's data changes, so how often the page should fetch the tiles again. */
    refreshSeconds: number;
    /** Vector: the layer inside each tile holding the road segments. */
    sourceLayer: string | null;
    /** Vector: the property holding current speed over free-flow speed, from 0 (stopped) to 1 (free flow). */
    speedRatioProperty: string | null;
    /** Vector: the property that is true on a closed road. Null when the provider does not mark closures. */
    closedProperty: string | null;
    /** Raster: the images' size in pixels. */
    tileSize: number;
    /** The credit the provider's terms require, as HTML. */
    attribution: string;
}

/** How a traffic provider's tiles are drawn. */
export type TrafficTileFormat = "Vector" | "Raster";

export type TravelMode = "Car" | "Bicycle" | "Walking" | "Truck";

/** Turn-by-turn directions. A route is computed on the device when the user downloaded the road network of a region covering every stop and the platform can run the router, and by the app's online router otherwise. Addresses become stops through the app's geocoder. The router's and the geocoder's addresses and keys stay in the native app; the page never sees them. */
export class DirectionsBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** Which sources can answer. */
    getInfo(options?: { signal?: AbortSignal }): Promise<DirectionsInfo> {
        return call<DirectionsInfo>(this.transport, "GET", `directions`, { signal: options?.signal });
    }

    /** Computes a route through the stops. Fails with 400 for fewer than two stops or a stop off the map, 404 when no route connects them, 503 (`offline_unavailable`) when the device cannot compute it and the online router cannot be reached, 501 when neither is available on this platform and app. */
    route(request: DirectionsRequest, options?: { signal?: AbortSignal }): Promise<DirectionsRoute> {
        return call<DirectionsRoute>(this.transport, "POST", `directions/route`, { json: request, signal: options?.signal });
    }

    /** Finds places matching an address or a name — "1701 Wynkoop St, Denver", "Red Rocks Amphitheatre" — best first, for turning what the user typed into a `RouteStop`. Always online. Fails with 400 for an empty query or one over 200 characters, 503 (`geocoder_unavailable`) when the geocoder cannot be reached, 501 when the app configured no geocoder. */
    geocode(queryValue: string, options?: { limit?: number; language?: string | null; signal?: AbortSignal }): Promise<GeocodeResult> {
        return call<GeocodeResult>(this.transport, "GET", `directions/geocode` + query({ query: queryValue, limit: options?.limit, language: options?.language }), { signal: options?.signal });
    }
}

/** Vector maps the page draws with MapLibre or any other vector-tile renderer. Tiles come from a region the user downloaded when one covers them, and from the app's online source otherwise, so the page asks for one set of URLs and never has to know which. Regions are listed from the app's signed catalog and downloaded on request. */
export class MapsBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** The URLs to hand the renderer, and what the app configured. */
    getInfo(options?: { signal?: AbortSignal }): Promise<MapsInfo> {
        return call<MapsInfo>(this.transport, "GET", `maps`, { signal: options?.signal });
    }

    /** The downloadable regions and what is installed. The catalog is fetched again when `refresh` is true or the last copy is old; offline, the last copy is used. */
    getRegions(options?: { refresh?: boolean; signal?: AbortSignal }): Promise<MapCatalog> {
        return call<MapCatalog>(this.transport, "GET", `maps/regions` + query({ refresh: options?.refresh }), { signal: options?.signal });
    }

    /** Starts downloading a region — its map, and its road network when asked — or updates an installed one to the catalog's build. Returns at once: `Installed` when the device already has the catalog's build, `Queued` otherwise, with progress arriving as `maps.download` — possibly before this reply does, so a page that tracks progress keeps the newest event rather than this reply. Fails with 404 for a region the catalog does not list, 409 when one is already downloading, 501 when the app configured no catalog. */
    install(id: string, request: MapPackInstallRequest, options?: { signal?: AbortSignal }): Promise<MapPackDownload> {
        return call<MapPackDownload>(this.transport, "POST", `maps/regions/${segment(id)}`, { json: request, signal: options?.signal });
    }

    /** Removes a region — map and road network — from the device, cancelling its download if one is running. */
    remove(id: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `maps/regions/${segment(id)}`, { signal: options?.signal });
    }

    /** Removes only a region's road network: the map still draws offline, directions go online. */
    removeDirections(id: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `maps/regions/${segment(id)}/directions`, { signal: options?.signal });
    }

    /** Cancels a region's download. What was already installed stays. */
    cancelDownload(id: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `maps/regions/${segment(id)}/download`, { signal: options?.signal });
    }

    /** One vector tile, as MapLibre asks for it through `tilesUrl`. 204 when no source has it — outside every downloaded region while offline. */
    getTile(z: number, x: number, y: number, options?: { signal?: AbortSignal }): Promise<Blob> {
        return callBlob(this.transport, "GET", `maps/tiles/${segment(z)}/${segment(x)}/${segment(y)}`, { signal: options?.signal });
    }

    /** One live traffic tile, as the renderer asks for it through `tilesUrl`: a vector tile or an image, as `format` says. 204 when the provider has nothing there or cannot be reached; 501 when the app configured no traffic provider. */
    getTrafficTile(z: number, x: number, y: number, options?: { signal?: AbortSignal }): Promise<Blob> {
        return callBlob(this.transport, "GET", `maps/traffic/${segment(z)}/${segment(x)}/${segment(y)}`, { signal: options?.signal });
    }

    /** One live traffic incident tile, as the renderer asks for it through `tilesUrl`. 204 when the provider has nothing there or cannot be reached; 501 when the app configured no incident provider. */
    getIncidentTile(z: number, x: number, y: number, options?: { signal?: AbortSignal }): Promise<Blob> {
        return callBlob(this.transport, "GET", `maps/incidents/${segment(z)}/${segment(x)}/${segment(y)}`, { signal: options?.signal });
    }

    /** A range of label glyphs, as MapLibre asks for it through `glyphsUrl`: `0-255.pbf`. */
    getGlyphs(fontstack: string, range: string, options?: { signal?: AbortSignal }): Promise<Blob> {
        return callBlob(this.transport, "GET", `maps/glyphs/${segment(fontstack)}/${segment(range)}`, { signal: options?.signal });
    }

    /** A sprite sheet or its index, as MapLibre asks for it: `light.json`, `light@2x.png`. */
    getSprite(name: string, options?: { signal?: AbortSignal }): Promise<Blob> {
        return callBlob(this.transport, "GET", `maps/sprites/${segment(name)}`, { signal: options?.signal });
    }

    /** A region's download moved on, finished, failed or was cancelled. */
    onDownload(handler: (payload: MapPackDownload) => void): Promise<() => void> {
        return this.transport.subscribe("maps.download", json => handler(JSON.parse(json) as MapPackDownload));
    }
}
