// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Notifications.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid, query, segment } from "./core.js";
import type { AccessState, BridgeFile } from "./shared.js";

export type ChannelActionType = "TextReply" | "Destructive" | "OpenApp" | "None";

export type ChannelImportance = "Low" | "Normal" | "High" | "Critical";

export type ChannelSound = "None" | "Default" | "High" | "Custom";

export interface NotificationAccessRequest {
    timeSensitive?: boolean;
    locationAware?: boolean;
}

export interface NotificationAccessResult {
    access: AccessState;
}

export interface NotificationBadge {
    value: number;
}

export type NotificationCancelScope = "All" | "Pending" | "Displayed";

export interface NotificationChannel {
    /** 1–64 letters, digits, `.`, `-` or `_`. */
    identifier: string;
    description: string | null;
    importance: ChannelImportance;
    sound: ChannelSound;
    actions: NotificationChannelAction[] | null;
}

export interface NotificationChannelAction {
    identifier: string;
    title: string;
    actionType: ChannelActionType;
}

/** A notification the user tapped or that arrived while the app was open. */
export interface NotificationEvent {
    id: number;
    title: string | null;
    message: string | null;
    channel: string | null;
    thread: string | null;
    data: Record<string, string>;
    /** The action chosen, when the user picked one rather than the notification itself. */
    action: string | null;
    /** What the user typed, for a text reply action. */
    text: string | null;
}

/** Show the notification when the device enters an area. */
export interface NotificationGeofence {
    latitude: number;
    longitude: number;
    radiusMeters: number;
    repeat: boolean;
}

/** A repeating schedule: every `intervalSeconds`, or at `timeOfDay`, optionally on one day. */
export interface NotificationRepeat {
    intervalSeconds: number | null;
    timeOfDay: string | null;
    dayOfWeek: ("Sunday" | "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday") | null;
}

/** A notification to send. */
export interface NotificationRequest {
    /** At most 4,000 characters. */
    message: string;
    title?: string | null;
    subtitle?: string | null;
    /** Replaces a notification with the same id; assigned when null. */
    id?: number | null;
    /** An Android channel identifier. */
    channel?: string | null;
    /** Groups notifications together. */
    thread?: string | null;
    badgeCount?: number | null;
    /** Show it then rather than now. */
    scheduleDate?: Date | string | null;
    repeat?: NotificationRepeat | null;
    geofence?: NotificationGeofence | null;
    /** A .png, .jpg, .gif or .heic of at most 10 MB in a file root. */
    image?: BridgeFile | null;
    /** Comes back on the tap. */
    data?: Record<string, string> | null;
}

export interface NotificationSent {
    id: number;
}

export interface NotificationStatus {
    access: AccessState;
    /** Whether the app badge can be read and set. */
    badge: boolean;
    /** Whether taps are reported. */
    entry: boolean;
    /** Whether notifications arriving while the app is open are reported. */
    received: boolean;
    /** Whether a notification can wait for the device to enter an area. */
    geofences: boolean;
    /** Whether a notification can carry an image. */
    images: boolean;
}

export interface PendingNotification {
    id: number;
    title: string | null;
    message: string | null;
    channel: string | null;
    thread: string | null;
    badgeCount: number | null;
    scheduleDate: string | null;
    repeat: NotificationRepeat | null;
    geofence: NotificationGeofence | null;
    /** Whether the web app sent it, rather than the native app. */
    fromWebApp: boolean;
    data: Record<string, string>;
}

/** Local notifications: permission, sending now or on a schedule, repeating or on entering an area, the pending list, cancelling, the app badge and Android channels. What a platform can do is in `NotificationStatus`; a feature it lacks fails with 501. */
export class NotificationsBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** Permission and what this platform supports. */
    getStatus(options?: { signal?: AbortSignal }): Promise<NotificationStatus> {
        return call<NotificationStatus>(this.transport, "GET", `notifications`, { signal: options?.signal });
    }

    /** Requests permission, optionally for time-sensitive and location-aware notifications too. */
    requestAccess(request: NotificationAccessRequest, options?: { signal?: AbortSignal }): Promise<NotificationAccessResult> {
        return call<NotificationAccessResult>(this.transport, "POST", `notifications/access`, { json: request, signal: options?.signal });
    }

    /** Sends or schedules a notification. Fails with 400 for an invalid one, such as a date already past. */
    send(notification: NotificationRequest, options?: { signal?: AbortSignal }): Promise<NotificationSent> {
        return call<NotificationSent>(this.transport, "POST", `notifications/send`, { json: notification, signal: options?.signal });
    }

    /** Scheduled notifications that have not been shown yet. */
    getPending(options?: { signal?: AbortSignal }): Promise<PendingNotification[]> {
        return call<PendingNotification[]>(this.transport, "GET", `notifications/pending`, { signal: options?.signal });
    }

    /** Cancels pending notifications, clears displayed ones, or both. */
    cancelAll(options?: { scope?: NotificationCancelScope; signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `notifications` + query({ scope: options?.scope }), { signal: options?.signal });
    }

    /** Cancels one notification. */
    cancel(id: number, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `notifications/${segment(id)}`, { signal: options?.signal });
    }

    /** The app icon's badge number. */
    getBadge(options?: { signal?: AbortSignal }): Promise<NotificationBadge> {
        return call<NotificationBadge>(this.transport, "GET", `notifications/badge`, { signal: options?.signal });
    }

    /** Sets the app icon's badge number, 0–99,999. */
    setBadge(badge: NotificationBadge, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "PUT", `notifications/badge`, { json: badge, signal: options?.signal });
    }

    /** The notification channels. */
    getChannels(options?: { signal?: AbortSignal }): Promise<NotificationChannel[]> {
        return call<NotificationChannel[]>(this.transport, "GET", `notifications/channels`, { signal: options?.signal });
    }

    /** Adds or replaces a channel. */
    addChannel(channel: NotificationChannel, options?: { signal?: AbortSignal }): Promise<NotificationChannel> {
        return call<NotificationChannel>(this.transport, "POST", `notifications/channels`, { json: channel, signal: options?.signal });
    }

    /** Removes a channel. */
    removeChannel(identifier: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `notifications/channels/${segment(identifier)}`, { signal: options?.signal });
    }

    /** The user tapped a notification, or one of its actions. */
    onEntry(handler: (payload: NotificationEvent) => void): () => void {
        return this.transport.subscribe("notification.entry", json => handler(JSON.parse(json) as NotificationEvent));
    }

    /** A notification arrived while the app was open. Apple platforms only. */
    onReceived(handler: (payload: NotificationEvent) => void): () => void {
        return this.transport.subscribe("notification.received", json => handler(JSON.parse(json) as NotificationEvent));
    }
}
