// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Obd.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid, query } from "./core.js";
import type { AccessState } from "./shared.js";

export interface ObdAdapter {
    /** A Bluetooth peripheral id, or a Wi-Fi adapter's host and port. */
    id: string;
    name: string;
    transport: ObdTransport;
    host: string | null;
    port: number | null;
}

export type ObdAdapterType = "Unknown" | "Elm327" | "ObdLink";

export interface ObdClearResult {
    cleared: boolean;
}

export interface ObdCommandInfo {
    /** Such as `engineRpm`. */
    name: string;
    /** The raw request it sends. */
    pid: string;
    unit: string | null;
}

/** An adapter to connect to: `peripheralUuid` for Bluetooth, `host` and `port` for Wi-Fi. */
export interface ObdConnectRequest {
    transport?: ObdTransport;
    peripheralUuid?: string | null;
    host?: string | null;
    port?: number | null;
    /** Up to 60,000 ms; 30 seconds when null. */
    timeoutMs?: number | null;
    /** For an adapter that does not use the usual GATT service. */
    serviceUuid?: string | null;
    readCharacteristicUuid?: string | null;
    writeCharacteristicUuid?: string | null;
}

export interface ObdDisconnected {
    reason: string;
    transport: ObdTransport;
    adapterId: string;
}

export interface ObdMonitor {
    commands: string[];
    intervalMs: number;
}

export interface ObdMonitorReading {
    command: string;
    value: number | null;
    text: string | null;
    unit: string | null;
    /** Why the reading failed; the value is null then. */
    error: string | null;
    timestamp: string;
}

export interface ObdMonitorRequest {
    commands: string[];
    /** 250–60,000 ms; one second when null. */
    intervalMs?: number | null;
}

export interface ObdRawRequest {
    /** Such as `010C` or `AT RV`. */
    raw: string;
}

export interface ObdRawResult {
    command: string;
    response: string;
}

export interface ObdReadRequest {
    /** A name from the command list, such as `engineRpm`. */
    command: string;
}

export interface ObdReading {
    command: string;
    /** A numeric reading. */
    value: number | null;
    /** A text reading. */
    text: string | null;
    unit: string | null;
}

export interface ObdScanRequest {
    transport?: ObdTransport;
    /** Up to 30,000 ms; 5 seconds when null. */
    scanMs?: number | null;
    /** Only adapters whose name contains this; at most 64 characters. */
    nameFilter?: string | null;
}

export interface ObdStatus {
    connected: boolean;
    transport: ObdTransport | null;
    adapterId: string | null;
    adapterName: string | null;
    adapterType: ObdAdapterType | null;
    /** What the adapter reports about itself. */
    adapterIdentifier: string | null;
    /** The vehicle protocol the adapter settled on. */
    protocol: string | null;
    /** Whether Bluetooth LE adapters can be used here. */
    bluetoothSupported: boolean;
    bluetoothAccess: AccessState | null;
    scanning: boolean;
    /** The running monitor. */
    monitor: ObdMonitor | null;
}

export type ObdTransport = "Ble" | "Wifi";

/** Each list is null where the vehicle did not answer that request. */
export interface ObdTroubleCodes {
    stored: string[] | null;
    pending: string[] | null;
    permanent: string[] | null;
}

export interface ObdVin {
    vin: string;
}

/** OBD-II through one ELM327 or OBDLink adapter at a time, over Bluetooth LE or Wi-Fi: find and connect to an adapter, read values, the VIN and trouble codes, and monitor readings live. Calls that need an adapter fail with 409 when none is connected. */
export class ObdBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** The connection, the adapter, Bluetooth availability, and the running monitor. */
    getStatus(options?: { signal?: AbortSignal }): Promise<ObdStatus> {
        return call<ObdStatus>(this.transport, "GET", `obd/status`, { signal: options?.signal });
    }

    /** The named commands `read` and `startMonitor` accept. */
    getCommands(options?: { signal?: AbortSignal }): Promise<ObdCommandInfo[]> {
        return call<ObdCommandInfo[]>(this.transport, "GET", `obd/commands`, { signal: options?.signal });
    }

    /** The adapters seen during the scan window. */
    scan(request: ObdScanRequest, options?: { signal?: AbortSignal }): Promise<ObdAdapter[]> {
        return call<ObdAdapter[]>(this.transport, "POST", `obd/scan`, { json: request, signal: options?.signal });
    }

    /** The last scan's adapters. */
    getAdapters(options?: { signal?: AbortSignal }): Promise<ObdAdapter[]> {
        return call<ObdAdapter[]>(this.transport, "GET", `obd/adapters`, { signal: options?.signal });
    }

    /** Connects to an adapter — a Bluetooth peripheral, or a Wi-Fi host, probed when none is given. */
    connect(request: ObdConnectRequest, options?: { signal?: AbortSignal }): Promise<ObdStatus> {
        return call<ObdStatus>(this.transport, "POST", `obd/connection`, { json: request, signal: options?.signal });
    }

    /** Disconnects, stopping the monitor. */
    disconnect(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `obd/connection`, { signal: options?.signal });
    }

    /** Reads one named value. Fails with 404 for a command not in `getCommands`. */
    read(request: ObdReadRequest, options?: { signal?: AbortSignal }): Promise<ObdReading> {
        return call<ObdReading>(this.transport, "POST", `obd/command`, { json: request, signal: options?.signal });
    }

    /** Sends a raw request and returns the adapter's reply. Only read-only requests are accepted: OBD modes 01, 02, 03, 05, 06, 07, 09, 0A or 22 in hex, or a harmless AT command. */
    sendRaw(request: ObdRawRequest, options?: { signal?: AbortSignal }): Promise<ObdRawResult> {
        return call<ObdRawResult>(this.transport, "POST", `obd/raw`, { json: request, signal: options?.signal });
    }

    /** The vehicle identification number. */
    getVin(options?: { signal?: AbortSignal }): Promise<ObdVin> {
        return call<ObdVin>(this.transport, "GET", `obd/vin`, { signal: options?.signal });
    }

    /** Stored, pending and permanent trouble codes. */
    getTroubleCodes(options?: { signal?: AbortSignal }): Promise<ObdTroubleCodes> {
        return call<ObdTroubleCodes>(this.transport, "GET", `obd/dtc`, { signal: options?.signal });
    }

    /** Clears trouble codes. This also resets the emissions readiness monitors, which take several drive cycles to complete again, so `confirm` must be true. */
    clearTroubleCodes(confirm: boolean, options?: { signal?: AbortSignal }): Promise<ObdClearResult> {
        return call<ObdClearResult>(this.transport, "DELETE", `obd/dtc` + query({ confirm: confirm }), { signal: options?.signal });
    }

    /** Reads up to 10 named values on an interval; readings arrive through `onReading`. */
    startMonitor(request: ObdMonitorRequest, options?: { signal?: AbortSignal }): Promise<ObdMonitor> {
        return call<ObdMonitor>(this.transport, "POST", `obd/monitor`, { json: request, signal: options?.signal });
    }

    /** Stops the monitor. */
    stopMonitor(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `obd/monitor`, { signal: options?.signal });
    }

    /** A monitored reading, or the error reading it. */
    onReading(handler: (payload: ObdMonitorReading) => void): () => void {
        return this.transport.subscribe("obd.reading", json => handler(JSON.parse(json) as ObdMonitorReading));
    }

    /** The adapter went away or stopped answering. */
    onDisconnected(handler: (payload: ObdDisconnected) => void): () => void {
        return this.transport.subscribe("obd.disconnected", json => handler(JSON.parse(json) as ObdDisconnected));
    }
}
