// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Photos.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callBlob, query, segment } from "./core";
import type { AccessState, BridgeFile } from "./shared";

/** A photo in the library. */
export interface LibraryPhoto {
    /** Pass to `getThumbnail` and `export`. */
    id: string;
    createdAt: string | null;
    width: number;
    height: number;
    fileName: string | null;
}

export interface PhotoAccessResult {
    access: AccessState;
}

export interface PhotoExportRequest {
    /** The file root the photo is copied into. */
    root?: string;
}

/** A photo copied into a file root. */
export interface PhotoFile {
    /** Where it is: read it through the files bridge. */
    file: BridgeFile;
    /** The name it had on the device, where the platform says. */
    fileName: string;
    contentType: string | null;
    size: number;
}

export interface PhotoPage {
    items: LibraryPhoto[];
    offset: number;
    limit: number;
    /** Whether another page follows. */
    hasMore: boolean;
}

export interface PhotoPickRequest {
    /** How many the user may choose, 1–50. */
    limit?: number;
    /** The file root the photos are copied into. */
    root?: string;
}

export interface PhotoStatus {
    /** Whether the system photo picker is available. */
    pickerSupported: boolean;
    /** Whether the photo library can be browsed here. */
    librarySupported: boolean;
    /** Library access. `Restricted` is a limited selection the user chose on iOS or Android. */
    libraryAccess: AccessState;
}

/** Photos, two ways. The system picker needs no permission — the user chooses — and works on every head. The library is browsing every photo on the device, newest first, with thumbnails; it needs library access and is not available on Linux. Either way a photo reaches the page as a file in a file root, read through `IFilesBridge`. */
export class PhotosBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** What works here, and whether the app has library access — without prompting. */
    getStatus(options?: { signal?: AbortSignal }): Promise<PhotoStatus> {
        return call<PhotoStatus>(this.transport, "GET", `photos`, { signal: options?.signal });
    }

    /** Requests photo library access. */
    requestAccess(options?: { signal?: AbortSignal }): Promise<PhotoAccessResult> {
        return call<PhotoAccessResult>(this.transport, "POST", `photos/access`, { signal: options?.signal });
    }

    /** Shows the system photo picker and copies what the user chose into a file root. Empty when the user cancels. Not every platform enforces `limit`. */
    pick(request: PhotoPickRequest, options?: { signal?: AbortSignal }): Promise<PhotoFile[]> {
        return call<PhotoFile[]>(this.transport, "POST", `photos/pick`, { json: request, signal: options?.signal });
    }

    /** A page of the photo library, newest first. Fails with 403 without library access. */
    getLibrary(options?: { offset?: number; limit?: number; signal?: AbortSignal }): Promise<PhotoPage> {
        return call<PhotoPage>(this.transport, "GET", `photos/library` + query({ offset: options?.offset, limit: options?.limit }), { signal: options?.signal });
    }

    /** A JPEG thumbnail that fits a square of `size` pixels, 32–1024. */
    getThumbnail(id: string, options?: { size?: number; signal?: AbortSignal }): Promise<Blob> {
        return callBlob(this.transport, "GET", `photos/library/${segment(id)}/thumbnail` + query({ size: options?.size }), { signal: options?.signal });
    }

    /** Copies a library photo at full size into a file root. */
    export(id: string, request: PhotoExportRequest, options?: { signal?: AbortSignal }): Promise<PhotoFile> {
        return call<PhotoFile>(this.transport, "POST", `photos/library/${segment(id)}/export`, { json: request, signal: options?.signal });
    }
}
