// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Printers.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callBlob, callVoid } from "./core.js";
import type { AccessState } from "./shared.js";

export interface ConnectedPrinter {
    /** The Bluetooth peripheral id, or `host:port` on the network. */
    id: string;
    name: string | null;
    transport: PrinterTransport;
    language: PrinterLanguage;
    capabilities: PrinterCapabilities;
}

/** A printer a scan found. Connect with its `id`. */
export interface DiscoveredPrinter {
    /** The Bluetooth peripheral id, or `host:port` on the network. */
    id: string;
    name: string | null;
    transport: PrinterTransport;
    host: string | null;
    port: number | null;
    rssi: number | null;
    /** The known printer model a Bluetooth printer matched. */
    profile: string | null;
    /** What the printer is assumed to be. A network printer never says how wide its paper is, so it is assumed 80mm: pass `paper` when you know better. */
    capabilities: PrinterCapabilities;
}

export type PrintAlign = "Left" | "Center" | "Right";

export type PrintBarcodeFormat = "UpcA" | "UpcE" | "Ean13" | "Ean8" | "Code39" | "Itf" | "Codabar" | "Code93" | "Code128";

/** Where the barcode's human-readable text goes. */
export type PrintBarcodeText = "None" | "Above" | "Below" | "Both";

export type PrintCutMode = "Full" | "Partial";

/** How an image becomes black dots: `Threshold` for logos and line art, `FloydSteinberg` for photos. */
export type PrintDithering = "Threshold" | "FloydSteinberg";

/** One step of a receipt. In C#, `PrintElements` builds the list. */
export interface PrintElement {
    type: PrintElementType;
    text?: string | null;
    align?: PrintAlign | null;
    on?: boolean | null;
    width?: number | null;
    height?: number | null;
    lines?: number | null;
    barcode?: PrintBarcodeFormat | null;
    barcodeText?: PrintBarcodeText | null;
    moduleSize?: number | null;
    correction?: PrintQrCorrection | null;
    cut?: PrintCutMode | null;
    data?: string | null;
    dithering?: PrintDithering | null;
}

/** What a `PrintElement` does. Each reads only the fields its description names. */
export type PrintElementType = "Text" | "Line" | "Align" | "Bold" | "Underline" | "Size" | "ResetStyle" | "Feed" | "Barcode" | "QrCode" | "Image" | "Cut" | "Raw";

/** How much of a QR code can be damaged and still read: about 7, 15, 25 or 30%. */
export type PrintQrCorrection = "Low" | "Medium" | "Quartile" | "High";

/** A receipt for the connected printer. */
export interface PrintReceiptRequest {
    elements: PrintElement[];
}

export interface PrintReceiptResult {
    /** What was sent to the printer. */
    bytes: number;
}

/** A receipt to render as a PDF, for a printer that speaks no ESC/POS — an office printer through the printing bridge, or a download — on pages of `pageWidth` by `pageHeight` points. */
export interface PrintRenderRequest {
    elements: PrintElement[];
    /** The receipt width images are fitted to; the connected printer's, or 80mm, when null. */
    paper?: PrinterPaper | null;
    /** Points; A4's 595 when null. */
    pageWidth?: number | null;
    /** Points; A4's 842 when null. */
    pageHeight?: number | null;
    /** Points; 36 when null. */
    margin?: number | null;
    /** Points; 12 when null. */
    fontSize?: number | null;
}

/** What a printer can do. Lay a receipt out against these, never against a fixed width: `charactersPerLine` columns of text, and images up to `dotsPerLine` wide. */
export interface PrinterCapabilities {
    charactersPerLine: number;
    /** Columns in the smaller font. */
    charactersPerLineFontB: number;
    dpi: number;
    /** The printable width. */
    paperWidthMm: number;
    dotsPerLine: number;
    supportsImages: boolean;
    supportsCut: boolean;
    supportsQrCodes: boolean;
    supportedBarcodes: PrintBarcodeFormat[];
}

/** The printer to connect to: the `id` of a printer the last scan found, or one named outright — a Bluetooth `peripheralUuid` with its `serviceUuid` and `writeCharacteristicUuid`, or a network `host` (an IP address on the local network) and `port` (9100). */
export interface PrinterConnectRequest {
    transport?: PrinterTransport;
    id?: string | null;
    peripheralUuid?: string | null;
    serviceUuid?: string | null;
    writeCharacteristicUuid?: string | null;
    host?: string | null;
    port?: number | null;
    /** The paper width; the scanned printer's, or 80mm on the network and 58mm over Bluetooth, when null. */
    paper?: PrinterPaper | null;
    /** Everything about the printer, for one that neither preset describes. Wins over `paper`. */
    capabilities?: PrinterCapabilities | null;
    /** The scanned printer's, or ESC/POS, when null. */
    language?: PrinterLanguage | null;
    /** The label stock, for TSPL. */
    label?: PrinterLabel | null;
    /** Up to 60,000 ms; 15 seconds when null. */
    timeoutMs?: number | null;
    /** Bytes per Bluetooth write, 20–512; the connection's MTU when null. Lower it when a cheap printer garbles a long receipt. */
    chunkSize?: number | null;
    /** A pause between Bluetooth writes, 0–500 ms, to let a small buffer drain. */
    chunkDelayMs?: number | null;
}

export interface PrinterDisconnected {
    id: string;
    transport: PrinterTransport;
}

/** A label printer's stock, for `Tspl`. */
export interface PrinterLabel {
    /** 50 when null. */
    widthMm?: number | null;
    /** 30 when null. */
    heightMm?: number | null;
    /** The gap between labels; 3 when null. */
    gapMm?: number | null;
}

/** The command language the printer speaks: ESC/POS for receipt printers, TSPL for label printers. */
export type PrinterLanguage = "EscPos" | "Tspl";

/** The common receipt widths: 58mm is 32 columns and 384 dots, 80mm is 48 columns and 576 dots with a cutter. */
export type PrinterPaper = "Paper58mm" | "Paper80mm";

export interface PrinterScanRequest {
    transport?: PrinterTransport;
    /** Up to 30,000 ms; 5 seconds when null. */
    scanMs?: number | null;
}

export type PrinterTransport = "Ble" | "Network";

export interface PrintersStatus {
    /** The connected printer, if any. */
    printer: ConnectedPrinter | null;
    /** Whether Bluetooth LE printers can be used here. */
    bluetoothSupported: boolean;
    bluetoothAccess: AccessState | null;
    /** Whether network printers can be found by scanning; one can always be connected by address. */
    networkScanSupported: boolean;
    /** Whether `POST render` can turn a receipt into a PDF here. */
    renderSupported: boolean;
    scanning: boolean;
}

/** Receipt and label printers — ESC/POS or TSPL over Bluetooth LE or the network (raw TCP, port 9100), one at a time: find and connect to a printer, then print receipts built in the page. Printing fails with 409 when none is connected. For an office printer, render the same receipt to a PDF and print that through the printing bridge. */
export class PrintersBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** The connected printer, and what can be used here. */
    getStatus(options?: { signal?: AbortSignal }): Promise<PrintersStatus> {
        return call<PrintersStatus>(this.transport, "GET", `printers/status`, { signal: options?.signal });
    }

    /** The printers seen during the scan window: Bluetooth printers matching a known model, or network printers advertising over mDNS (`_pdl-datastream._tcp`, `_printer._tcp`). */
    scan(request: PrinterScanRequest, options?: { signal?: AbortSignal }): Promise<DiscoveredPrinter[]> {
        return call<DiscoveredPrinter[]>(this.transport, "POST", `printers/scan`, { json: request, signal: options?.signal });
    }

    /** Connects to a printer. Fails with 409 while another is connected. */
    connect(request: PrinterConnectRequest, options?: { signal?: AbortSignal }): Promise<ConnectedPrinter> {
        return call<ConnectedPrinter>(this.transport, "POST", `printers/connection`, { json: request, signal: options?.signal });
    }

    /** Disconnects the printer. */
    disconnect(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `printers/connection`, { signal: options?.signal });
    }

    /** Prints a receipt on the connected printer. */
    print(request: PrintReceiptRequest, options?: { signal?: AbortSignal }): Promise<PrintReceiptResult> {
        return call<PrintReceiptResult>(this.transport, "POST", `printers/print`, { json: request, signal: options?.signal });
    }

    /** Renders a receipt as a PDF. Needs no printer. */
    render(request: PrintRenderRequest, options?: { signal?: AbortSignal }): Promise<Blob> {
        return callBlob(this.transport, "POST", `printers/render`, { json: request, signal: options?.signal });
    }

    /** The printer went away. */
    onDisconnected(handler: (payload: PrinterDisconnected) => void): Promise<() => void> {
        return this.transport.subscribe("printers.disconnected", json => handler(JSON.parse(json) as PrinterDisconnected));
    }
}
