// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Printing.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callBlob, query } from "./core.js";

/** An HTML document to lay out on pages with the platform's own engine — the one printing uses — and return as a PDF. */
export interface HtmlToPdfRequest {
    /** A complete HTML document. */
    html: string;
    /** Portrait page width in points; A4's 595 when null. Letter is 612. */
    pageWidth?: number | null;
    /** Portrait page height in points; A4's 842 when null. Letter is 792. */
    pageHeight?: number | null;
    /** `Landscape` swaps width and height; anything else is portrait. */
    orientation?: PrintJobOrientation;
    /** A uniform margin in points; 36 (half an inch) when null. A CSS `@page { margin }` in the document wins on Android. */
    margin?: number | null;
}

export interface InstalledPrinter {
    /** Pass back as `printerId`. */
    id: string;
    displayName: string;
    isDefault: boolean;
}

export type PrintJobColor = "Default" | "Color" | "Monochrome";

export type PrintJobContent = "Pdf" | "Image" | "Html" | "Url";

export type PrintJobDuplex = "Default" | "OneSided" | "TwoSidedLongEdge" | "TwoSidedShortEdge";

export interface PrintJobOptions {
    /** What the print queue shows. */
    jobName?: string | null;
    /** Print without the dialog where `silent`; the dialog shows anyway elsewhere. */
    silent?: boolean;
    /** The printer for a silent job; the default printer when null. */
    printerId?: string | null;
    /** 1–99; one when null. */
    copies?: number | null;
    orientation?: PrintJobOrientation;
    duplex?: PrintJobDuplex;
    color?: PrintJobColor;
}

export type PrintJobOrientation = "Auto" | "Portrait" | "Landscape";

/** One document: `data` as base64 for a PDF or a PNG/JPEG image, `html` for markup, or `url` for an http or https page. */
export interface PrintJobRequest {
    content: PrintJobContent;
    data?: string | null;
    html?: string | null;
    url?: string | null;
    options?: PrintJobOptions | null;
}

export interface PrintJobResult {
    status: PrintJobStatus;
    printerId: string | null;
    /** Why, when `status` is failed. */
    error: string | null;
}

/** `Completed` and `Submitted` both mean it printed, or will: submitted is a job handed to a spooler whose end the platform does not report. */
export type PrintJobStatus = "Completed" | "Submitted" | "Cancelled" | "Failed";

/** What printing can do here. Feature-detect with these rather than printing to find out. */
export interface PrintingCapabilities {
    supported: boolean;
    pdf: boolean;
    image: boolean;
    html: boolean;
    /** Printing shows the platform's print dialog, where the person picks the printer. */
    systemDialog: boolean;
    /** A job with `silent` skips the dialog: Windows and CUPS (Linux, macOS). */
    silent: boolean;
    /** Installed printers can be listed and named in `printerId`. */
    listPrinters: boolean;
    /** HTML can be laid out on pages and returned as a PDF, with no print UI: iOS, Mac Catalyst and Android. */
    htmlToPdf: boolean;
}

/** The operating system's own printing — AirPrint on iOS and Mac Catalyst, the print dialog on Android, the spooler on Windows, CUPS on Linux and macOS — for any printer it knows. A receipt printer needs the printers bridge instead. */
export class PrintingBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** What printing can do here. */
    getCapabilities(options?: { signal?: AbortSignal }): Promise<PrintingCapabilities> {
        return call<PrintingCapabilities>(this.transport, "GET", `printing/capabilities`, { signal: options?.signal });
    }

    /** The installed printers; empty where they cannot be listed. */
    getPrinters(options?: { signal?: AbortSignal }): Promise<InstalledPrinter[]> {
        return call<InstalledPrinter[]>(this.transport, "GET", `printing/printers`, { signal: options?.signal });
    }

    /** Prints a document, through the print dialog unless the job is silent and the platform allows it. Answers once the dialog closes or the job is spooled; a cancelled dialog is a result, not an error. Fails with 501 for content the platform cannot print — HTML on Windows and CUPS, for one: render it to a PDF first. */
    print(request: PrintJobRequest, options?: { signal?: AbortSignal }): Promise<PrintJobResult> {
        return call<PrintJobResult>(this.transport, "POST", `printing/print`, { json: request, signal: options?.signal });
    }

    /** Lays an HTML document out on pages with the engine printing uses and returns it as a PDF, with no print UI — to save, share or attach a document. iOS, Mac Catalyst and Android; 501 elsewhere, where `htmlToPdf` is false. Capped at the JSON limit (16 MB by default). */
    htmlToPdf(request: HtmlToPdfRequest, options?: { signal?: AbortSignal }): Promise<Blob> {
        return callBlob(this.transport, "POST", `printing/html-to-pdf`, { json: request, signal: options?.signal });
    }

    /** Prints a PDF sent as the raw body, streamed to a temporary file on the device rather than held in memory — the route for a document of any size. Options travel in the query. Fails with 400 when the body is not a PDF, and with 413 past the bridge's limit (512 MB by default). */
    printPdf(pdf: Blob | ArrayBuffer | Uint8Array, options?: { jobName?: string | null; silent?: boolean; printerId?: string | null; copies?: number | null; orientation?: PrintJobOrientation; duplex?: PrintJobDuplex; color?: PrintJobColor; signal?: AbortSignal }): Promise<PrintJobResult> {
        return call<PrintJobResult>(this.transport, "POST", `printing/print/pdf` + query({ jobName: options?.jobName, silent: options?.silent, printerId: options?.printerId, copies: options?.copies, orientation: options?.orientation, duplex: options?.duplex, color: options?.color }), { body: pdf, contentType: "application/pdf", signal: options?.signal });
    }

    /** Prints a PNG or JPEG sent as the raw body, streamed to a temporary file like `printPdf`. The format is read from the bytes. */
    printImage(image: Blob | ArrayBuffer | Uint8Array, options?: { jobName?: string | null; silent?: boolean; printerId?: string | null; copies?: number | null; orientation?: PrintJobOrientation; duplex?: PrintJobDuplex; color?: PrintJobColor; signal?: AbortSignal }): Promise<PrintJobResult> {
        return call<PrintJobResult>(this.transport, "POST", `printing/print/image` + query({ jobName: options?.jobName, silent: options?.silent, printerId: options?.printerId, copies: options?.copies, orientation: options?.orientation, duplex: options?.duplex, color: options?.color }), { body: image, contentType: "application/octet-stream", signal: options?.signal });
    }
}
