// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Push.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid } from "./core.js";
import type { AccessState } from "./shared.js";

/** A push as the web app sees it. */
export interface PushPayload {
    /** The push's data fields. */
    data: Record<string, string>;
    /** The visible notification's title, when the push carried one. */
    title: string | null;
    /** The visible notification's body, when the push carried one. */
    message: string | null;
}

/** Push permission and registration. */
export interface PushStatus {
    /** Whether the app may receive pushes. */
    access: AccessState;
    /** The provider's token — what a server sends to. Null until registered. */
    token: string | null;
    /** The platform's own token (APNs, FCM) where it differs from `token`. */
    nativeToken: string | null;
}

/** The tags a device is registered with. */
export interface PushTags {
    tags: string[];
}

/** A token that was issued or unregistered. */
export interface PushTokenEvent {
    token: string;
}

/** Push notifications: registration, the token, tags, and what arrives. */
export class PushBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** The permission state and the current tokens, without prompting. */
    getStatus(options?: { signal?: AbortSignal }): Promise<PushStatus> {
        return call<PushStatus>(this.transport, "GET", `push`, { signal: options?.signal });
    }

    /** Requests permission if it has not been decided, then registers with the push provider. */
    register(options?: { signal?: AbortSignal }): Promise<PushStatus> {
        return call<PushStatus>(this.transport, "POST", `push/registration`, { signal: options?.signal });
    }

    /** Unregisters from the push provider. */
    unregister(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `push/registration`, { signal: options?.signal });
    }

    /** The tags the device is registered with. Fails with 501 where the provider has no tags. */
    getTags(options?: { signal?: AbortSignal }): Promise<PushTags> {
        return call<PushTags>(this.transport, "GET", `push/tags`, { signal: options?.signal });
    }

    /** Replaces the device's tags. Fails with 501 where the provider has no tags, 409 when it refuses them. */
    setTags(tags: PushTags, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "PUT", `push/tags`, { json: tags, signal: options?.signal });
    }

    /** The provider issued a new token. */
    onToken(handler: (payload: PushTokenEvent) => void): () => void {
        return this.transport.subscribe("push.token", json => handler(JSON.parse(json) as PushTokenEvent));
    }

    /** The device was unregistered. */
    onUnregistered(handler: (payload: PushTokenEvent) => void): () => void {
        return this.transport.subscribe("push.unregistered", json => handler(JSON.parse(json) as PushTokenEvent));
    }

    /** A push arrived. Raised only when the app hands pushes to the web app. */
    onReceived(handler: (payload: PushPayload) => void): () => void {
        return this.transport.subscribe("push.received", json => handler(JSON.parse(json) as PushPayload));
    }

    /** The user opened the app from a push. Raised only when the app hands pushes to the web app. */
    onEntry(handler: (payload: PushPayload) => void): () => void {
        return this.transport.subscribe("push.entry", json => handler(JSON.parse(json) as PushPayload));
    }
}
