// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.RpiCamera.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callBlob, callVoid, query } from "./core.js";
import type { FileEntry } from "./shared.js";

/** A photograph to take and write into a file root. */
export interface RpiCameraCapture {
    /** The file root, as the files bridge names it. */
    root: string;
    /** Where in the root. An existing file is replaced. */
    path: string;
    /** Null takes the first camera. */
    cameraId?: string | null;
    /** Zero takes the bridge's still size. */
    width?: number;
    height?: number;
    /** JPEG quality, 1 to 100; zero takes the bridge's still quality. */
    quality?: number;
}

/** A sensor control. Which ones exist depends on the module: a Camera Module 3 has autofocus, a v2 doesn't. */
export type RpiCameraControl = "AutoExposure" | "ExposureTime" | "AnalogueGain" | "AutoWhiteBalance" | "WhiteBalanceMode" | "Brightness" | "Contrast" | "Saturation" | "Sharpness" | "ExposureValue" | "FrameDurationMin" | "FrameDurationMax" | "AutoFocusMode" | "LensPosition" | "NoiseReduction";

export interface RpiCameraControlInfo {
    control: RpiCameraControl;
    /** False when the attached sensor doesn't have the control. */
    supported: boolean;
    minimum: number;
    maximum: number;
    default: number;
    /** The value the bridge applies to every session it opens; null when it leaves the sensor's own. */
    value: number | null;
}

export interface RpiCameraControlValue {
    control: RpiCameraControl;
    /** Null goes back to the sensor's own value from the next session. */
    value: number | null;
}

/** Control values to apply now, to a running stream, and to every session opened later. */
export interface RpiCameraControlsInput {
    values: RpiCameraControlValue[];
}

/** A camera attached to the device. */
export interface RpiCameraInfo {
    /** Stable across reboots, but not across a move to another CSI port. */
    id: string;
    /** The sensor, such as `imx708`; empty when it doesn't say. */
    model: string;
    /** The full width of the sensor's pixel array. */
    maxWidth: number;
    maxHeight: number;
    /** How the sensor is mounted. */
    rotationDegrees: number;
    location: RpiCameraLocation;
}

export type RpiCameraLocation = "External" | "Front" | "Back";

/** What the camera can do here. */
export interface RpiCameraStatus {
    /** False off Linux, without libcamera, or with the native shim missing — `backend` says which. */
    supported: boolean;
    /** The backend and the libcamera it was built against, or why there is none. */
    backend: string;
    /** Every camera attached. Empty isn't an error: a badly seated ribbon cable looks like this. */
    cameras: RpiCameraInfo[];
    /** Streams running now. */
    streams: RpiCameraStream[];
}

/** A live stream, shared by everyone watching it. */
export interface RpiCameraStream {
    cameraId: string;
    /** What the camera actually delivers, which may differ from what was asked for. */
    width: number;
    height: number;
    /** The sensor's format as a FourCC, such as `NV12`; frames are encoded to JPEG from it. */
    pixelFormat: string;
    quality: number;
    maxFps: number;
    /** Open `stream` responses. */
    viewers: number;
    framesDelivered: number;
    /** Frames the camera produced faster than they could be sent. */
    framesDropped: number;
}

/**
 * A Raspberry Pi camera through libcamera: the cameras attached, JPEG snapshots, photographs written into a file root, and sensor controls. Linux with libcamera only; everywhere else fails with 501.
 *
 * The live feed is `GET {bridge}/rpicamera/stream` — a `multipart/x-mixed-replace` MJPEG stream an `<img>` plays directly, with `camera`, `width`, `height`, `quality` and `fps` in the query. Everyone watching a camera shares one stream, so the first viewer decides its size.
 */
export class RpiCameraBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** Whether a camera backend loaded, the cameras attached, and the streams running. */
    getStatus(options?: { signal?: AbortSignal }): Promise<RpiCameraStatus> {
        return call<RpiCameraStatus>(this.transport, "GET", `rpicamera`, { signal: options?.signal });
    }

    /** A JPEG from the camera. Taken from the running stream when there is one, otherwise from a session opened for the photograph. Fails with 404 for an unknown camera and 409 while another process holds the camera. */
    snapshot(options?: { camera?: string | null; width?: number; height?: number; quality?: number; signal?: AbortSignal }): Promise<Blob> {
        return callBlob(this.transport, "GET", `rpicamera/snapshot` + query({ camera: options?.camera, width: options?.width, height: options?.height, quality: options?.quality }), { signal: options?.signal });
    }

    /** Takes a photograph and writes it into a file root, where the page, a transfer or a share can pick it up. */
    capture(capture: RpiCameraCapture, options?: { signal?: AbortSignal }): Promise<FileEntry> {
        return call<FileEntry>(this.transport, "POST", `rpicamera/capture`, { json: capture, signal: options?.signal });
    }

    /** Every control, what the sensor accepts, and the value the bridge applies. */
    getControls(options?: { camera?: string | null; signal?: AbortSignal }): Promise<RpiCameraControlInfo[]> {
        return call<RpiCameraControlInfo[]>(this.transport, "GET", `rpicamera/controls` + query({ camera: options?.camera }), { signal: options?.signal });
    }

    /** Sets controls on a running stream and on every session opened later. Fails with 400 naming a control the sensor lacks. */
    setControls(controls: RpiCameraControlsInput, options?: { camera?: string | null; signal?: AbortSignal }): Promise<RpiCameraControlInfo[]> {
        return call<RpiCameraControlInfo[]>(this.transport, "PUT", `rpicamera/controls` + query({ camera: options?.camera }), { json: controls, signal: options?.signal });
    }

    /** Ends every stream, closing each viewer's response and releasing the cameras. */
    stopStreams(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `rpicamera/streams`, { signal: options?.signal });
    }
}
