// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.ScreenRecorder.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid } from "./core.js";
import type { AccessState, BridgeFile } from "./shared.js";

/** Which audio to ask for along with the screen. Only the microphone has a permission of its own. */
export interface ScreenRecorderAccessRequest {
    includeMicrophone?: boolean;
    includeSystemAudio?: boolean;
}

export interface ScreenRecorderAccessResult {
    /** Where recording stands after asking. Android cannot grant the screen ahead of time, so it reports `Unknown` there and asks when a recording starts: anything but `Denied` is worth trying. */
    access: AccessState;
}

/** What this device's recorder can do. A request that asks for something missing here answers 501 rather than recording without it. */
export type ScreenRecorderCapability = "Recording" | "PauseResume" | "Microphone" | "SystemAudio" | "CursorToggle" | "FrameRateControl" | "BitrateControl" | "Downscaling";

/** Where the recorder is. */
export type ScreenRecorderState = "Idle" | "Starting" | "Recording" | "Paused" | "Stopping";

/** The recorder as it is right now. */
export interface ScreenRecorderStatus {
    /** Whether this device can record its screen at all. */
    supported: boolean;
    /** What it can do. */
    capabilities: ScreenRecorderCapability[];
    /** Where it is. */
    state: ScreenRecorderState;
    /** How much has been recorded, without any paused span. Null when nothing is recording. */
    elapsedSeconds: number | null;
    /** The longest a recording may run on this device; a longer request is shortened to it. */
    maxDurationSeconds: number | null;
    /** The most recent recording the bridge filed. */
    lastRecording: ScreenRecording | null;
}

/** A recording, filed into a file root and read through the files bridge. */
export interface ScreenRecording {
    /** Where it was filed. */
    file: BridgeFile;
    /** Bytes. */
    size: number;
    /** Encoded width in pixels. */
    width: number;
    /** Encoded height in pixels. */
    height: number;
    /** How long it runs, without any paused span. */
    durationSeconds: number;
    /** What was written — `video/mp4` on every native platform. */
    mimeType: string;
}

/** Why a recording ended. */
export type ScreenRecordingEndReason = "Unknown" | "Stopped" | "Cancelled" | "MaxDurationReached" | "RevokedByUser" | "InterruptedBySystem" | "TargetLost" | "EncoderFailed";

/** A recording ended — stopped, cancelled, or ended by the device. */
export interface ScreenRecordingEnded {
    /** Why. */
    reason: ScreenRecordingEndReason;
    /** The recording, when there was one to file. */
    recording: ScreenRecording | null;
    /** What went wrong, when something did. */
    message: string | null;
}

/** What to record. Every setting but the audio is optional, and each one needs its `ScreenRecorderCapability`: a request for something this device cannot do answers 501. */
export interface ScreenRecordingRequest {
    /** Mix in the microphone. Needs `Microphone`. */
    includeMicrophone?: boolean;
    /** Capture what the device is playing. Needs `SystemAudio`. */
    includeSystemAudio?: boolean;
    /** Draw the pointer. Null or true draws it; false needs `CursorToggle`. */
    showCursor?: boolean | null;
    /** A ceiling, 1–240. Needs `FrameRateControl`. */
    frameRate?: number | null;
    /** Bits a second. Needs `BitrateControl`. */
    videoBitrate?: number | null;
    /** Downscale to at most this many pixels wide. Needs `Downscaling`. */
    maxWidth?: number | null;
    /** Stop and file it after this long. Never longer than `maxDurationSeconds`, which also applies when this is null. */
    maxDurationSeconds?: number | null;
}

/**
 * Records the device's screen to a video filed into a file root. Not the screen of the machine showing the page — in a browser that is `getDisplayMedia`, which the embedded WebViews on iOS and Android do not offer.
 *
 * What ends up in the file differs by platform. Android, macOS, Windows and Linux record the whole screen, other apps included; iOS and Mac Catalyst record only this app. Every platform but Windows asks the user first — a consent dialog, a system permission or the compositor's picker — so `start` can take as long as the user takes to answer.
 *
 * One recording at a time: a second start answers 409 (`recording_busy`), and a stop, pause or resume with nothing recording answers 409 (`not_recording`). A setting the device cannot honour answers 501, as does a device that cannot record at all; a declined consent answers 403 (`permission_denied`). The device can end a recording on its own, so listen to `onEnded` rather than assuming a stop will find one running.
 */
export class ScreenRecorderBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** What the recorder can do and where it is, without prompting. */
    getStatus(options?: { signal?: AbortSignal }): Promise<ScreenRecorderStatus> {
        return call<ScreenRecorderStatus>(this.transport, "GET", `screenrecorder`, { signal: options?.signal });
    }

    /** Asks for what recording needs, where the platform lets it be asked ahead of time. */
    requestAccess(request: ScreenRecorderAccessRequest, options?: { signal?: AbortSignal }): Promise<ScreenRecorderAccessResult> {
        return call<ScreenRecorderAccessResult>(this.transport, "POST", `screenrecorder/access`, { json: request, signal: options?.signal });
    }

    /** Starts recording and answers once frames are being written — after any consent the platform asks for — with the state it is in. */
    start(request: ScreenRecordingRequest, options?: { signal?: AbortSignal }): Promise<ScreenRecorderStatus> {
        return call<ScreenRecorderStatus>(this.transport, "POST", `screenrecorder/recording`, { json: request, signal: options?.signal });
    }

    /** Stops recording, finishes the file and files it. Finishing takes a moment on a long recording. */
    stop(options?: { signal?: AbortSignal }): Promise<ScreenRecording> {
        return call<ScreenRecording>(this.transport, "DELETE", `screenrecorder/recording`, { signal: options?.signal });
    }

    /** Ends the recording and keeps nothing. */
    cancel(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `screenrecorder/recording/cancel`, { signal: options?.signal });
    }

    /** Stops writing frames without ending the recording. Needs `PauseResume`. */
    pause(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `screenrecorder/recording/pause`, { signal: options?.signal });
    }

    /** Carries on after `pause`. */
    resume(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `screenrecorder/recording/resume`, { signal: options?.signal });
    }

    /** The recorder changed state — starting, recording, paused, stopping, idle. Raised with the whole status. */
    onStatus(handler: (payload: ScreenRecorderStatus) => void): Promise<() => void> {
        return this.transport.subscribe("screenrecorder.status", json => handler(JSON.parse(json) as ScreenRecorderStatus));
    }

    /** A recording ended, however it ended, with the recording when one was filed. */
    onEnded(handler: (payload: ScreenRecordingEnded) => void): Promise<() => void> {
        return this.transport.subscribe("screenrecorder.ended", json => handler(JSON.parse(json) as ScreenRecordingEnded));
    }
}
