// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callBlob, callVoid, query, segment } from "./core.js";

/** Where a permission stands. Reported by every bridge that needs one; the names match Shiny's own. */
export type AccessState = "Unknown" | "NotSupported" | "NotSetup" | "Disabled" | "Restricted" | "Denied" | "Available";

/** A link the app was opened with. */
export interface AppLink {
    /** The link as the OS delivered it. */
    url: string;
    /** The page route it maps to — always a local path, safe to navigate to as it is. */
    route: string;
    /** When the app received it. */
    receivedAt: string;
}

/** The outcome of applying an update. */
export interface ApplyUpdateResult {
    /** False when nothing was waiting. */
    applied: boolean;
    /** The version now being served, when one was applied. */
    version: string | null;
}

/** A registered bridge. */
export interface BridgeCapability {
    /** Its path under the bridge prefix — `calendar` for `/_bridge/calendar`. */
    name: string;
    /** False where the platform has no implementation; its endpoints then answer 501. */
    isSupported: boolean;
}

/** A file the page can reach through the files bridge: a named root and a path inside it. Bridges that take or return a file use this, so nothing reaches the page that `/_bridge/files` would not also serve. */
export interface BridgeFile {
    root: string;
    path: string;
}

/** A file or directory. */
export interface FileEntry {
    /** The entry's name; the root's name for the root itself. */
    name: string;
    /** Relative to the root, with forward slashes. Empty for the root. */
    path: string;
    /** Whether it is a directory. */
    isDirectory: boolean;
    /** Bytes, for files. */
    size: number | null;
    /** When it last changed. */
    modified: string;
}

export type FileRootChange = "Added" | "Replaced" | "Removed";

/** The `files.roots` event. */
export interface FileRootsChanged {
    /** The root's name. */
    root: string;
    /** What happened to it. */
    change: FileRootChange;
}

/** A move or copy within a root. */
export interface FileTransfer {
    /** The entry to move or copy. */
    from: string;
    /** Where it goes, including its new name. */
    to: string;
    /** Replace an existing file at `to`. Directories are never merged or replaced. */
    overwrite?: boolean;
}

/** What is serving the page. */
export interface HostInfo {
    /** The app's id, as the update server knows it. */
    appId: string;
    /** The native app's version. */
    hostVersion: string;
    /** android, ios, maccatalyst, macos, windows or linux. */
    platform: string;
    /** The web app build being served; null while pages come from a dev server. */
    webAppVersion: string | null;
    /** Whether that build is the baseline or a download. */
    webAppOrigin: WebAppOrigin | null;
    /** A downloaded update waiting for `applyUpdate`. */
    pendingVersion: string | null;
    /** Every registered bridge. */
    bridges: BridgeCapability[];
    /** The dev server pages are proxied from, in a debug build that uses one. */
    devServer: string | null;
}

/** The keys in a scope. */
export interface SettingsList {
    /** The scope listed. */
    scope: SettingsScope;
    /** Whether values in this scope are encrypted at rest on this device. */
    encrypted: boolean;
    /** The keys this web app has set, in ordinal order. */
    keys: string[];
}

/** Which store a setting lives in. */
export type SettingsScope = "Local" | "Secure";

/** Where the web app being served came from. */
export type WebAppOrigin = "Baseline" | "Installed";

/** The page's own files, confined to named roots the app configured — `data` and `cache` by default. Paths are relative to the root and use `/`. Parent directories are created as needed, and a write that fails leaves no partial file behind. */
export class FilesBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** The names of the roots the page can use. */
    getRoots(options?: { signal?: AbortSignal }): Promise<string[]> {
        return call<string[]>(this.transport, "GET", `files`, { signal: options?.signal });
    }

    /** A directory's entries, directories first. Fails with 404 when it does not exist. */
    list(root: string, options?: { path?: string; signal?: AbortSignal }): Promise<FileEntry[]> {
        return call<FileEntry[]>(this.transport, "GET", `files/${segment(root)}/list` + query({ path: options?.path }), { signal: options?.signal });
    }

    /** One file or directory. Fails with 404 when it does not exist. */
    getInfo(root: string, path: string, options?: { signal?: AbortSignal }): Promise<FileEntry> {
        return call<FileEntry>(this.transport, "GET", `files/${segment(root)}/info` + query({ path: path }), { signal: options?.signal });
    }

    /** A file's content as a stream. Fails with 404 when it does not exist. */
    openRead(root: string, path: string, options?: { signal?: AbortSignal }): Promise<Blob> {
        return callBlob(this.transport, "GET", `files/${segment(root)}/content` + query({ path: path }), { signal: options?.signal });
    }

    /** A file's content. Fails with 404 when it does not exist. */
    readBytes(root: string, path: string, options?: { signal?: AbortSignal }): Promise<Blob> {
        return callBlob(this.transport, "GET", `files/${segment(root)}/content` + query({ path: path }), { signal: options?.signal });
    }

    /** Writes a file from a stream. With `overwrite` false, fails with 409 when it exists. */
    write(root: string, path: string, content: Blob | ArrayBuffer | Uint8Array, options?: { overwrite?: boolean; signal?: AbortSignal }): Promise<FileEntry> {
        return call<FileEntry>(this.transport, "PUT", `files/${segment(root)}/content` + query({ path: path, overwrite: options?.overwrite }), { body: content, contentType: "application/octet-stream", signal: options?.signal });
    }

    /** Writes a file. With `overwrite` false, fails with 409 when it exists. */
    writeBytes(root: string, path: string, content: Blob | ArrayBuffer | Uint8Array, options?: { overwrite?: boolean; signal?: AbortSignal }): Promise<FileEntry> {
        return call<FileEntry>(this.transport, "PUT", `files/${segment(root)}/content` + query({ path: path, overwrite: options?.overwrite }), { body: content, contentType: "application/octet-stream", signal: options?.signal });
    }

    /** Writes a UTF-8 text file. With `overwrite` false, fails with 409 when it exists. */
    writeText(root: string, path: string, text: string, options?: { overwrite?: boolean; signal?: AbortSignal }): Promise<FileEntry> {
        return call<FileEntry>(this.transport, "PUT", `files/${segment(root)}/content` + query({ path: path, overwrite: options?.overwrite }), { body: text, contentType: "text/plain; charset=utf-8", signal: options?.signal });
    }

    /** Appends UTF-8 text to a file, creating it if needed. */
    appendText(root: string, path: string, text: string, options?: { signal?: AbortSignal }): Promise<FileEntry> {
        return call<FileEntry>(this.transport, "POST", `files/${segment(root)}/append` + query({ path: path }), { body: text, contentType: "text/plain; charset=utf-8", signal: options?.signal });
    }

    /** Appends bytes to a file, creating it if needed. */
    appendBytes(root: string, path: string, content: Blob | ArrayBuffer | Uint8Array, options?: { signal?: AbortSignal }): Promise<FileEntry> {
        return call<FileEntry>(this.transport, "POST", `files/${segment(root)}/append` + query({ path: path }), { body: content, contentType: "application/octet-stream", signal: options?.signal });
    }

    /** Creates a directory and its parents. */
    createDirectory(root: string, path: string, options?: { signal?: AbortSignal }): Promise<FileEntry> {
        return call<FileEntry>(this.transport, "POST", `files/${segment(root)}/directory` + query({ path: path }), { signal: options?.signal });
    }

    /** Deletes a file or a directory. A directory that is not empty fails with 409 unless `recursive`. */
    delete(root: string, path: string, options?: { recursive?: boolean; signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `files/${segment(root)}/entry` + query({ path: path, recursive: options?.recursive }), { signal: options?.signal });
    }

    /** Moves or renames a file or directory within a root. */
    move(root: string, transfer: FileTransfer, options?: { signal?: AbortSignal }): Promise<FileEntry> {
        return call<FileEntry>(this.transport, "POST", `files/${segment(root)}/move`, { json: transfer, signal: options?.signal });
    }

    /** Copies a file, or a directory recursively, within a root. */
    copy(root: string, transfer: FileTransfer, options?: { signal?: AbortSignal }): Promise<FileEntry> {
        return call<FileEntry>(this.transport, "POST", `files/${segment(root)}/copy`, { json: transfer, signal: options?.signal });
    }

    /** A root was added, replaced or removed while the app ran — a folder the user picked or the app mapped, a share it published. Call `getRoots` again, and drop anything listed from a root that was replaced or removed. */
    onRootsChanged(handler: (payload: FileRootsChanged) => void): () => void {
        return this.transport.subscribe("files.roots", json => handler(JSON.parse(json) as FileRootsChanged));
    }
}

/** The host itself: what is serving the page, which bridges it has, and a pending web app update. */
export class HostBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** The app, the web app build being served, and every registered bridge with whether it works here. */
    getInfo(options?: { signal?: AbortSignal }): Promise<HostInfo> {
        return call<HostInfo>(this.transport, "GET", `host`, { signal: options?.signal });
    }

    /** Switches to a downloaded update, if one is waiting. The page reloads itself afterwards; the host never reloads it out from under the user. */
    applyUpdate(options?: { signal?: AbortSignal }): Promise<ApplyUpdateResult> {
        return call<ApplyUpdateResult>(this.transport, "POST", `host/apply-update`, { signal: options?.signal });
    }
}

/** Deep links and universal links. A link arrives as an event while the page is open, and waits as the pending link otherwise — so a page reads the pending link once it boots, and listens after. */
export class LinksBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** The latest link, left in place. Null when there is none. */
    getPending(options?: { signal?: AbortSignal }): Promise<AppLink | null> {
        return call<AppLink | null>(this.transport, "GET", `links/pending`, { signal: options?.signal });
    }

    /** The latest link, taken off the host so it is acted on once. Null when there is none. */
    consume(options?: { signal?: AbortSignal }): Promise<AppLink | null> {
        return call<AppLink | null>(this.transport, "DELETE", `links/pending`, { signal: options?.signal });
    }

    /** A link arrived while the page is open. It is also left pending until consumed. */
    onLink(handler: (payload: AppLink) => void): () => void {
        return this.transport.subscribe("app.link", json => handler(JSON.parse(json) as AppLink));
    }
}

/** Key/value settings in the platform's stores. Values are any JSON; keys are 1–128 letters, digits, `.`, `_`, `-` or `:`. The typed `getAsync``1` and `setAsync``1` are what a page normally calls. */
export class SettingsBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** The keys this web app has set in a scope, and whether the scope is encrypted at rest. */
    list(scope: SettingsScope, options?: { signal?: AbortSignal }): Promise<SettingsList> {
        return call<SettingsList>(this.transport, "GET", `settings/${segment(scope)}`, { signal: options?.signal });
    }

    /** Removes every key this web app set in a scope, and nothing the native app set. */
    clear(scope: SettingsScope, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `settings/${segment(scope)}`, { signal: options?.signal });
    }

    /** A value exactly as it was written. Fails with 404 when the key is not set. */
    getValue(scope: SettingsScope, key: string, options?: { signal?: AbortSignal }): Promise<unknown> {
        return call<unknown>(this.transport, "GET", `settings/${segment(scope)}/${segment(key)}`, { signal: options?.signal });
    }

    /** Sets a key to any JSON value, at most 1 MB. */
    setValue(scope: SettingsScope, key: string, value: unknown, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "PUT", `settings/${segment(scope)}/${segment(key)}`, { json: value, signal: options?.signal });
    }

    /** Removes a key. Fails with 404 when it is not set. */
    remove(scope: SettingsScope, key: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `settings/${segment(scope)}/${segment(key)}`, { signal: options?.signal });
    }
}
