// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Speech.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid, query } from "./core.js";
import type { AccessState } from "./shared.js";

export interface RecognizeRequest {
    /** A culture name such as `en-US`; the device's when null. */
    culture?: string | null;
    /** How much quiet ends it, 500–10,000 ms. */
    silenceTimeoutMs?: number | null;
    /** The longest it waits in all, 1,000–60,000 ms; 15 seconds when null. */
    timeoutMs?: number | null;
    /** Keep audio on the device where the platform allows. */
    preferOnDevice?: boolean | null;
    /** At most 32, each at most 64 characters. */
    keywords?: string[] | null;
}

export interface RecognizeResult {
    /** What was heard; null when nothing was. */
    text: string | null;
}

export interface SpeakRequest {
    /** At most 4,000 characters. */
    text: string;
    /** A culture name such as `en-US`. */
    culture?: string | null;
    /** A voice's `id`. */
    voice?: string | null;
    /** 0.5–2. */
    pitch?: number | null;
    /** 0.25–4. */
    rate?: number | null;
    /** 0–1. */
    volume?: number | null;
    /** Return once speech ends rather than straight away. */
    wait?: boolean;
}

export interface SpeakResult {
    /** False when it was interrupted. */
    completed: boolean;
}

export interface SpeechAccessResult {
    access: AccessState;
}

/** Why dictation ended. */
export type SpeechEndReason = "Stopped" | "PageClosed" | "Error";

export interface SpeechEnded {
    reason: SpeechEndReason;
}

export interface SpeechError {
    source: SpeechErrorSource;
    message: string;
}

export type SpeechErrorSource = "Recognition" | "Synthesis";

export interface SpeechKeyword {
    keyword: string;
}

export interface SpeechListener {
    culture: string | null;
    keywords: string[] | null;
}

export interface SpeechListenerRequest {
    /** A culture name such as `en-US`; the device's when null. */
    culture?: string | null;
    /** How much quiet ends a phrase, 500–10,000 ms. */
    silenceTimeoutMs?: number | null;
    /** Keep audio on the device where the platform allows. */
    preferOnDevice?: boolean | null;
    /** Words that raise `onKeyword`. At most 32, each at most 64 characters. */
    keywords?: string[] | null;
}

export interface SpeechRecognized {
    text: string;
    /** 0–1, where the platform reports one. */
    confidence: number | null;
}

export interface SpeechStatus {
    recognitionSupported: boolean;
    synthesisSupported: boolean;
    listening: boolean;
    recognizing: boolean;
    speaking: boolean;
}

export interface SpeechVoice {
    id: string;
    name: string;
    culture: string | null;
}

/** On-device speech recognition and text-to-speech. Linux has no OS speech engine, so every call there fails with 501. There is one microphone: a one-shot recognition and dictation exclude each other, and whichever comes second fails with 409 `microphone_busy`. */
export class SpeechBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** What is supported, and whether the microphone or the speaker is in use. */
    getStatus(options?: { signal?: AbortSignal }): Promise<SpeechStatus> {
        return call<SpeechStatus>(this.transport, "GET", `speech/status`, { signal: options?.signal });
    }

    /** Requests microphone and speech recognition permission. */
    requestAccess(options?: { signal?: AbortSignal }): Promise<SpeechAccessResult> {
        return call<SpeechAccessResult>(this.transport, "POST", `speech/access`, { signal: options?.signal });
    }

    /** Listens until the speaker goes quiet and returns what was heard. `text` is null when nothing was heard before the timeout. */
    recognize(request: RecognizeRequest, options?: { signal?: AbortSignal }): Promise<RecognizeResult> {
        return call<RecognizeResult>(this.transport, "POST", `speech/recognize`, { json: request, signal: options?.signal });
    }

    /** The running dictation, or null when there is none. */
    getListener(options?: { signal?: AbortSignal }): Promise<SpeechListener | null> {
        return call<SpeechListener | null>(this.transport, "GET", `speech/listener`, { signal: options?.signal });
    }

    /** Starts dictation. Results arrive through `onPartial`, `onResult` and `onKeyword`, so listen first: without a listener for `onPartial` or `onResult` it fails with 409. It ends when stopped or once neither has a listener left. */
    startListener(request: SpeechListenerRequest, options?: { signal?: AbortSignal }): Promise<SpeechListener> {
        return call<SpeechListener>(this.transport, "POST", `speech/listener`, { json: request, signal: options?.signal });
    }

    /** Stops dictation. */
    stopListener(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `speech/listener`, { signal: options?.signal });
    }

    /** Speaks text, interrupting anything already being spoken. With `wait` it returns once speech ends; without, it returns null straight away and `onSpoken` says when it ended. */
    speak(request: SpeakRequest, options?: { signal?: AbortSignal }): Promise<SpeakResult | null> {
        return call<SpeakResult | null>(this.transport, "POST", `speech/speak`, { json: request, signal: options?.signal });
    }

    /** Stops speaking. */
    stopSpeaking(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `speech/speak`, { signal: options?.signal });
    }

    /** The voices installed, optionally for one culture such as `en-US`. */
    getVoices(options?: { culture?: string | null; signal?: AbortSignal }): Promise<SpeechVoice[]> {
        return call<SpeechVoice[]>(this.transport, "GET", `speech/voices` + query({ culture: options?.culture }), { signal: options?.signal });
    }

    /** The cultures voices exist for. */
    getCultures(options?: { signal?: AbortSignal }): Promise<string[]> {
        return call<string[]>(this.transport, "GET", `speech/cultures`, { signal: options?.signal });
    }

    /** Dictation's best guess so far, replaced as the speaker goes on. */
    onPartial(handler: (payload: SpeechRecognized) => void): Promise<() => void> {
        return this.transport.subscribe("speech.partial", json => handler(JSON.parse(json) as SpeechRecognized));
    }

    /** A finished phrase from dictation. */
    onResult(handler: (payload: SpeechRecognized) => void): Promise<() => void> {
        return this.transport.subscribe("speech.result", json => handler(JSON.parse(json) as SpeechRecognized));
    }

    /** One of the dictation's keywords was heard. */
    onKeyword(handler: (payload: SpeechKeyword) => void): Promise<() => void> {
        return this.transport.subscribe("speech.keyword", json => handler(JSON.parse(json) as SpeechKeyword));
    }

    /** Dictation ended. */
    onEnded(handler: (payload: SpeechEnded) => void): Promise<() => void> {
        return this.transport.subscribe("speech.ended", json => handler(JSON.parse(json) as SpeechEnded));
    }

    /** An utterance finished or was interrupted. */
    onSpoken(handler: (payload: SpeakResult) => void): Promise<() => void> {
        return this.transport.subscribe("speech.spoken", json => handler(JSON.parse(json) as SpeakResult));
    }

    /** Recognition or synthesis failed. */
    onError(handler: (payload: SpeechError) => void): Promise<() => void> {
        return this.transport.subscribe("speech.error", json => handler(JSON.parse(json) as SpeechError));
    }
}
