// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.TrayIcon.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid, segment } from "./core";

export interface TrayAnimation {
    /** 2–24 images. */
    frames?: TrayImage[] | null;
    /** Time per frame; at least 50 ms. */
    intervalMs?: number;
}

export interface TrayClick {
    /** The icon clicked. */
    id: string;
    button: TrayClickButton;
    /** Screen coordinates, where the platform reports them. */
    x: number;
    y: number;
}

export type TrayClickButton = "Primary" | "Secondary" | "Double";

export interface TrayIconInfo {
    id: string;
    tooltip: string | null;
    title: string | null;
    visible: boolean;
    templateImage: boolean;
    badge: string | null;
    hasIcon: boolean;
    animating: boolean;
    menu: TrayMenuItemInfo[];
}

/** An icon to create, or the changes to one. Properties left null are left as they are. */
export interface TrayIconInput {
    id?: string | null;
    tooltip?: string | null;
    title?: string | null;
    visible?: boolean | null;
    /** On macOS, let the menu bar tint the icon; use black with alpha. */
    templateImage?: boolean | null;
    /** A short count or label drawn over the icon. */
    badge?: string | null;
    icon?: TrayImage | null;
    menu?: TrayMenuInput | null;
}

/** An image: a file the page could already read through the files bridge (`root` and `path`), or base64 bytes it built itself (`data`, with or without a `data:` URI prefix). */
export interface TrayImage {
    root?: string | null;
    path?: string | null;
    data?: string | null;
}

/** A menu: at most 64 entries in all, nested at most 4 deep. */
export interface TrayMenuInput {
    items?: TrayMenuItemInput[] | null;
}

export interface TrayMenuItemInfo {
    id: string;
    type: TrayMenuItemType;
    label: string | null;
    enabled: boolean;
    visible: boolean;
    /** Null for anything but a check item. */
    checked: boolean | null;
    items: TrayMenuItemInfo[] | null;
}

/** One menu entry. */
export interface TrayMenuItemInput {
    /** What comes back on `tray.menu`; assigned when null. */
    id?: string | null;
    type?: TrayMenuItemType;
    label?: string | null;
    /** A shortcut such as `Ctrl+S`. */
    accelerator?: string | null;
    enabled?: boolean;
    visible?: boolean;
    checked?: boolean;
    icon?: TrayImage | null;
    /** A submenu's entries. */
    items?: TrayMenuItemInput[] | null;
}

export type TrayMenuItemType = "Item" | "Check" | "Separator" | "Submenu";

export interface TrayMenuSelection {
    /** The icon whose menu it was. */
    id: string;
    itemId: string;
    label: string | null;
    /** The new state of a check item; null for anything else. */
    checked: boolean | null;
}

export interface TrayNotification {
    title?: string | null;
    message?: string | null;
}

export interface TrayStatus {
    supported: boolean;
    maxIcons: number;
    icons: TrayIconInfo[];
}

/** System tray and menu bar icons on Windows, macOS and Linux: create and update them, give them menus, show notifications, animate them, and hear clicks and menu choices. Android and iOS fail with 501. Ids are 1–64 letters, digits, `.`, `_` or `-`. */
export class TrayBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** Whether tray icons are supported here, the limit, and the icons this page created. */
    getStatus(options?: { signal?: AbortSignal }): Promise<TrayStatus> {
        return call<TrayStatus>(this.transport, "GET", `tray`, { signal: options?.signal });
    }

    /** Creates an icon, assigning an id when `id` is null. Fails with 429 past the limit. */
    create(icon: TrayIconInput, options?: { signal?: AbortSignal }): Promise<TrayIconInfo> {
        return call<TrayIconInfo>(this.transport, "POST", `tray`, { json: icon, signal: options?.signal });
    }

    /** Removes every icon. */
    removeAll(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `tray`, { signal: options?.signal });
    }

    /** One icon. Fails with 404 when there is no such icon. */
    get(id: string, options?: { signal?: AbortSignal }): Promise<TrayIconInfo> {
        return call<TrayIconInfo>(this.transport, "GET", `tray/${segment(id)}`, { signal: options?.signal });
    }

    /** Creates the icon, or updates it: only properties that are set change, and an empty string clears `tooltip`, `title` or `badge`. PUT by a fixed id lets a reloaded page adopt its icon rather than add another. */
    put(id: string, icon: TrayIconInput, options?: { signal?: AbortSignal }): Promise<TrayIconInfo> {
        return call<TrayIconInfo>(this.transport, "PUT", `tray/${segment(id)}`, { json: icon, signal: options?.signal });
    }

    /** Removes an icon. */
    remove(id: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `tray/${segment(id)}`, { signal: options?.signal });
    }

    /** Replaces an icon's menu. */
    setMenu(id: string, menu: TrayMenuInput, options?: { signal?: AbortSignal }): Promise<TrayIconInfo> {
        return call<TrayIconInfo>(this.transport, "PUT", `tray/${segment(id)}/menu`, { json: menu, signal: options?.signal });
    }

    /** Removes an icon's menu. */
    clearMenu(id: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `tray/${segment(id)}/menu`, { signal: options?.signal });
    }

    /** Opens an icon's menu, as though it had been clicked. */
    showMenu(id: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `tray/${segment(id)}/menu/show`, { signal: options?.signal });
    }

    /** Shows a notification from the icon. */
    notify(id: string, notification: TrayNotification, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "POST", `tray/${segment(id)}/notification`, { json: notification, signal: options?.signal });
    }

    /** Cycles the icon through two or more frames. */
    startAnimation(id: string, animation: TrayAnimation, options?: { signal?: AbortSignal }): Promise<TrayIconInfo> {
        return call<TrayIconInfo>(this.transport, "PUT", `tray/${segment(id)}/animation`, { json: animation, signal: options?.signal });
    }

    /** Stops animating and restores the icon. */
    stopAnimation(id: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `tray/${segment(id)}/animation`, { signal: options?.signal });
    }

    /** An icon was clicked. Also delivered to background.js when no page is listening. */
    onClick(handler: (payload: TrayClick) => void): () => void {
        return this.transport.subscribe("tray.click", json => handler(JSON.parse(json) as TrayClick));
    }

    /** A menu item was chosen. Also delivered to background.js when no page is listening. */
    onMenu(handler: (payload: TrayMenuSelection) => void): () => void {
        return this.transport.subscribe("tray.menu", json => handler(JSON.parse(json) as TrayMenuSelection));
    }
}
