// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Wearables.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid, segment } from "./core.js";
import type { BridgeFile } from "./shared.js";

/** Shared context. */
export interface WearableContext {
    /** The context. */
    data: unknown;
    /** It was not JSON: `data` is its bytes as a base64 string. */
    binary: boolean;
    /** The node that shared it; null for this app's own. */
    nodeId: string | null;
}

/** Both sides' context. */
export interface WearableContextState {
    /** What this app last shared, or null. */
    sent: WearableContext | null;
    /** What the wearable last shared, or null. */
    received: WearableContext | null;
}

/** New context to share. */
export interface WearableContextUpdate {
    data: unknown;
}

/** A file to queue for the wearable. */
export interface WearableFileRequest {
    /** What it is — `maps/offline`. */
    path: string;
    /** The file, in a root on disk. */
    file: BridgeFile;
    /** Strings the companion app receives with it. */
    metadata?: Record<string, string> | null;
}

/** A live message from the wearable. */
export interface WearableMessage {
    /** What it is about. */
    path: string;
    /** The body. */
    data: unknown;
    /** The body was not JSON: `data` is its bytes as a base64 string. */
    binary: boolean;
    /** The node that sent it. */
    nodeId: string | null;
    /** The sender waits on a reply — what a `wearables.message` handler returns. */
    expectsReply: boolean;
}

/** A live message to send. */
export interface WearableMessageRequest {
    /** What it is about — `sync`, `workout/start`. */
    path: string;
    /** The body, any JSON value. Keep it small: about 64 KB on iOS, 100 KB on Wear OS. */
    data?: unknown | null;
    /** Wear OS only: the node to send to. Omitted, the nearby node that runs the companion app. */
    nodeId?: string | null;
}

/** A connected wearable. */
export interface WearableNode {
    /** The node id — always `watch` on iOS, which has one active watch. */
    id: string;
    /** The name the platform gives it. */
    displayName: string;
    /** Directly connected rather than reached through the cloud. */
    isNearby: boolean;
    /** Runs the companion app. */
    hasApp: boolean;
}

/** An outgoing transfer or file the wearable has not received yet. */
export interface WearablePendingTransfer {
    /** The id the send returned. */
    id: string;
    /** What it is. */
    path: string;
    /** Data or a file. */
    kind: WearableTransferKind;
    /** 0–1 where the platform reports it (iOS files); null otherwise. */
    progress: number | null;
}

/** A file from the wearable, filed into a file root. */
export interface WearableReceivedFile {
    /** The sender's transfer id. */
    id: string;
    /** What the sender said it is. */
    path: string;
    /** The file's name on the sender. */
    fileName: string;
    /** Where it is now — read, move or delete it through the files bridge. */
    file: BridgeFile;
    /** Its size in bytes. */
    size: number;
    /** The strings sent with it. */
    metadata: Record<string, string>;
    /** The node that sent it. */
    nodeId: string | null;
}

/** The companion app's reply to a message. */
export interface WearableReply {
    /** The reply; JSON null when the companion app replied with nothing. */
    data: unknown;
    /** The reply was not JSON: `data` is its bytes as a base64 string. */
    binary: boolean;
}

/** Whether there is a wearable to talk to. */
export interface WearableStatus {
    /** False where the platform has no wearable API — anything but iOS and Android, an iPad, an Android device without the Wear OS app. */
    supported: boolean;
    /** A wearable is paired (iOS) or connected (Android). */
    paired: boolean;
    /** The companion app is installed on it. */
    appInstalled: boolean;
    /** A live message can be sent now. Context, transfers and files queue and do not need this. */
    reachable: boolean;
    /** The wearables the platform reports. */
    nodes: WearableNode[];
}

/** A queued transfer from the wearable. */
export interface WearableTransfer {
    id: string;
    path: string;
    data: unknown;
    binary: boolean;
    nodeId: string | null;
}

/** An outgoing transfer or file finished. */
export interface WearableTransferCompleted {
    /** The id the send returned. */
    id: string;
    /** What it was; empty on Wear OS, where the delivery receipt carries only the id. */
    path: string;
    /** Data or a file. */
    kind: WearableTransferKind;
    /** The wearable received it. */
    succeeded: boolean;
    /** Why it failed or was cancelled; null when delivered. */
    error: string | null;
}

export type WearableTransferKind = "Data" | "File";

/** Data to queue for the wearable. */
export interface WearableTransferRequest {
    /** What it is. */
    path: string;
    /** Any JSON value. */
    data: unknown;
}

/** A queued transfer or file. */
export interface WearableTransferTicket {
    /** What `wearables.completed` and the pending list report it by. */
    id: string;
}

/** The companion app on a paired Apple Watch or Wear OS device. Bodies are JSON: what the page sends reaches the watch as UTF-8 JSON, and what the watch sends reaches the page as JSON — or, when it is not JSON, as a base64 string with `binary` set. Files are `BridgeFile`s, so they move through the files bridge's roots. */
export class WearablesBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** Whether a wearable is paired, has the companion app, and is reachable for live messages. */
    getStatus(options?: { signal?: AbortSignal }): Promise<WearableStatus> {
        return call<WearableStatus>(this.transport, "GET", `wearables`, { signal: options?.signal });
    }

    /** Sends a live message and waits for the companion app's reply. Fails with 409 (`not_reachable`) when no wearable is reachable — a message never queues; use `transfer` for that. */
    sendMessage(message: WearableMessageRequest, options?: { signal?: AbortSignal }): Promise<WearableReply> {
        return call<WearableReply>(this.transport, "POST", `wearables/messages`, { json: message, signal: options?.signal });
    }

    /** The context this app last shared and the context the wearable last shared. */
    getContext(options?: { signal?: AbortSignal }): Promise<WearableContextState> {
        return call<WearableContextState>(this.transport, "GET", `wearables/context`, { signal: options?.signal });
    }

    /** Replaces the context shared with the wearable. Only the latest value is kept; it arrives when the wearable can take it. */
    updateContext(context: WearableContextUpdate, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "PUT", `wearables/context`, { json: context, signal: options?.signal });
    }

    /** Queues data for the wearable, delivered in order even if it is out of range or its app is not running. */
    transfer(transfer: WearableTransferRequest, options?: { signal?: AbortSignal }): Promise<WearableTransferTicket> {
        return call<WearableTransferTicket>(this.transport, "POST", `wearables/transfers`, { json: transfer, signal: options?.signal });
    }

    /** Queues a file from a file root for the wearable. Fails with 404 when the file does not exist. The platform reads it while it transfers, so leave it in place until `onTransferCompleted` reports the id. */
    sendFile(file: WearableFileRequest, options?: { signal?: AbortSignal }): Promise<WearableTransferTicket> {
        return call<WearableTransferTicket>(this.transport, "POST", `wearables/files`, { json: file, signal: options?.signal });
    }

    /** Outgoing transfers and files the wearable has not received yet. */
    getPendingTransfers(options?: { signal?: AbortSignal }): Promise<WearablePendingTransfer[]> {
        return call<WearablePendingTransfer[]>(this.transport, "GET", `wearables/transfers`, { signal: options?.signal });
    }

    /** Cancels an outgoing transfer or file. Fails with 404 when nothing pending has the id. */
    cancelTransfer(id: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `wearables/transfers/${segment(id)}`, { signal: options?.signal });
    }

    /** The wearable was paired or unpaired, installed or removed the app, or became reachable or unreachable. */
    onStatusChanged(handler: (payload: WearableStatus) => void): Promise<() => void> {
        return this.transport.subscribe("wearables.status", json => handler(JSON.parse(json) as WearableStatus));
    }

    /** A live message arrived. To answer it, register a `wearables.message` handler instead (page or background.js): what the handler returns is the reply. */
    onMessage(handler: (payload: WearableMessage) => void): Promise<() => void> {
        return this.transport.subscribe("wearables.message", json => handler(JSON.parse(json) as WearableMessage));
    }

    /** The wearable shared new context. Also handed to a `wearables.context` handler. */
    onContext(handler: (payload: WearableContext) => void): Promise<() => void> {
        return this.transport.subscribe("wearables.context", json => handler(JSON.parse(json) as WearableContext));
    }

    /** A queued transfer arrived. Also handed to a `wearables.transfer` handler. */
    onTransfer(handler: (payload: WearableTransfer) => void): Promise<() => void> {
        return this.transport.subscribe("wearables.transfer", json => handler(JSON.parse(json) as WearableTransfer));
    }

    /** A file arrived and was filed into a file root. Also handed to a `wearables.file` handler. */
    onFile(handler: (payload: WearableReceivedFile) => void): Promise<() => void> {
        return this.transport.subscribe("wearables.file", json => handler(JSON.parse(json) as WearableReceivedFile));
    }

    /** An outgoing transfer or file was delivered, failed, or was cancelled. */
    onTransferCompleted(handler: (payload: WearableTransferCompleted) => void): Promise<() => void> {
        return this.transport.subscribe("wearables.completed", json => handler(JSON.parse(json) as WearableTransferCompleted));
    }
}
