// <auto-generated/>
// Generated by tools/Shiny.AppDeviceBridge.TypeScript from Shiny.AppDeviceBridge.Wifi.Client. Do not edit; run the tool instead.
import { type BridgeTransport, browserTransport, call, callVoid, query } from "./core.js";
import type { AccessState } from "./shared.js";

export interface HotspotChangedEvent {
    /** The hotspot now; null when it stopped. */
    current: HotspotInfo | null;
}

/** A device connected to the hotspot. */
export interface HotspotClient {
    macAddress: string;
    ipAddress: string | null;
    hostName: string | null;
}

/** A running hotspot. */
export interface HotspotInfo {
    ssid: string;
    passphrase: string | null;
    security: WifiSecurity;
    band: WifiBand;
    address: string | null;
}

/** A hotspot to start. Every field is optional. */
export interface HotspotStartRequest {
    ssid?: string | null;
    passphrase?: string | null;
    band?: WifiBand;
    isHidden?: boolean;
}

export interface HotspotStatus {
    /** Whether the platform supports a hotspot and the app registered it. */
    supported: boolean;
    /** Whether one this app started is running. */
    running: boolean;
    /** The hotspot, when one is running. */
    current: HotspotInfo | null;
}

/** A network saved on the device. */
export interface KnownWifiNetwork {
    /** An int on Android, a UUID on Linux, the SSID itself on Apple platforms. */
    id: string;
    ssid: string;
    security: WifiSecurity;
    isHidden: boolean;
    addedByThisApp: boolean;
}

export interface WifiAccessResult {
    access: AccessState;
}

export type WifiBand = "Unknown" | "TwoPointFourGhz" | "FiveGhz" | "SixGhz";

/** Something a platform's Wi-Fi can do. */
export type WifiCapability = "Scan" | "Connect" | "Disconnect" | "CurrentNetwork" | "RadioState" | "RadioToggle" | "Hotspot" | "HotspotCustomConfiguration" | "HotspotClients" | "KnownNetworks" | "ForgetNetwork" | "ConnectKnownNetwork";

export interface WifiChangedEvent {
    /** The network now; null when the device left Wi-Fi. */
    current: WifiNetworkInfo | null;
}

/** A network to join: by `ssid`, or a saved one by `knownNetworkId`. */
export interface WifiConnectRequest {
    ssid?: string | null;
    passphrase?: string | null;
    security?: WifiSecurity;
    /** Join this access point in particular. */
    bssid?: string | null;
    isHidden?: boolean;
    /** Save the network on the device. */
    remember?: boolean;
    /** How long to wait for the connection, in milliseconds; the platform's default when null. */
    timeoutMs?: number | null;
    /** A saved network's `id`, instead of an SSID. */
    knownNetworkId?: string | null;
}

/** The network the device is on. */
export interface WifiNetworkInfo {
    interfaceName: string;
    ssid: string | null;
    bssid: string | null;
    security: WifiSecurity;
    ipAddresses: string[];
    dnsAddresses: string[];
    gateway: string | null;
    subnetMask: string | null;
    signalStrengthDbm: number | null;
    signalStrengthPercent: number | null;
    frequencyMhz: number | null;
    band: WifiBand;
    channel: number | null;
}

export interface WifiRadioState {
    enabled: boolean;
}

/** A network in range. */
export interface WifiScanResult {
    ssid: string;
    bssid: string | null;
    security: WifiSecurity;
    signalStrengthDbm: number | null;
    signalStrengthPercent: number;
    frequencyMhz: number | null;
    band: WifiBand;
    channel: number | null;
    isHidden: boolean;
    isOpen: boolean;
}

export type WifiSecurity = "Unknown" | "Open" | "Wep" | "WpaPsk" | "Wpa2Psk" | "Wpa3Psk" | "Enterprise" | "Owe" | "Psk";

/** Wi-Fi on this device. */
export interface WifiStatus {
    /** What this platform can do. Calls outside it fail with 501. */
    capabilities: WifiCapability[];
    /** The network the device is on, where the platform can tell. */
    current: WifiNetworkInfo | null;
    /** Whether the app registered the hotspot and the platform supports one. */
    hotspotSupported: boolean;
}

/** Wi-Fi: scanning, the current network, joining and forgetting networks, the radio, and a hotspot. What works varies more by platform than for any other bridge — iOS cannot scan, Android cannot toggle the radio — so check `capabilities`; a call the platform lacks fails with 501. */
export class WifiBridge {
    constructor(private readonly transport: BridgeTransport = browserTransport()) {}

    /** What this platform can do, the current network, and whether a hotspot is available. */
    getStatus(options?: { signal?: AbortSignal }): Promise<WifiStatus> {
        return call<WifiStatus>(this.transport, "GET", `wifi`, { signal: options?.signal });
    }

    /** Requests the permission Wi-Fi needs here — location on Android. */
    requestAccess(options?: { signal?: AbortSignal }): Promise<WifiAccessResult> {
        return call<WifiAccessResult>(this.transport, "POST", `wifi/access`, { signal: options?.signal });
    }

    /** Scans for networks in range. */
    scan(options?: { signal?: AbortSignal }): Promise<WifiScanResult[]> {
        return call<WifiScanResult[]>(this.transport, "GET", `wifi/networks`, { signal: options?.signal });
    }

    /** The network the device is on. Null when it is not on Wi-Fi. */
    getCurrentNetwork(options?: { signal?: AbortSignal }): Promise<WifiNetworkInfo | null> {
        return call<WifiNetworkInfo | null>(this.transport, "GET", `wifi/current`, { signal: options?.signal });
    }

    /** Joins a network by SSID, or a saved one by id. iOS asks the user first. Fails with 409 when the connection fails, 403 when permission is missing. */
    connect(request: WifiConnectRequest, options?: { signal?: AbortSignal }): Promise<WifiNetworkInfo> {
        return call<WifiNetworkInfo>(this.transport, "POST", `wifi/connection`, { json: request, signal: options?.signal });
    }

    /** Disconnects from the current network. */
    disconnect(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `wifi/connection`, { signal: options?.signal });
    }

    /** The networks saved on the device that this app can see. */
    getKnownNetworks(options?: { signal?: AbortSignal }): Promise<KnownWifiNetwork[]> {
        return call<KnownWifiNetwork[]>(this.transport, "GET", `wifi/known`, { signal: options?.signal });
    }

    /** Forgets a saved network. */
    forget(id: string, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `wifi/known` + query({ id: id }), { signal: options?.signal });
    }

    /** Whether the Wi-Fi radio is on. */
    getRadio(options?: { signal?: AbortSignal }): Promise<WifiRadioState> {
        return call<WifiRadioState>(this.transport, "GET", `wifi/radio`, { signal: options?.signal });
    }

    /** Turns the Wi-Fi radio on or off. */
    setRadio(state: WifiRadioState, options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "PUT", `wifi/radio`, { json: state, signal: options?.signal });
    }

    /** Whether a hotspot is supported and running. */
    getHotspot(options?: { signal?: AbortSignal }): Promise<HotspotStatus> {
        return call<HotspotStatus>(this.transport, "GET", `wifi/hotspot`, { signal: options?.signal });
    }

    /** Starts a hotspot. Every field of the request is optional; the platform picks what is not given. */
    startHotspot(request: HotspotStartRequest, options?: { signal?: AbortSignal }): Promise<HotspotInfo> {
        return call<HotspotInfo>(this.transport, "POST", `wifi/hotspot`, { json: request, signal: options?.signal });
    }

    /** Stops the hotspot. */
    stopHotspot(options?: { signal?: AbortSignal }): Promise<void> {
        return callVoid(this.transport, "DELETE", `wifi/hotspot`, { signal: options?.signal });
    }

    /** The devices connected to a hotspot this app started. Fails with 409 when it is not running. */
    getHotspotClients(options?: { signal?: AbortSignal }): Promise<HotspotClient[]> {
        return call<HotspotClient[]>(this.transport, "GET", `wifi/hotspot/clients`, { signal: options?.signal });
    }

    /** The device joined, left or changed networks. */
    onChanged(handler: (payload: WifiChangedEvent) => void): () => void {
        return this.transport.subscribe("wifi.changed", json => handler(JSON.parse(json) as WifiChangedEvent));
    }

    /** The hotspot started, stopped or changed. */
    onHotspotChanged(handler: (payload: HotspotChangedEvent) => void): () => void {
        return this.transport.subscribe("wifi.hotspot", json => handler(JSON.parse(json) as HotspotChangedEvent));
    }
}
