using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Shiny.AppDeviceBridge.Client.SourceGenerators;

/// <summary>
/// Turns a <c>[BridgeClient]</c> interface into its implementation over <c>IBridgeTransport</c>.
/// <para>
/// Every decision is made here — which parameter is the route, the query or the body, which JSON metadata reads the
/// response — so the emitted client does no reflection at all, and a declaration it cannot honour is a build error
/// pointing at the method rather than a request that fails on a device.
/// </para>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class BridgeClientGenerator : IIncrementalGenerator
{
    const string Namespace = "Shiny.AppDeviceBridge.Client";
    const string ClientAttribute = Namespace + ".BridgeClientAttribute";
    const string RouteAttribute = Namespace + ".BridgeRouteAttribute";
    const string EventAttribute = Namespace + ".BridgeEventAttribute";
    const string BodyAttribute = Namespace + ".BridgeBodyAttribute";
    const string QueryAttribute = Namespace + ".BridgeQueryAttribute";

    const string Calls = "global::Shiny.AppDeviceBridge.Client.BridgeCalls";
    const string Transport = "global::Shiny.AppDeviceBridge.Client.IBridgeTransport";

    static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .AddMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    static readonly DiagnosticDescriptor Unsupported = new(
        "ADB001",
        "Bridge client member cannot be generated",
        "{0}",
        "Shiny.AppDeviceBridge.Client",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true
    );

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var clients = context.SyntaxProvider.ForAttributeWithMetadataName(
            ClientAttribute,
            static (node, _) => node is InterfaceDeclarationSyntax,
            static (ctx, ct) => Build((INamedTypeSymbol)ctx.TargetSymbol, ctx.Attributes[0])
        );

        context.RegisterSourceOutput(clients, static (spc, result) =>
        {
            foreach (var problem in result.Problems)
                spc.ReportDiagnostic(Diagnostic.Create(Unsupported, problem.Location, problem.Message));

            if (result.Source is { } source)
                spc.AddSource(result.HintName, source);
        });
    }

    static Result Build(INamedTypeSymbol iface, AttributeData attribute)
    {
        var problems = new List<Problem>();
        var bridgeName = attribute.ConstructorArguments.Length > 0 ? attribute.ConstructorArguments[0].Value as string ?? "" : "";
        var context = attribute.ConstructorArguments.Length > 1 ? attribute.ConstructorArguments[1].Value as INamedTypeSymbol : null;

        if (context is null)
        {
            problems.Add(new(iface.Locations.FirstOrDefault(), $"[BridgeClient] on {iface.Name} needs a JsonSerializerContext type."));
            return new(Hint(iface), null, problems);
        }

        var ns = iface.ContainingNamespace.IsGlobalNamespace ? null : iface.ContainingNamespace.ToDisplayString();
        var interfaceName = iface.ToDisplayString(TypeFormat);
        var className = ClassName(iface);
        var contextName = context.ToDisplayString(TypeFormat);

        var members = new StringBuilder();
        var extensions = new StringBuilder();

        foreach (var method in iface.GetMembers().OfType<IMethodSymbol>().Where(x => x.MethodKind == MethodKind.Ordinary))
        {
            var route = method.GetAttributes().FirstOrDefault(x => Inherits(x.AttributeClass, RouteAttribute));
            var @event = method.GetAttributes().FirstOrDefault(x => x.AttributeClass?.ToDisplayString() == EventAttribute);

            if (route is not null)
                WriteCall(members, method, route, bridgeName, contextName, problems);
            else if (@event is not null)
                WriteEvent(members, extensions, method, @event, interfaceName, contextName, problems);
            else
                problems.Add(new(method.Locations.FirstOrDefault(), $"{iface.Name}.{method.Name} has no [BridgeGet]/[BridgePost]/[BridgePut]/[BridgeDelete] or [BridgeEvent] attribute."));
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();

        if (ns is not null)
            source.AppendLine($"namespace {ns};").AppendLine();

        source.AppendLine($"/// <summary>The generated implementation of <see cref=\"{iface.Name}\"/>, over the page's bridge transport.</summary>");
        source.AppendLine($"public sealed partial class {className} : {interfaceName}");
        source.AppendLine("{");
        source.AppendLine($"    readonly {Transport} transport;");
        source.AppendLine();
        source.AppendLine($"    public {className}({Transport} transport)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(transport);");
        source.AppendLine("        this.transport = transport;");
        source.AppendLine("    }");
        source.Append(members);
        source.AppendLine("}");
        source.AppendLine();

        var registration = className.EndsWith("Client", StringComparison.Ordinal) ? className : className + "Client";
        source.AppendLine($"/// <summary>Registering and using <see cref=\"{iface.Name}\"/>.</summary>");
        source.AppendLine($"public static partial class {className}Extensions");
        source.AppendLine("{");
        source.AppendLine($"    /// <summary>Registers <see cref=\"{iface.Name}\"/>. The page's transport comes from the client package — <c>AddWebAppHostClient()</c> for Blazor.</summary>");
        source.AppendLine($"    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection Add{registration}(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(services);");
        source.AppendLine($"        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(services, global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Scoped<{interfaceName}, {className}>());");
        source.AppendLine("        return services;");
        source.AppendLine("    }");
        source.Append(extensions);
        source.AppendLine("}");

        return new(Hint(iface), source.ToString(), problems);
    }

    static void WriteCall(StringBuilder members, IMethodSymbol method, AttributeData route, string bridgeName, string contextName, List<Problem> problems)
    {
        var location = method.Locations.FirstOrDefault();
        var verb = VerbOf(route);
        var pattern = route.ConstructorArguments.Length > 0 ? route.ConstructorArguments[0].Value as string ?? "" : "";
        var tokens = new HashSet<string>(Regex.Matches(pattern, @"\{(\w+)\}").Cast<Match>().Select(m => m.Groups[1].Value), StringComparer.Ordinal);

        string? cancellation = null;
        string? body = null;
        var query = new List<string>();
        var path = pattern.Trim('/');

        foreach (var parameter in method.Parameters)
        {
            if (parameter.RefKind != RefKind.None || parameter.IsParams)
            {
                problems.Add(new(location, $"{method.Name}: parameter '{parameter.Name}' cannot be ref, out or params."));
                continue;
            }

            var type = parameter.Type;
            var bodyAttribute = parameter.GetAttributes().FirstOrDefault(x => x.AttributeClass?.ToDisplayString() == BodyAttribute);

            if (type.ToDisplayString() == "System.Threading.CancellationToken")
            {
                cancellation = parameter.Name;
            }
            else if (tokens.Contains(parameter.Name))
            {
                if (!IsSimple(type))
                {
                    problems.Add(new(location, $"{method.Name}: route parameter '{parameter.Name}' must be a string, number, Guid or enum."));
                    continue;
                }

                // Parenthesised: inside an interpolation hole, the first ':' of "global::" would start a format specifier.
                path = path.Replace("{" + parameter.Name + "}", "{(" + Calls + ".Segment(" + ToText(parameter.Name, type) + "))}");
                tokens.Remove(parameter.Name);
            }
            else if (bodyAttribute is not null || (!IsSimple(type) && verb is "POST" or "PUT"))
            {
                if (body is not null)
                {
                    problems.Add(new(location, $"{method.Name}: only one parameter can be the body."));
                    continue;
                }

                var contentType = bodyAttribute?.ConstructorArguments.FirstOrDefault().Value as string ?? "application/json";
                body = type.ToDisplayString() switch
                {
                    "System.IO.Stream" or "byte[]" or "string" when contentType != "application/json"
                        => $"{Calls}.Raw({parameter.Name}, \"{contentType}\")",
                    "System.IO.Stream" or "byte[]"
                        => $"{Calls}.Raw({parameter.Name}, \"application/octet-stream\")",
                    _ => $"{Calls}.Json({parameter.Name}, {Calls}.TypeInfo<{type.ToDisplayString(TypeFormat)}>({contextName}.Default))"
                };
            }
            else if (IsSimple(type))
            {
                var name = parameter.GetAttributes().FirstOrDefault(x => x.AttributeClass?.ToDisplayString() == QueryAttribute)
                    ?.ConstructorArguments.FirstOrDefault().Value as string ?? parameter.Name;

                query.Add(QueryAdd(name, parameter.Name, type));
            }
            else
            {
                problems.Add(new(location, $"{method.Name}: '{parameter.Name}' is a complex type on a {verb}. Send it with POST or PUT, or pass its values as simple parameters."));
            }
        }

        foreach (var missing in tokens)
            problems.Add(new(location, $"{method.Name}: the route names {{{missing}}} but no parameter has that name."));

        var fullPath = bridgeName.Trim('/') + (path.Length > 0 ? "/" + path : "");
        var returnType = method.ReturnType as INamedTypeSymbol;
        var result = returnType is { IsGenericType: true } && returnType.ConstructedFrom.ToDisplayString() == "System.Threading.Tasks.Task<TResult>"
            ? returnType.TypeArguments[0]
            : null;

        if (returnType?.ToDisplayString() != "System.Threading.Tasks.Task" && result is null)
        {
            problems.Add(new(location, $"{method.Name} must return Task or Task<T>."));
            return;
        }

        var token = cancellation ?? "default";
        var content = body ?? "null";
        var httpMethod = $"global::System.Net.Http.HttpMethod.{Pascal(verb)}";

        members.AppendLine();
        members.AppendLine($"    public {method.ReturnType.ToDisplayString(TypeFormat)} {method.Name}({Parameters(method)})");
        members.AppendLine("    {");

        var target = $"$\"{fullPath}\"";
        if (query.Count > 0)
        {
            members.AppendLine("        var __query = new global::Shiny.AppDeviceBridge.Client.BridgeQuery();");
            foreach (var add in query)
                members.AppendLine($"        {add};");
            target = $"$\"{fullPath}\" + __query";
        }

        var call = result?.ToDisplayString() switch
        {
            null => $"{Calls}.SendAsync(this.transport, {httpMethod}, {target}, {content}, {token})",
            "System.IO.Stream" => $"{Calls}.SendForStreamAsync(this.transport, {httpMethod}, {target}, {content}, {token})",
            "byte[]" => $"{Calls}.SendForBytesAsync(this.transport, {httpMethod}, {target}, {content}, {token})",
            _ => $"{Calls}.SendAsync(this.transport, {httpMethod}, {target}, {content}, {Calls}.TypeInfo<{result.ToDisplayString(TypeFormat)}>({contextName}.Default), {token})"
        };

        members.AppendLine($"        return {call};");
        members.AppendLine("    }");
    }

    static void WriteEvent(StringBuilder members, StringBuilder extensions, IMethodSymbol method, AttributeData attribute, string interfaceName, string contextName, List<Problem> problems)
    {
        var location = method.Locations.FirstOrDefault();
        var eventName = attribute.ConstructorArguments.FirstOrDefault().Value as string ?? "";

        var handler = method.Parameters.Length == 1 ? method.Parameters[0].Type as INamedTypeSymbol : null;
        var isFunc = handler is { IsGenericType: true }
            && handler.ConstructedFrom.ToDisplayString() == "System.Func<T, TResult>"
            && handler.TypeArguments[1].ToDisplayString() == "System.Threading.Tasks.Task";

        if (!isFunc || method.ReturnType.ToDisplayString() != "System.Threading.Tasks.Task<System.IAsyncDisposable>")
        {
            problems.Add(new(location, $"{method.Name} must be shaped Task<IAsyncDisposable> {method.Name}(Func<TPayload, Task> handler)."));
            return;
        }

        var payload = handler!.TypeArguments[0].ToDisplayString(TypeFormat);
        var parameter = method.Parameters[0].Name;

        members.AppendLine();
        members.AppendLine($"    public global::System.Threading.Tasks.Task<global::System.IAsyncDisposable> {method.Name}(global::System.Func<{payload}, global::System.Threading.Tasks.Task> {parameter})");
        members.AppendLine($"        => {Calls}.SubscribeAsync(this.transport, \"{eventName}\", {parameter}, {Calls}.TypeInfo<{payload}>({contextName}.Default));");

        extensions.AppendLine();
        extensions.AppendLine($"    /// <summary>Subscribes to <c>{eventName}</c> with a handler that does not return a task.</summary>");
        extensions.AppendLine($"    public static global::System.Threading.Tasks.Task<global::System.IAsyncDisposable> {method.Name}(this {interfaceName} bridge, global::System.Action<{payload}> {parameter})");
        extensions.AppendLine("    {");
        extensions.AppendLine($"        global::System.ArgumentNullException.ThrowIfNull({parameter});");
        extensions.AppendLine($"        return bridge.{method.Name}(payload => {{ {parameter}(payload); return global::System.Threading.Tasks.Task.CompletedTask; }});");
        extensions.AppendLine("    }");
    }

    static string VerbOf(AttributeData route) => route.AttributeClass!.Name switch
    {
        "BridgeGetAttribute" => "GET",
        "BridgePostAttribute" => "POST",
        "BridgePutAttribute" => "PUT",
        "BridgeDeleteAttribute" => "DELETE",
        _ => "GET"
    };

    static string Pascal(string verb) => verb.Substring(0, 1) + verb.Substring(1).ToLowerInvariant();

    static bool Inherits(INamedTypeSymbol? type, string name)
    {
        for (var current = type; current is not null; current = current.BaseType)
        {
            if (current.ToDisplayString() == name)
                return true;
        }

        return false;
    }

    static ITypeSymbol Underlying(ITypeSymbol type)
        => type is INamedTypeSymbol { IsGenericType: true } named && named.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T
            ? named.TypeArguments[0]
            : type;

    static bool IsSimple(ITypeSymbol type)
    {
        var t = Underlying(type);

        if (t.TypeKind == TypeKind.Enum)
            return true;

        return t.SpecialType is SpecialType.System_String or SpecialType.System_Boolean
                   or SpecialType.System_Byte or SpecialType.System_Int16 or SpecialType.System_Int32 or SpecialType.System_Int64
                   or SpecialType.System_Single or SpecialType.System_Double or SpecialType.System_Decimal or SpecialType.System_DateTime
               || t.ToDisplayString() is "System.DateTimeOffset" or "System.Guid" or "System.TimeSpan";
    }

    static string QueryAdd(string name, string parameter, ITypeSymbol type)
    {
        var t = Underlying(type);
        var nullable = !ReferenceEquals(t, type);
        var literal = "\"" + name + "\"";

        if (t.TypeKind == TypeKind.Enum)
            return $"__query.AddEnum<{t.ToDisplayString(TypeFormat)}>({literal}, {parameter})";

        return t.SpecialType switch
        {
            SpecialType.System_String => $"__query.Add({literal}, {parameter})",
            SpecialType.System_Boolean => $"__query.Add({literal}, (bool?){parameter})",
            SpecialType.System_Byte or SpecialType.System_Int16 or SpecialType.System_Int32 => $"__query.Add({literal}, (int?){parameter})",
            SpecialType.System_Int64 => $"__query.Add({literal}, (long?){parameter})",
            SpecialType.System_Single or SpecialType.System_Double => $"__query.Add({literal}, (double?){parameter})",
            SpecialType.System_Decimal => nullable
                ? $"__query.Add({literal}, {parameter}?.ToString(global::System.Globalization.CultureInfo.InvariantCulture))"
                : $"__query.Add({literal}, {parameter}.ToString(global::System.Globalization.CultureInfo.InvariantCulture))",
            SpecialType.System_DateTime => $"__query.Add({literal}, (global::System.DateTime?){parameter})",
            _ => $"__query.Add({literal}, ({t.ToDisplayString(TypeFormat)}?){parameter})"
        };
    }

    static string ToText(string parameter, ITypeSymbol type)
    {
        var t = Underlying(type);

        if (t.SpecialType == SpecialType.System_String)
            return parameter;

        if (t.TypeKind == TypeKind.Enum)
            return parameter + ".ToString()";

        return $"global::System.Convert.ToString({parameter}, global::System.Globalization.CultureInfo.InvariantCulture)";
    }

    static string Parameters(IMethodSymbol method)
        => String.Join(", ", method.Parameters.Select(p =>
        {
            var text = p.Type.ToDisplayString(TypeFormat) + " " + p.Name;

            if (p.HasExplicitDefaultValue)
                text += " = " + DefaultValue(p);

            return text;
        }));

    static string DefaultValue(IParameterSymbol parameter)
    {
        var value = parameter.ExplicitDefaultValue;
        var type = Underlying(parameter.Type);

        if (value is null)
            return parameter.Type.IsValueType && ReferenceEquals(type, parameter.Type) ? "default" : "null";

        if (type.TypeKind == TypeKind.Enum)
            return $"({type.ToDisplayString(TypeFormat)}){SymbolDisplay.FormatPrimitive(value, quoteStrings: false, useHexadecimalNumbers: false)}";

        return value switch
        {
            bool b => b ? "true" : "false",
            string s => SymbolDisplay.FormatLiteral(s, quote: true),
            long l => l + "L",
            double d => SymbolDisplay.FormatPrimitive(d, false, false) + "D",
            float f => SymbolDisplay.FormatPrimitive(f, false, false) + "F",
            decimal m => SymbolDisplay.FormatPrimitive(m, false, false) + "M",
            _ => SymbolDisplay.FormatPrimitive(value, quoteStrings: true, useHexadecimalNumbers: false)
        };
    }

    static string ClassName(INamedTypeSymbol iface)
    {
        var name = iface.Name.Length > 1 && iface.Name[0] == 'I' && Char.IsUpper(iface.Name[1]) ? iface.Name.Substring(1) : iface.Name;
        return name + "Client";
    }

    static string Hint(INamedTypeSymbol iface) => iface.ToDisplayString().Replace('<', '_').Replace('>', '_') + ".BridgeClient.g.cs";

    sealed class Problem(Location? location, string message)
    {
        public Location? Location { get; } = location;

        public string Message { get; } = message;
    }

    /// <summary>
    /// The pipeline's output. Not value-equal, so the incremental cache regenerates on any change to the interface —
    /// which is all this generator ever looks at, and cheap enough to redo.
    /// </summary>
    sealed class Result(string hintName, string? source, List<Problem> problems)
    {
        public string HintName { get; } = hintName;

        public string? Source { get; } = source;

        public IReadOnlyList<Problem> Problems { get; } = problems;
    }
}
