using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using Shiny.AppDeviceBridge.Client;

namespace Shiny.AppDeviceBridge.TypeScript;

/// <summary>
/// The TypeScript half of the typed clients: one module per bridge client assembly, holding its contracts and a client
/// class, generated from the same [BridgeClient] interface the C# client is. Parameters are classified exactly as the
/// C# generator classifies them — route token, then body, then query — so the two clients send identical requests.
/// </summary>
public static partial class TypeScriptGenerator
{
    const string SharedAssembly = "Shiny.AppDeviceBridge.Client";
    const string Header = "// <auto-generated/>\n// Generated by tools/Shiny.AppDeviceBridge.TypeScript from {0}. Do not edit; run the tool instead.\n";

    /// <summary>File name → content, for every generated module and the index.</summary>
    public static IReadOnlyDictionary<string, string> Generate()
    {
        var assemblies = LoadClientAssemblies();
        var modules = new SortedDictionary<string, Module>(StringComparer.Ordinal);

        Module ModuleFor(Assembly assembly)
        {
            var name = ModuleName(assembly);
            if (!modules.TryGetValue(name, out var module))
                modules[name] = module = new Module(name, assembly);

            return module;
        }

        // The shared package first: it declares the built-in bridges, and every other module imports from it.
        foreach (var assembly in assemblies.Prepend(typeof(BridgeClientAttribute).Assembly))
        {
            foreach (var bridge in assembly.GetExportedTypes().Where(x => x.IsInterface && x.GetCustomAttribute<BridgeClientAttribute>() is not null))
            {
                var module = ModuleFor(assembly);
                module.Bridges.Add(bridge);
                Walk(bridge, ModuleFor);
            }
        }

        var files = new SortedDictionary<string, string>(StringComparer.Ordinal);
        foreach (var module in modules.Values)
            files[module.Name + ".ts"] = Emit(module, modules);

        files["index.ts"] = EmitIndex(modules.Values);
        return files;
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Discovery
    // ---------------------------------------------------------------------------------------------------------------

    static List<Assembly> LoadClientAssemblies()
        => [.. Directory.EnumerateFiles(AppContext.BaseDirectory, "Shiny.AppDeviceBridge.*.Client.dll")
            .Select(path => Assembly.Load(AssemblyName.GetAssemblyName(path)))
            .OrderBy(x => x.GetName().Name, StringComparer.Ordinal)];

    static string ModuleName(Assembly assembly)
    {
        var name = assembly.GetName().Name!;
        if (name == SharedAssembly)
            return "shared";

        var bridge = name["Shiny.AppDeviceBridge.".Length..^".Client".Length];
        return Kebab(bridge);
    }

    /// <summary>Records which declared types each module needs, and whether each is read, written, or both.</summary>
    static void Walk(Type bridge, Func<Assembly, Module> moduleFor)
    {
        foreach (var method in bridge.GetMethods())
        {
            if (method.GetCustomAttribute<BridgeEventAttribute>() is not null)
            {
                Collect(method.GetParameters()[0].ParameterType.GetGenericArguments()[0], Usage.Output, moduleFor);
                continue;
            }

            if (Result(method) is { } result)
                Collect(result, Usage.Output, moduleFor);

            var route = method.GetCustomAttribute<BridgeRouteAttribute>()!;
            foreach (var parameter in method.GetParameters())
            {
                var kind = Classify(parameter, route);
                Collect(parameter.ParameterType, kind == ParameterKind.Body ? Usage.Input : Usage.Output, moduleFor);
            }
        }
    }

    static void Collect(Type type, Usage usage, Func<Assembly, Module> moduleFor)
    {
        type = Nullable.GetUnderlyingType(type) ?? type;

        if (ElementType(type) is { } element)
        {
            Collect(element, usage, moduleFor);
            return;
        }

        if (!IsDeclared(type))
            return;

        var module = moduleFor(type.Assembly);
        if (module.Types.TryGetValue(type, out var existing))
        {
            // Read anywhere means every member is always present; that wins over the looser shape a request allows.
            if (existing == Usage.Output || usage == Usage.Input)
                return;

            module.Types[type] = Usage.Output;
            return;
        }

        module.Types[type] = usage;

        if (type.IsEnum)
            return;

        foreach (var property in Properties(type))
            Collect(property.PropertyType, usage, moduleFor);
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Emission
    // ---------------------------------------------------------------------------------------------------------------

    static string Emit(Module module, IReadOnlyDictionary<string, Module> modules)
    {
        var docs = XmlDocs.For(module.Assembly);
        var body = new StringBuilder();
        var imports = new SortedDictionary<string, SortedSet<string>>(StringComparer.Ordinal);

        string Ref(Type type)
        {
            var owner = ModuleName(type.Assembly);
            if (owner != module.Name)
            {
                if (!imports.TryGetValue(owner, out var names))
                    imports[owner] = names = new SortedSet<string>(StringComparer.Ordinal);

                names.Add(type.Name);
            }

            return type.Name;
        }

        foreach (var (type, usage) in module.Types.OrderBy(x => x.Key.Name, StringComparer.Ordinal))
        {
            body.AppendLine();
            WriteDoc(body, docs.Type(type), "");

            if (type.IsEnum)
            {
                body.AppendLine($"export type {type.Name} = {String.Join(" | ", Enum.GetNames(type).Select(x => $"\"{x}\""))};");
                continue;
            }

            body.AppendLine($"export interface {type.Name} {{");
            foreach (var property in Properties(type))
            {
                WriteDoc(body, docs.Property(property), "    ");

                var nullable = IsNullable(property);
                var optional = usage == Usage.Input && !IsRequired(property);
                var tsType = TsType(property.PropertyType, Ref, forParameter: usage == Usage.Input) + (nullable ? " | null" : "");

                body.AppendLine($"    {JsonName(property)}{(optional ? "?" : "")}: {tsType};");
            }

            body.AppendLine("}");
        }

        foreach (var bridge in module.Bridges.OrderBy(x => x.Name, StringComparer.Ordinal))
            WriteClient(body, bridge, docs, Ref);

        var text = new StringBuilder();
        text.AppendFormat(Header, module.Assembly.GetName().Name);

        if (module.Bridges.Count > 0)
        {
            var generated = body.ToString();
            var helpers = new[] { "browserTransport", "call", "callBlob", "callVoid", "dateText", "query", "segment" }
                .Where(helper => Regex.IsMatch(generated, $@"\b{helper}(<|\()"));

            text.AppendLine($"import {{ type BridgeTransport, {String.Join(", ", helpers)} }} from \"./core\";");
        }

        foreach (var (from, names) in imports)
            text.AppendLine($"import type {{ {String.Join(", ", names)} }} from \"./{from}\";");

        text.Append(body);
        return text.ToString();
    }

    static void WriteClient(StringBuilder body, Type bridge, XmlDocs docs, Func<Type, string> reference)
    {
        var attribute = bridge.GetCustomAttribute<BridgeClientAttribute>()!;
        var className = bridge.Name.Length > 1 && bridge.Name[0] == 'I' && Char.IsUpper(bridge.Name[1]) ? bridge.Name[1..] : bridge.Name;

        body.AppendLine();
        WriteDoc(body, docs.Type(bridge), "");
        body.AppendLine($"export class {className} {{");
        body.AppendLine("    constructor(private readonly transport: BridgeTransport = browserTransport()) {}");

        foreach (var method in bridge.GetMethods().OrderBy(x => x.MetadataToken))
        {
            body.AppendLine();
            WriteDoc(body, docs.Method(method), "    ");

            if (method.GetCustomAttribute<BridgeEventAttribute>() is { } @event)
            {
                var payload = reference(method.GetParameters()[0].ParameterType.GetGenericArguments()[0]);
                body.AppendLine($"    {MemberName(method)}(handler: (payload: {payload}) => void): () => void {{");
                body.AppendLine($"        return this.transport.subscribe(\"{@event.EventName}\", json => handler(JSON.parse(json) as {payload}));");
                body.AppendLine("    }");
                continue;
            }

            var route = method.GetCustomAttribute<BridgeRouteAttribute>()!;
            var parameters = method.GetParameters();
            var signature = new List<string>();
            var options = new List<string>();
            var queryParts = new List<string>();
            string? content = null;
            var path = attribute.Name.Trim('/') + (route.Pattern.Trim('/') is { Length: > 0 } p ? "/" + p : "");
            var hasSignal = false;

            // The trailing bag of optional arguments is "options" unless a parameter already has that name.
            var bag = parameters.Any(x => x.Name == "options") ? "requestOptions" : "options";

            foreach (var parameter in parameters)
            {
                var kind = Classify(parameter, route);
                var name = parameter.Name!;
                var optional = parameter.HasDefaultValue && kind != ParameterKind.Cancellation;
                var access = optional ? $"{bag}?.{name}" : name;

                switch (kind)
                {
                    case ParameterKind.Cancellation:
                        hasSignal = true;
                        continue;

                    case ParameterKind.Route:
                        path = path.Replace("{" + name + "}", "${segment(" + access + ")}");
                        break;

                    case ParameterKind.Query:
                        var queryName = parameter.GetCustomAttribute<BridgeQueryAttribute>()?.Name ?? name;
                        queryParts.Add($"{Quote(queryName)}: {(IsDate(parameter.ParameterType) ? $"dateText({access})" : access)}");
                        break;

                    case ParameterKind.Body:
                        var raw = parameter.GetCustomAttribute<BridgeBodyAttribute>();
                        content = IsRawBody(parameter.ParameterType)
                            ? $"body: {access}, contentType: \"{(raw is { ContentType: not "application/json" } ? raw.ContentType : "application/octet-stream")}\""
                            : $"json: {access}";
                        break;
                }

                var tsType = TsType(parameter.ParameterType, reference, forParameter: true)
                             + (IsNullable(parameter) ? " | null" : "");

                if (optional)
                    options.Add($"{name}?: {tsType}");
                else
                    signature.Add($"{name}: {tsType}");
            }

            if (hasSignal)
                options.Add("signal?: AbortSignal");

            if (options.Count > 0)
                signature.Add($"{bag}?: {{ {String.Join("; ", options)} }}");

            var target = "`" + path + "`" + (queryParts.Count > 0 ? $" + query({{ {String.Join(", ", queryParts)} }})" : "");
            var init = String.Join(", ", new[] { content, hasSignal ? $"signal: {bag}?.signal" : null }.Where(x => x is not null));
            var initText = init.Length > 0 ? $", {{ {init} }}" : "";
            var result = Result(method);

            var (returns, invocation) = result switch
            {
                null => ("Promise<void>", $"callVoid(this.transport, \"{route.Method}\", {target}{initText})"),
                _ when result == typeof(Stream) || result == typeof(byte[]) => ("Promise<Blob>", $"callBlob(this.transport, \"{route.Method}\", {target}{initText})"),
                _ => (TsType(result, reference, forParameter: false) + (IsNullableResult(method) ? " | null" : "")) is var resultType
                    ? ($"Promise<{resultType}>", $"call<{resultType}>(this.transport, \"{route.Method}\", {target}{initText})")
                    : default
            };

            body.AppendLine($"    {MemberName(method)}({String.Join(", ", signature)}): {returns} {{");
            body.AppendLine($"        return {invocation};");
            body.AppendLine("    }");
        }

        body.AppendLine("}");
    }

    static string EmitIndex(IEnumerable<Module> modules)
    {
        // One flat namespace for the page: a name declared twice would silently shadow, so it fails the build instead.
        var seen = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var module in modules)
        {
            foreach (var name in module.Types.Keys.Select(x => x.Name).Concat(module.Bridges.Select(x => x.Name[1..])))
            {
                if (seen.TryGetValue(name, out var other) && other != module.Name)
                    throw new InvalidOperationException($"'{name}' is declared by both the {other} and {module.Name} clients. Rename one of the contracts.");

                seen[name] = module.Name;
            }
        }

        var text = new StringBuilder();
        text.AppendFormat(Header, "every bridge client");
        text.AppendLine("export * from \"./core\";");
        foreach (var module in modules)
            text.AppendLine($"export * from \"./{module.Name}\";");

        return text.ToString();
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Types
    // ---------------------------------------------------------------------------------------------------------------

    static string TsType(Type type, Func<Type, string> reference, bool forParameter)
    {
        if (Nullable.GetUnderlyingType(type) is { } underlying)
            return TsType(underlying, reference, forParameter) + " | null";

        if (type == typeof(string) || type == typeof(char) || type == typeof(Guid) || type == typeof(TimeSpan)
            || type == typeof(Uri) || type == typeof(DateOnly) || type == typeof(TimeOnly))
            return "string";

        if (type == typeof(DateTime) || type == typeof(DateTimeOffset))
            return forParameter ? "Date | string" : "string";

        if (type == typeof(bool))
            return "boolean";

        if (type.IsPrimitive || type == typeof(decimal))
            return "number";

        if (type == typeof(byte[]))
            return forParameter ? "Blob | ArrayBuffer | Uint8Array" : "string";

        if (type == typeof(Stream))
            return "Blob | ArrayBuffer | Uint8Array";

        if (type == typeof(object) || type == typeof(JsonElement))
            return "unknown";

        if (DictionaryValue(type) is { } value)
            return $"Record<string, {TsType(value, reference, forParameter)}>";

        if (ElementType(type) is { } element)
        {
            var inner = TsType(element, reference, forParameter);
            return inner.Contains(' ') ? $"({inner})[]" : inner + "[]";
        }

        if (IsDeclared(type))
            return reference(type);

        // A framework enum such as DayOfWeek: its names, inline, since there is no contract module to declare it in.
        if (type.IsEnum)
            return "(" + String.Join(" | ", Enum.GetNames(type).Select(x => $"\"{x}\"")) + ")";

        throw new NotSupportedException($"{type} has no TypeScript mapping. Add one to TypeScriptGenerator.TsType.");
    }

    /// <summary>A contract type — declared in a bridge's own assembly — rather than a framework type the mapping covers.</summary>
    static bool IsDeclared(Type type)
        => type.Assembly.GetName().Name!.StartsWith("Shiny.AppDeviceBridge", StringComparison.Ordinal)
           && (type.IsEnum || type.IsClass || (type.IsValueType && !type.IsPrimitive));

    static bool IsDate(Type type) => (Nullable.GetUnderlyingType(type) ?? type) is var t && (t == typeof(DateTime) || t == typeof(DateTimeOffset));

    static bool IsRawBody(Type type) => type == typeof(Stream) || type == typeof(byte[]) || type == typeof(string);

    static Type? ElementType(Type type)
    {
        if (type == typeof(string) || type == typeof(byte[]))
            return null;

        if (type.IsArray)
            return type.GetElementType();

        if (DictionaryValue(type) is not null)
            return null;

        return type.IsGenericType && type.GetInterfaces().Append(type).Any(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IEnumerable<>))
            ? type.GetGenericArguments()[0]
            : null;
    }

    static Type? DictionaryValue(Type type)
        => type.GetInterfaces().Append(type)
            .FirstOrDefault(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IReadOnlyDictionary<,>) && i.GetGenericArguments()[0] == typeof(string))
            ?.GetGenericArguments()[1];

    static IEnumerable<PropertyInfo> Properties(Type type)
        => type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(x => x.GetIndexParameters().Length == 0 && x.GetCustomAttribute<JsonIgnoreAttribute>() is null)
            .OrderBy(x => x.MetadataToken);

    static string JsonName(PropertyInfo property)
        => property.GetCustomAttribute<JsonPropertyNameAttribute>()?.Name ?? JsonNamingPolicy.CamelCase.ConvertName(property.Name);

    /// <summary>
    /// A <c>required</c> member, or a positional record parameter with no default — either way the host cannot read the
    /// request without it.
    /// </summary>
    static bool IsRequired(PropertyInfo property)
        => property.GetCustomAttribute<RequiredMemberAttribute>() is not null
           || property.DeclaringType!.GetConstructors().Any(c => c.GetParameters().Any(p =>
               String.Equals(p.Name, property.Name, StringComparison.Ordinal) && !p.HasDefaultValue));

    /// <summary>A <c>Task&lt;T?&gt;</c> for a reference type: the call answers null when there is nothing.</summary>
    static bool IsNullableResult(MethodInfo method)
        => Result(method) is { IsValueType: false }
           && new NullabilityInfoContext().Create(method.ReturnParameter).GenericTypeArguments[0].ReadState == NullabilityState.Nullable;

    static bool IsNullable(PropertyInfo property)
        => !property.PropertyType.IsValueType && new NullabilityInfoContext().Create(property).ReadState == NullabilityState.Nullable;

    static bool IsNullable(ParameterInfo parameter)
        => !parameter.ParameterType.IsValueType && new NullabilityInfoContext().Create(parameter).WriteState == NullabilityState.Nullable;

    static Type? Result(MethodInfo method)
        => method.ReturnType.IsGenericType && method.ReturnType.GetGenericTypeDefinition() == typeof(Task<>)
            ? method.ReturnType.GetGenericArguments()[0]
            : null;

    static ParameterKind Classify(ParameterInfo parameter, BridgeRouteAttribute route)
    {
        if (parameter.ParameterType == typeof(CancellationToken))
            return ParameterKind.Cancellation;

        if (route.Pattern.Contains("{" + parameter.Name + "}", StringComparison.Ordinal))
            return ParameterKind.Route;

        var simple = IsSimple(parameter.ParameterType);
        if (parameter.GetCustomAttribute<BridgeBodyAttribute>() is not null || (!simple && route.Method is "POST" or "PUT"))
            return ParameterKind.Body;

        return ParameterKind.Query;
    }

    static bool IsSimple(Type type)
    {
        type = Nullable.GetUnderlyingType(type) ?? type;
        return type.IsEnum || type.IsPrimitive || type == typeof(string) || type == typeof(decimal) || type == typeof(DateTime)
               || type == typeof(DateTimeOffset) || type == typeof(Guid) || type == typeof(TimeSpan);
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Text
    // ---------------------------------------------------------------------------------------------------------------

    static void WriteDoc(StringBuilder body, string? doc, string indent)
    {
        if (String.IsNullOrWhiteSpace(doc))
            return;

        var lines = doc.Split('\n');
        if (lines.Length == 1)
        {
            body.AppendLine($"{indent}/** {lines[0]} */");
            return;
        }

        body.AppendLine($"{indent}/**");
        foreach (var line in lines)
            body.AppendLine(line.Length == 0 ? $"{indent} *" : $"{indent} * {line}");
        body.AppendLine($"{indent} */");
    }

    static string MemberName(MethodInfo method)
    {
        var name = method.Name.EndsWith("Async", StringComparison.Ordinal) ? method.Name[..^"Async".Length] : method.Name;
        return JsonNamingPolicy.CamelCase.ConvertName(name);
    }

    static string Quote(string name) => KebabOrIdentifier().IsMatch(name) ? name : $"\"{name}\"";

    static string Kebab(string pascal) => PascalBoundary().Replace(pascal, "$1-$2").ToLowerInvariant();

    [GeneratedRegex("^[A-Za-z_$][A-Za-z0-9_$]*$")]
    private static partial Regex KebabOrIdentifier();

    [GeneratedRegex("([a-z0-9])([A-Z])")]
    private static partial Regex PascalBoundary();

    enum Usage { Input, Output }

    enum ParameterKind { Cancellation, Route, Query, Body }

    sealed class Module(string name, Assembly assembly)
    {
        public string Name { get; } = name;

        public Assembly Assembly { get; } = assembly;

        public Dictionary<Type, Usage> Types { get; } = [];

        public List<Type> Bridges { get; } = [];
    }
}
